dandi/dandi-archive

dev/django.Dockerfile
=> Fix django.Dockerfile

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
This is what's going to back the My Dandisets page.
=> My dandisets filter

dandiapi/api/tasks.py
=> Fix the celery task failing in docker

dandiapi/api/tests/test_users.py, dandiapi/api/views/__init__.py, dandiapi/api/views/serializers.py, dandiapi/api/views/users.py, dandiapi/urls.py
=> User serializer admin

dandiapi/settings.py
This suppresses a warning from having a PAGE_SIZE set without a
DEFAULT_PAGINATION_CLASS.
=> Add DEFAULT_PAGINATION_CLASS

dandiapi/api/views/dandiset.py
Add a custom filter that orders dandisets by created date and name (actually the name of the most recent published version).
=> Add the ability to sort dandisets when listing

dandiapi/api/views/dandiset.py
=> Use ordering.endswith instead of slicing

dandiapi/api/mail.py, dandiapi/api/models/dandiset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
Users now receive emails whenever they are added or removed as owners of a dandiset.
=> Ownership emails

dandiapi/settings.py, setup.py
Please merge when this is approved.
=> Upstream django-composed-configuration now allows SessionAuthentication

dandiapi/api/models/asset.py, dandiapi/api/tests/test_version.py
=> 76 fix publish asset

dandiapi/api/views/search.py
I overthought implementing search the first time, hopefully this will have feature parity within reason.
I'm merging this immediately so I can test it against some real metadata.
=> Apply SearchVector directly to metadata for search

dandiapi/api/checksum.py, dandiapi/api/tasks.py, dandiapi/api/tests/conftest.py, dandiapi/api/tests/test_checksum.py, dandiapi/api/tests/test_validate.py
=> Stream checksum calculation rather than download to temporary file

dandiapi/api/views/asset.py
=> Order AssetViewSet by created to suppress pagination warning

dandiapi/api/models/version.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py, setup.py
=> dandiset.yaml and assets.yaml

dandiapi/api/tests/test_upload.py, dandiapi/api/views/upload.py
Should provide info to debug https://github.com/dandi/dandi-cli/pull/479#issuecomment-805056962
=> Report incorrect values when validation fails

dandiapi/api/doi.py
This involves fixing some typos to make the DOIs DataCite schema
compliant.
Fixes #180
=> Publish DOIs as they are created

dandiapi/api/multipart.py, dandiapi/api/tests/test_upload.py
=> Extend presigned URL expiration to 1 week

dandiapi/api/tests/conftest.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/settings.py
Done with a ton of help from @dchiquito.
Closes #152.
I am not sure who else should review this.
=> Supply content-disposition header for asset downloads

dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py
Turns out there is a native django way to deal with this: https://docs.djangoproject.com/en/3.1/ref/utils/#django.utils.decorators.method_decorator
May come in handy on Multinet
=> Method decorator permissions

.github/workflows/cli-integration.yml
Closes #42.
Blocked by https://github.com/dandi/dandi-cli/pull/500.
=> Set up integration tests with dandi-cli

dandiapi/api/migrations/0006_default_oauth_application.py
Fixes #186 
Restores https://github.com/dandi/dandi-api/commit/e62310cc11fe7ddd5aa7663c78e8f466b23e8daa#diff-7fab13f3a7b88ebfee8c8c0742[…]1b1fe9856211c9cdbb8e0c4ba471fcc
=> Create a default OAuth application so devs can log in

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
I'm holding off on merging this until the migration upload is finished to avoid any interruptions.
=> Add asset digests to asset metadata

DEVELOPMENT.md, dandiapi/api/models/version.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, scripts/refresh_metadata.py
* version
* id: i.e. 000000/draft
* url: i.e. https://identifiers.org/000000/draft
* citation: Jane Doe; John Doe (2021) Dandiset. Online: ...
Fixes #262 , #267
=> Add more computed fields to version metadata

dandiapi/api/__init__.py, dandiapi/api/mail.py, dandiapi/api/tests/test_users.py, dandiapi/api/user_migration.py
Requested by @satra so we can continue adding newly registered users to the slack channel.
=> Email on register

doc/design/doi-generation-1.md, doc/design/publish-1.md
This is my current understanding of the publish process and associated machinery.
Most of the juicy bits are the description of `Assets` and the `Publish process` section.
=> First draft of publish process

README.md
could be improved but at least reflects what currently works
=> DOC: adjusted README.md on how to authenticate

dandiapi/api/views/common.py
=> Increase max page size to 1000

doc/design/staging-1.md
Staging will be important for testing the publish process, so this is how we are envisioning staging will be used.
=> First draft of staging design doc

doc/design/staging-1.md
I forgot to clarify the development process in the original PR, here are those changes.
=> Clarify development procedures

dandiapi/api/doi.py, dandiapi/settings.py, setup.py
See https://github.com/dandi/dandischema/pull/33 for discussion of the approach taken here. That PR also blocks this one.
=> Use dandischema to compute DOIs

dandiapi/api/doi.py, dandiapi/api/models/asset.py, dandiapi/api/models/version.py, dandiapi/api/tasks.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py, dandiapi/settings.py, scripts/migrate_version_metadata.py, setup.py
This involves adding some stuff to make the computed + test metadata compliant with the new schema.
=> Bump metadata schema to 0.4.1

dandiapi/api/views/asset.py
Modifying asset metadata (through upload/update) triggers a save of the Version, which also populates and potentially modifies the version metadata.
Trigger metadata validation whenever `version.save()` is called in Asset views.
=> Validate version metadata triggers

dandiapi/api/mail.py, dandiapi/api/templates/api/mail/added_message.html, dandiapi/api/templates/api/mail/added_message.txt, dandiapi/api/templates/api/mail/registered_message.html, dandiapi/api/templates/api/mail/registered_message.txt, dandiapi/api/templates/api/mail/removed_message.html, dandiapi/api/templates/api/mail/removed_message.txt
This is significantly more maintainable than using inline strings.
=> Use Django templates to render email bodies

dandiapi/api/templates/api/mail/registered_message.html, dandiapi/api/templates/api/mail/registered_message.txt
@satra, did I get the links right?
@bendichter, does this look good to you?
I noticed that the HTML and text versions of the email sent to new users are not the same; this further pushes the need to resolve #314.
Closes #361.
=> Use correct link and text for helpdesk issues

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
This should resolve https://github.com/dandi/dandi-cli/issues/682#issuecomment-868803784
=> Fix default contributor

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
This should resolve https://github.com/dandi/dandi-cli/issues/682#issuecomment-868835699
FYI @mvandenburgh
=> Inject schemaVersion if not specified when creating dandisets

scripts/migrate_version_metadata.py
=> Trigger metadata validation after migrate_version_metadata

dandiapi/api/checksum.py, dandiapi/api/management/commands/migrate_version_metadata.py, dandiapi/api/management/commands/refresh_metadata.py, dandiapi/api/multipart.py
* Move a script that was added after Brian's PR
* Don't refresh metadata for published versions
=> Fix scripts

dandiapi/api/tests/test_version.py
I didn't properly update some tests in #401 so CI is currently failing, this PR fixes those.
=> Update CI tests for new version serializer field

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
There is no way to add a DB constraint that uses foreign keys, so we can't ensure in the DB that asset paths are unique per version. The alternative is to check whenever an asset is modified.
Also, wrap the update operation to be atomic.
=> Address duplicate assets

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/api/views/serializers.py
Fixes #292
~Draft PR because I'm still fixing the tests.~
This is largely similar to #261, but with some extra additions. @yarikoptic Could you PTAL and tell me if this is what you were looking for?
=> Update asset paths endpoint to include more information

dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
Publish is working in production, so it's almost time to let the general public have at it.
=> Allow any dandiset owners to publish

dandiapi/api/models/version.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_version.py
Use the DOI for the citation URL if it is present.
=> DOI citations

dandiapi/api/migrations/0016_remove_metadata_tables.py
Migration 0016 ran perfectly in development and in staging, but was not
performant enough to run in production.
Update it to use subqueries rather than `.all()`.
This change only affects the `RunPython` step which copies the data, so
it should not affect any existing instances that have already run the
migration.
=> Fix migration 0016_remove_metadata_tables

dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
=> Allow admin users to delete published versions

dandiapi/api/tests/test_upload.py, dandiapi/api/views/upload.py
=> Make /blobs/digest/ support SHA256

dandiapi/api/views/users.py
User search doesn't work in local deployments because it only considers `SocialAccounts` (which local environments don't use). This adds an additional query that searches all `User` objects too; the query is conditionalized so it only runs when the `SocialAccount` search returns no results (otherwise there would be duplicates between the `User` and `SocialAccount` objects).
This also allows the E2E tests to test adding an owner to a dandiset, which will hopefully prevent that feature from breaking again.
=> Fix user search in dev environments

dandiapi/api/views/dandiset.py
#489 allowed regular `User` accounts to be included in searches, but didn't allow them to actually be made owners.
=> Allow adding regular `Users` as dandiset owners

DEVELOPMENT.md, README.md
I forgot this important step on #487
=> Add docs for create_dev_dandiset

dandiapi/api/doi.py, dandiapi/api/tasks.py, dandiapi/api/views/version.py
=> Delete DOI when deleting a version

dandiapi/api/views/users.py
=> Exclude disabled users from search results

dandiapi/settings.py, setup.py
- Update `dandischema` package to latest version
- Update schema version to 0.5.2
Closes #518
=> Update to schema 0.5.2

dandiapi/api/admin.py
This makes the `Dandiset` admin page significantly more useful, imo.
=> Add `Version` inline to `Dandiset` admin page

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
This reverts commit aa29edaffd72c7be3553a198e8f752401b01f336, reversing
changes made to 1c9e41f2a6fc03ed6684c1f2601f20639ad7711d.
=> Revert "Merge pull request #545 from dandi/paginate-asset-paths"

setup.py, tox.ini
This fixes the deploy failures caused by #588. I also went ahead and revert #561 since that issue has been fixed upstream.
=> Pin composed configuration, unpin flake8

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
required by https://github.com/dandi/dandiarchive/pull/977
=> Empty dandiset filter

dandiapi/api/mail.py, dandiapi/api/scheduled_tasks.py, dandiapi/api/tasks.py, dandiapi/api/templates/api/mail/pending_users_message.html, dandiapi/api/templates/api/mail/pending_users_message.txt, dandiapi/api/tests/test_users.py
=> Send daily email listing pending users

dandiapi/api/mail.py, dandiapi/api/scheduled_tasks.py, dandiapi/api/tasks.py
Adds a check to ensure there are actually users with a status of `PENDING` before sending the email.
Also moves a function that I now realize was put in the wrong place.
=> Fix daily pending users email

dandiapi/api/dashboard.py, dandiapi/api/tests/test_dashboard.py
This fixes the table alignment issues on the user dashboard page. https://api-staging.dandiarchive.org/dashboard/users
=> Don't include `AnonymousUser` in the user dashboard

dandiapi/api/tests/test_users.py, dandiapi/api/views/auth.py
=> Fix questionnaire page crash

dandiapi/api/mail.py, dandiapi/api/templates/api/mail/added_message.html, dandiapi/api/templates/api/mail/approved_user_message.html, dandiapi/api/templates/api/mail/new_user_message.html, dandiapi/api/templates/api/mail/pending_users_message.html, dandiapi/api/templates/api/mail/registered_message.html, dandiapi/api/templates/api/mail/rejected_user_message.html, dandiapi/api/templates/api/mail/removed_message.html
=> Stop sending HTML versions of email messages

dandiapi/api/templates/api/root_content.html, dandiapi/api/views/__init__.py, dandiapi/api/views/root.py, dandiapi/urls.py
=> Add content at the root of the API server

web/src/views/DandisetLandingView/DandisetSidebar.vue
Transfer over https://github.com/dandi/dandiarchive/pull/1026.
=> Disable embargo dlp ui

web/src/components/DandisetList.vue
Closes #716. The new UI element is feature flagged so we can merge this without deploying.
=> Add Embargo status chip to dandiset listing page

web/src/components/DLP/OverviewTab.vue
=> Add `mailto` link to contact person icon

dandiapi/api/tests/test_asset.py
I wrote this test while working on a theory for #686, but it passed. It's a perfectly good test so might as well add it.
=> Add a test for asset path filtering

web/src/views/DandisetLandingView/DandisetOwners.vue
=> Allow admins to manage ownership of dandisets they don't own

dandiapi/api/models/asset.py, dandiapi/api/tests/conftest.py, dandiapi/api/tests/test_stats.py
=> Include `EmbargoedAssetBlob` sizes in stats endpoint

dandiapi/api/tests/test_zarr.py, dandiapi/api/views/zarr.py
Fixes #746 
Also break up the monolithic zarr API test into smaller chunks.
=> Add HEAD support to Zarr API

dandiapi/api/models/asset.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_upload.py, dandiapi/api/views/asset.py
Fixes #812
I missed download and checksum calculation.
Last embargo PR, I hope.
=> Embargo download and checksum calculation

doc/design/embargo-full.md, doc/design/embargo-mvp.md
There are two documents here, one for the minimum viable product we are rushing out, and another that describes the additional features that will eventually be required.
There a couple of zarr related TODOs in the MVP because the zarr design doc isn't quite final yet, but that will be patched up soon.
=> Embargo design docs

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml
Renames Heroku deploy actions to specify that they only deploy the backend
=> Update GH Action file names

web/src/components/DLP/MetadataCard.vue, web/src/components/DLP/OverviewTab.vue
Fixes 1st point in https://github.com/dandi/dandi-archive/issues/707
=> Display message on DLP if no funding info is present

dandiapi/api/tests/test_embargo.py, dandiapi/api/views/dandiset.py
=> Make DandisetViewSet return 401/403 when embargoed

web/src/components/DandisetList.vue
=> Show embargo status

web/src/components/DandiFooter.vue, web/test/src/tests/homePage.test.js
=> Update footer link to GitHub

web/src/rest.ts, web/src/views/DandisetLandingView/DandisetActions.vue
=> Add manifest link to DLP

dandiapi/api/copy.py
When testing locally against minio, setting the `CopySourceRange` param to `''` was fine, but it seems like this isn't the case with S3 proper.
I've tested unembargo in staging with a file larger than 64mb, ensuring more than one part, and thus a non-empty `CopySourceRange` param. That succeeded, so I believe this fix will address the issue.
=> Fix inclusion of CopySourceRange param

web/src/components/DLP/OverviewTab.vue
=> Fix `mailto:undefined` error + icon spacing for contact people

web/src/components/AppBar/AppBar.vue
=> Make the logo into a "home" link; remove the "welcome" button

web/package.json, web/src/main.ts, web/src/plugins/asyncComputed.ts, web/src/views/FileBrowserView/FileBrowser.vue, web/yarn.lock
Thought it would make sense to do this before the file browser redesign.
Resolves in part #708
=> Convert `FileBrowser` to TypeScript/Composition API

dandiapi/api/views/zarr.py
=> Add operation_id to zarr explore endpoint

dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
=> Do not publish dandisets with zarrs

web/src/components/Meditor.vue
=> Make meditor category tabs horizontally scrollable, remove unused variable

web/src/components/Meditor.vue, web/src/components/VJsfWrapper.vue
=> Fix meditor scrolling

dandiapi/api/tests/test_zarr.py, dandiapi/api/tests/test_zarr_upload.py, dandiapi/api/views/zarr.py
=> Update asset metadata when zarr is modified

dandiapi/api/tests/test_zarr.py, dandiapi/api/views/zarr.py
=> Do not allow creating zarrs in embargoed dandisets

web/src/views/FileBrowserView/FileBrowser.vue
=> Fix file browser pagination

dandiapi/api/admin.py
=> Add EmbargoedAssetBlob to admin page

dandiapi/api/tests/test_users.py, dandiapi/api/views/auth.py
=> Auto approve users with a .edu email

dandiapi/api/views/auth.py
=> Fix signup questionnaire answers not being saved

dandiapi/api/models/zarr.py, dandiapi/api/tests/test_zarr.py, dandiapi/api/tests/test_zarr_upload.py, dandiapi/api/zarr_checksums.py
=> Import zarr checksum calculation code from dandischema

dandiapi/api/manifests.py, dandiapi/api/models/asset.py, dandiapi/api/models/version.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, setup.py
Depends on https://github.com/dandi/dandischema/pull/121
=> Remove hardcoding of API and web app URLs

web/README.md, web/src/App.vue, web/src/main.ts
=> Don't crash web client when server is down, provide mechanism to display custom error message

web/src/components/DLP/OverviewTab.vue
=> Fix funding information console error

dandiapi/api/views/upload.py
=> Fix race condition on upload validation endpoint

dandiapi/api/checksum.py, dandiapi/api/tasks/__init__.py
This will hopefully help with debugging https://github.com/dandi/dandi-archive/issues/567
=> Add extra logging to checksum task

.github/workflows/frontend-ci.yml
I messed this up when I changed the workflows around in #990 .
=> Fix Vue lint step in CI

web/netlify.toml, web/src/router.ts, web/src/views/HomeView/HomeView.vue, web/src/views/HomeView/StatsBar.vue
=> Use history mode instead of hash mode (remove hash from GUI URL)

doc/design/apex-domain-netlify.md
Closes #727
This should be very straightforward to implement.
=> Create design doc for replacing Redirector with Netlify

web/src/components/AppBar/AppBar.vue
Fixes #934 
@waxlamp A little late because I needed Mike's help on some stuff, but the navbar works responsively and in Firefox now. I just need @mvandenburgh to fix some of the logic that I broke in the mobile menu to make the links work and this will be all set.
Thanks in advance, Mike!
=> Fix responsiveness of v-app-bar

dandiapi/api/tests/test_zarr.py, dandiapi/api/views/zarr.py
Fixes bug introduced in #1000 (not so blessed after all)
=> Replace use of strip with lstrip

redirector/README.md, redirector/netlify.toml
=> Add new netlify redirector

dandiapi/api/tests/test_info.py, dandiapi/api/views/info.py
=> Remove trailing slash in info api url

web/src/views/FileBrowserView/FileBrowser.vue
=> Handle missing location query param

dandiapi/api/tasks/zarr.py, dandiapi/api/views/zarr.py
This should help identify where the ingest_zarr_archive task is getting stuck.
=> Add verbose logging to `ingest_zarr_archive` task

dandiapi/api/tasks/zarr.py
Reverts dandi/dandi-archive#1128
Closes #1129
=> Revert "Add verbose logging to `ingest_zarr_archive` task"

dandiapi/api/management/commands/import_dandisets.py
This will help us test #1126 in staging.
=> Add support for cloning assets to `import_dandisets` script

dandiapi/api/admin.py
=> Fix admin search fields

dandiapi/api/apps.py
- Fixes an unhandled exception in the sampling code
- Modifies the sampling code to reduce traces from 2 very busy endpoints
- Configures sentry to show tracebacks narrowed to our app code by default
=> Improve sentry configuration

DEVELOPMENT.md, setup.py
Memray seems to be a pretty useful tool for memory profiling, so this PR adds the relevant packages to the `dev` and `test` extra requires.
=> Add memray dev deps to setup.py

DEVELOPMENT.md
=> DOC: add DLP abbreviation to initiate Abbreviations in DEVELOPMENT.md

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/serializers.py, web/src/types/index.ts, web/src/views/FileBrowserView/FileBrowser.vue
Adds https://kitware.github.io/itk-vtk-viewer/app/ as a "External service" for .ngff files in the file browser gui.
closes #906
=> Add external viewer for NGFF files

dandiapi/api/mail.py, dandiapi/api/models/zarr.py
I noticed some incorrect type hints while working on the API code. We don't do static type checking for our python code, so this went unnoticed.
=> Fix incorrect type hints

setup.py
=> Remove unused dependency httpx

dandiapi/api/storage.py, setup.py
This is just an upgrade of S3FF with the appropriate changes. v0.1.2 required adding support for content type to multipart uploads.
=> Update s3-file-field dependency

pyproject.toml
=> Fix `target-version` for black

dandiapi/api/views/dandiset.py
=> Make Dandiset sorting account for zarr files

dandiapi/api/admin.py
This is just as a convenience for development.
=> Add social accounts to user admin page

dandiapi/api/mail.py, dandiapi/api/templates/api/mail/approved_user_message.txt, dandiapi/api/templates/api/mail/registered_message.txt, dandiapi/api/templates/api/mail/rejected_user_message.txt, dandiapi/settings.py
=> Improve edge cases around email greetings 

web/src/stores/dandiset.ts
Follow-up from [this conversation](https://github.com/dandi/dandi-archive/pull/1265#discussion_r973302209).
=> Only suppress 4xx errors in pinia action

dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
=> Don't revalidate version metadata on PUT unless it has changed

dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/version/metadata.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py, dandiapi/drf_utils.py
This is a general refactor of some dandiset code, it should:
1) DRY up dandiset creation code
2) Make it a bit more clear who can operate on dandisets
3) Allow the code to easily be used outside of the DRF context
This shouldn't cause any breaking changes.
=> Refactor dandiset create/delete methods

web/src/views/DandisetLandingView/DandisetPublish.vue
=> Fix missing spacing for validation error UI when logged out

dandiapi/api/mail.py
This seems to have been removed erroneously in #1275.
=> Include rejection reason in rejected user email

web/src/components/Meditor/Meditor.vue
=> Disable save button in Meditor if no changes have been made

dandiapi/api/asset_paths.py, setup.py
This makes it easier to view the progress of asset paths version ingestion
=> Add tqdm to asset path version ingestion

dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/management/commands/refresh_metadata.py, dandiapi/api/models/asset.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/services/asset/exceptions.py, dandiapi/api/services/asset/metadata.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
This is a general refactor of asset create/update/delete code. This PR doesn't alter any existing functionality, it just restructures the internal API.
@AlmightyYakob cc'ing you because this slightly touches asset path code
=> Refactor asset create/update/delete

dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_tasks.py
This fixes a bug that was discovered in [this](https://github.com/dandi/dandi-archive/issues/1355) issue.
The previous behavior was to save the asset without also saving any draft versions, resulting in a mismatched `modified` timestamp between the asset and the version.
=> Save draft versions during asset metadata validation

dandiapi/api/models/asset.py, dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/embargo/exceptions.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_unembargo.py, dandiapi/api/views/dandiset.py
This refactors the embargo/unembargo workflow into a service.
=> Add embargo service

web/src/views/FileBrowserView/FileBrowser.vue
this adds a service endpoint to validate ome-zarr objects.
=> add zarr validator service

web/src/views/FileBrowserView/FileBrowser.vue
=> Convert FileBrowser component to <script setup>

web/README.md
[ ] Edit the READMEs for style consistency/grammar/etc
[ ]  Determine and implement a common structure where applicable
=> dandi-archive web app readme edit

dandiapi/api/services/asset/__init__.py
=> Refresh asset object before validating it after creation

dandiapi/api/services/publish/__init__.py
There's a couple places in the publishing service where we iterate over all assets in a Version without using `.iterator()` and unnecessarily allocate extremely large lists. This may cause OOM errors when dandisets with a significant amount of assets are published. This PR adds `.iterator()` where needed to decrease the memory usage of querysets, and removes any list coercions in favor of generator expressions.
The `bulk_create` calls also need to be chunked for the same reason; I'll make a follow up PR for that.
=> Optimize memory use in publish service

dandiapi/api/storage.py
Currently there's no timeout on requests to S3. Occasionally we run into issues where Heroku kills the API request because of the 30s time limit due to a hanging S3 request. The default boto configuration provides no timeout. This adds some upper bounds to the timeouts which should free up resources earlier and give us better error messages when it happens.
=> Add request timeouts for S3 storage

dandiapi/api/services/dandiset/__init__.py, dandiapi/api/tests/test_dandiset.py
This is fixing a regression from #1292.
=> Allow deleting embargoed dandisets

.github/dependabot.yml
=> Fix dependabot ignore types

web/src/stores/dandiset.ts, web/src/views/DandisetLandingView/DandisetLandingView.vue, web/test/src/tests/dandisetLandingPage.test.js
=> Display error message for invalid dandiset URL

web/src/views/CreateDandisetView/CreateDandisetView.vue
=> Use `import type` syntax in CreateDandisetView

web/src/views/CreateDandisetView/CreateDandisetView.vue
The license field was being incorrectly populated by the Create Dandiset Page.
=> Fix license type, improve type annotation

.codespellrc
This will fix failing CI on `master`.
=> codespell: ignore `CHANGELOG.md`

.codespellrc, tox.ini
Add additional ignore patterns and allow passing the files to check
through tox additional arguments.
=> Improve codespell configuration

web/.eslintrc.js, web/src/components/CopyText.vue, web/src/components/DLP/DandisetOwnersDialog.vue, web/src/components/DLP/MetadataCard.vue, web/src/components/DandisetList.vue, web/src/components/DandisetSearchField.vue, web/src/components/DandisetsPage.vue, web/src/components/Meditor/Meditor.vue, web/src/components/Meditor/VJsfWrapper.vue, web/src/components/Meditor/editor.ts, web/src/components/Meditor/localStorage.ts, web/src/components/Meditor/state.ts, web/src/components/Meditor/transactions.ts, web/src/components/Meditor/utils.ts, web/src/components/UserStatusBanner.vue, web/src/rest.ts, web/src/router.ts, web/src/stores/dandiset.ts, web/src/title.ts, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/DandisetLandingView.vue, web/src/views/DandisetLandingView/DandisetMain.vue, web/src/views/DandisetLandingView/DandisetPublish.vue, web/src/views/DandisetLandingView/DandisetSidebar.vue, web/src/views/FileBrowserView/FileBrowser.vue
This will also enable auto-fixing via eslint.
Closes #1144
=> Add eslint rule enforcing the use of `import type`

dandiapi/zarr/admin.py
=> Always force ingestion from zarr admin action

dandiapi/api/tests/test_info.py, dandiapi/api/views/info.py
and supported zarr upload mechanisms etc
Closes #1408
=> Boost minimal client version to be 0.51.0 since needed for fresh dandischema

web/src/components/AppBar/UserMenu.vue
=> Add github username + profile link to UI

web/src/components/Meditor/Meditor.vue
Reverts dandi/dandi-archive#1582
=> Restore metadata editing

dandiapi/analytics/tasks/__init__.py, dandiapi/api/tasks/scheduled.py
Our download counts are roughly up to date. This is the final piece for keeping them updated over time.
=> Add schedule for processing new S3 log files

web/src/components/DandiFooter.vue
fixes #1611 
Applies `app` prop to the footer.
=> Add app prop to footer

web/package.json, web/src/components/Meditor/VJsfWrapper.vue, web/yarn.lock
Some preliminary updates before I investigate integrating AJV with VJSF.
Also fixes #1384 (See comment below)
=> Update VJSF/ajv dependencies, refactor VJSF component to use `<script setup>`

web/src/components/DandiFooter.vue
to mention in-kind amazon similarly to what was done on https://www.dandiarchive.org/ . But also to do proper casing of DANDI and GitHub names
=> Minor tuneups to footer

web/src/views/FileBrowserView/FileBrowser.vue
See https://github.com/flatironinstitute/neurosift/issues/47
Note that the old version will still redirect to the newer URL.
=> adjust neurosift endpoint

dandiapi/api/tasks/scheduled.py
This is to prevent putting too many messages on the queue too quickly. Our current CloudAMQP plan allows us to put 500msg/s on the queue.
=> Set up throttling for validating asset metadata

dandiapi/api/templates/api/mail/approved_user_message.txt, dandiapi/api/templates/api/mail/registered_message.txt
since looks better/easier to remember
=> [DATALAD RUNCMD] Replace youtube URL with the one with @dandiarchive 

dandiapi/api/views/version.py
If multiple concurrent calls to this endpoint occur, it's possible that some data will be clobbered. This is fixed by using select_for_update to lock the version before doing the diff and potential update of metadata.
=> Fix race condition in version PUT endpoint

web/src/views/FileBrowserView/FileBrowser.vue
=> Check that path is an asset before proceeding

dandiapi/api/tests/test_version.py
This was introduced by e1b642c30bd5b2236c52287175c923efbbe04345.
=> Fix a test failure

dandiapi/api/views/serializers.py
=> Generate correct docs for dandisets endpoint

.github/workflows/frontend-ci.yml, e2e/README.md, e2e/src/tests/fileBrowserPage.test.js
Adds simple e2e test for the FileBrowser 
closes #1760
=> Add an e2e test for the FileBrowser

web/package.json, web/yarn.lock
=> Update VJSF to 2.23.3

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tasks/scheduled.py, dandiapi/settings.py, scripts/delete_from_versioned_bucket.py, scripts/papertrail.py
There are some formatting changes that a newer version of ruff catches. Creating as it's own PR because it effects existing files and code.
=> Add format changes from ruff update

setup.py
Mitigation for the CI failures in #1894 until we figure out why the latest release broke CI.
Fixes #1894
=> Temporarily pin DRF

dandiapi/settings.py
Follow on PR adding a missing setting from #1899
=> Add missing setting for DRF throttle class

dandiapi/api/views/asset.py
I noticed this function was making several unnecessary DB calls, and since it's used to check permissions in every endpoint part of the `AssetViewSet`, it's good to decrease the overhead on it as much as possible.
The changes in this PR cut down the query count from 8 to 4 for viewing an embargoed asset.
=> Optimize asset permission check function

web/src/views/DandisetLandingView/DandisetMain.vue
=> Remove File to avoid confusion

dandiapi/api/admin.py
The queryset pulled from `VersionAdmin` when used in this way was causing Django to generate a `SELECT DISTINCT(status, version)` instead of just a `SELECT DISTINCT(status)`. It seems there's about 234 unique `version` values in the database as of now, which was causing 234 `SELECT COUNT(*)` queries being made when `qs.filter(status=status).count()` was called. This was causing this page to crash.
This PR replaces that queryset with one that does the same thing in one query.
=> Fix N query problem with VersionStatusFilter

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, web/src/types/index.ts, web/src/views/DandisetLandingView/ContactDialog.vue, web/src/views/DandisetLandingView/DandisetActions.vue
Closes #723 
Allows a user to send an e-mail populated with a subject 'Regarding  Dandiset `name` `id`' to either the contact person or owner(if logged in)
=> Contact owner

web/package.json, web/src/rest.ts, web/yarn.lock
This package was renamed, see https://github.com/kitware-resonant/resonant-oauth-client/releases/tag/v0.9.0.
=> Upgrade oauth client package

dandiapi/analytics/tasks/__init__.py
This removes a linear scaling set of update queries in favor of `bulk_update`. This should prevent us from hitting our preconfigured time limits for processing S3 log files.
=> Use bulk_update for updating blob download counts

dandiapi/api/views/auth.py
To quickly further lessen the burden on yours truly
=> Auto-allow people with @alleninstitute.org email addresses

web/src/views/DandisetLandingView/ShareDialog.vue
Resolves https://github.com/dandi/dandi-archive/issues/793#event-15607842465
Looked for other scenarios as well throughout the Web UI -- seems this is the only remaining one.
Cc @waxlamp @yarikoptic @kabilar
=> Update shareable link to reflect window.location.origin

setup.py
=> Upgrade `dandischema` version to 0.11.0

web/package.json, web/src/components/Meditor/Meditor.vue, web/src/components/Meditor/VJsfWrapper.vue, web/src/components/Meditor/editor.ts, web/src/components/Meditor/state.ts, web/src/components/Meditor/transactions.ts, web/src/components/Meditor/utils.ts, web/src/stores/dandiset.ts, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/DandisetLandingView.vue, web/src/views/DandisetLandingView/DandisetValidationErrors.vue, web/vite.config.mts, web/yarn.lock
=> Meditor/VJSF Vue 3 migration

dandiapi/api/tests/test_webdav.py, dandiapi/api/views/webdav/__init__.py
Follow on to #2193 
This includes the following fixes that were erroneously not included in the original PR:
* Return 404 if no resource found at path
* Return 404 if trailing slash supplied and asset is found
Closes #2197
=> Update `atpath` endpoint implementation

dandiapi/api/tests/test_webdav.py, dandiapi/api/views/webdav/serializers.py
=> Return full metadata in atpath asset resource

web/src/components/FileBrowser/FileUploadInstructions.vue, web/src/utils/constants.ts
Follow-up to https://github.com/dandi/dandi-docs/pull/190.
=> Fix DANDI Docs links

dandiapi/zarr/tasks/__init__.py
This should completely remove long lived database locks during zarr ingest. This should help prevent deadlocks like the one we saw recently.
=> Compute zarr checksums outside of transactions

web/src/views/DandisetLandingView/ShareDialog.vue
=> Fix Share icon size

web/src/components/CopyText.vue
=> Fix cutoff text on CopyText form

web/src/components/DandisetsPage.vue
=> Display the number of results found in DandisetSearchField

dandiapi/api/views/dandiset.py
The `empty=false` branch of our dandiset list query logic (which is the default) was slow, due to performing an asset count on every dandiset twice (the second one was for the `count` field).
I wasn't able to find a corresponding issue, but if anyone finds one, please link it here.
=> Optimize dandiset list query when excluding empty

dandiapi/api/models/asset.py
=> Remove hardcoded string for pending status

web/README.md, web/src/components/FooterBanner.vue, web/src/views/HomeView/HomeView.vue, web/src/views/HomeView/StatsBar.vue
Adds a banner to the home page that can be used to display an arbitrary message configurable via an environment variable.
=> Conditionally display sticky banner

web/src/utils/constants.ts, web/src/views/CreateDandisetView/CreateDandisetView.vue
fix #1628
cline-assisted.
I wasn't able to test this locally
=> Add warning alert for test dandisets in CreateDandisetView

dandiapi/settings.py
=> Revert OAuth model change

DEVELOPMENT.md, dev/.env.docker-compose, dev/.env.docker-compose-native
Otherwise people who are referred to this doc are unclear what to clone. And if they run DB locally, they run into a conflict, although docker-compose does not complain.
@tompollard please review/try out
=> Give explicit instructions on where to get code and check/set port for django DB

dandiapi/api/admin.py
Adds an admin action to export github usernames
=> enh: add action to export github usernames

dandiapi/search/views/__init__.py, web/src/components/Search/forms/SpeciesForm.vue
=> Fix missing species on search page

e2e/tests/meditor.spec.ts, web/src/views/DandisetLandingView/CiteAsDialog.vue, web/src/views/DandisetLandingView/ContactDialog.vue, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/DandisetOwners.vue, web/src/views/DandisetLandingView/DandisetPublish.vue, web/src/views/DandisetLandingView/DandisetSidebar.vue, web/src/views/DandisetLandingView/DandisetValidationErrors.vue, web/src/views/DandisetLandingView/DownloadDialog.vue, web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
Implement fixes to some of the UI issues mentioned in #2218 and #2220 in the DLP sidebar.
=> DLP Sidebar Design

.gitattributes, .gitignore, DEVELOPMENT.md, dev/.env.docker-compose, dev/.env.docker-compose-native, docker-compose.yml
Some minor improvements downstreamed from the cookiecutter.
=> Miscellaneous improvements

.github/workflows/backend-ci.yml, .github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml, .github/workflows/cli-integration.yml, .github/workflows/frontend-ci.yml, .github/workflows/release.yml
* Removes references to custom secrets in favor of `permissions` block
* Removes cron jobs (unused)
* Remove unused auto-add-issues job
=> Improvements to GitHub Actions

.github/workflows/backend-production-deploy.yml
Reverting this change from #2465 for the same reason as #2490.
https://github.com/dandi/dandi-archive/actions/runs/16977335285
=> Revert change to github token again

dandiapi/api/migrations/0001_initial_v2.py, dandiapi/api/migrations/0002_asset_zarr.py, dandiapi/api/migrations/0009_remove_embargoedassetblob_dandiset_and_more.py, dandiapi/api/migrations/0011_asset_access_metadata.py, dandiapi/api/migrations/0013_remove_assetpath_consistent_slash_and_more.py, dandiapi/api/migrations/0018_auditrecord_admin_auditrecord_description_and_more.py, dandiapi/api/models/asset.py, dandiapi/api/models/asset_paths.py, dandiapi/api/models/audit.py, dandiapi/api/models/version.py, dandiapi/urls.py, dandiapi/zarr/migrations/0001_initial_v2.py, dandiapi/zarr/models.py, uv.lock
This updates the backend to Django 5.2 (the latest stable release).
=> Update to Django 5

DEVELOPMENT.md
See individual commit message for details.
=> Improve documentation for development setup

dandiapi/api/management/commands/extract_metadata.py, dandiapi/api/services/dandiset/__init__.py
Follows https://github.com/dandi/dandi-schema/pull/203
=> Remove deprecated dandischema / Pydantic API usage

dandiapi/api/services/embargo/utils.py, dandiapi/api/tests/test_unembargo.py
Follows #2551. Boto3 is already configured to retry with exponential backoff. Additional application-level retries are unnecessary.
=> Don't retry _delete_zarr_object_tags

dandiapi/api/management/commands/delete_malformed_manifests.py
This command will be used to delete the extra manifest files referenced in https://github.com/dandi/dandi-archive/issues/2534
I've tested this successfully locally and in a test S3 bucket.
=> Add management command to delete extra manifest files
