dandi/dandi-archive

dandiapi/api/tasks.py, dandiapi/api/views/draft_version.py
The publish endpoint was not saving the lock/unlock actions, so drafts
weren't actually being locked while publish was in progress.
=> Fix publish locking

dandiapi/api/models/version.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py
The Version.create_or_find() helper performs the same work as
Version.objects.get_or_create(). Remove it in favor of the native
solution.
=> Remove Version.create_or_find helper

dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/upload.py, dandiapi/api/views/version.py
We have many viewsets with custom actions. Swagger cannot dynamically determine the response shape of these actions, so it must be specified manually using `@swagger_auto_schema`.
=> Swagger returns

dandiapi/api/tests/test_auth.py, dandiapi/api/tests/test_upload.py, dandiapi/api/views/__init__.py, dandiapi/api/views/auth.py, dandiapi/api/views/upload.py, dandiapi/urls.py
These endpoints will allow users to retrieve and refresh an access token once they are already logged in. Users will be able to log in to the swagger page, then use these endpoints to get the access token, which they can then use to authenticate requests from cURLs or the CLI by including an `Authorization: Token {token}` header.
This does not solve the problem of logging in through the web GUI, but it does provide functionality that will be required for CLI usage.
=> Token auth endpoints

dandiapi/api/views/version.py
This ensures that versions are well ordered by publish date, so the UI
can reliably determine what the most recent version was.
=> Sort versions by created date

dandiapi/api/tests/test_users.py, dandiapi/api/views/__init__.py, dandiapi/api/views/serializers.py, dandiapi/api/views/users.py, dandiapi/urls.py
Add an endpoint to search for users. This is used when selecting owners to add in the DandisetOwnersDialog.
=> Add search users endpoint

dandiapi/api/views/dandiset.py
The django-guardian helper used to determine the dandisets that belong
to the current user did not account for admins, which implicitly have
ownership on every dandiset, which meant their My Dandisets page was the
same as Public Dandisets. The check now explicitly excludes admins.
=> Fix My Dandisets not filtering for admins

dandiapi/settings.py
An update to django-composed-configuration removed the
`rest_framework.authentication.TokenAuthentication` auth class from the
configuration, which broke the `setTokenHack` and other token auth
stuff. This workaround needs to be removed later, as it should be
replaced with the new django-oauth-toolkit auth class.
=> Register rest_framework TokenAuthentication

dandiapi/settings.py
Clicking `Login` in production will now take you straight to the GitHub login page. In development and test it will take you to the default `accounts/login/` page, as these environments don't have GitHub logins set up.
=> Make GitHub the only login method in production

dandiapi/api/mail.py, dandiapi/api/models/dandiset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py, scripts/map_ids.py
* Add a new computed property on `Dandiset` models, `most_recent_version`, that finds the most recent version for that dandiset.
* Include `most_recent_version` on the serializer for all views in `DandisetViewSet`. This drastically lowers the number of queries required on the Dandiset Listing page. Previously 17 were required (1 to list dandisets, 8 to fetch all the versions IDs for each dandiset, then 8 more to get the details of the most recent version for each dandiset). Now listing dandisets includes details for the most recent version, so only 1 query is required.
* Use `most_recent_version` when sending ownership change emails to render the name of the dandiset in the email, instead of using the identifier.
* Update a few places where we were calculating the `most_recent_version` …
=> Most recent version

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/serializers.py
Previously, a `MostRecentVersionSerializer` was defined to avoid
including extra information when serializing dandisets. This was more
complicated on the backend and required more special handling on the
frontend, so instead of that, Dandiset views now use a serializer that
looks like this:
```
{
"identifier": ...
"most_recent_version": {
"version": ...
...
"dandiset": {
"identifier": ...
{
{
}
```
The dandiset identifier is now included twice, but now
`most_recent_version` uses the normal `VersionSerializer` so it doesn't
require any special handling in the client.
=> Tweak dandiset serializer

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Fixes #70
[ViewSets](https://www.django-rest-framework.org/api-guide/viewsets/#viewset-actions) handle most of the boilerplate around generate API endpoints. All we have to do to add the DELETE endpoint for assets is to define the appropriate `destroy` method on the existing `AssetViewSet`.
=> Delete asset endpoint

dandiapi/api/views/version.py
`drf-yasg` generates the endpoints on the Swagger page automatically, but sometimes makes incorrect guesses. In this case, it assumes that all POST endpoints require request bodies, which is not the case for the `publish` endpoint.
The solution is to use the `@swagger_auto_schema` decorator to indicate that the `request_body` is `no_body`. I originally tried to this by using `None`, but `no_body` is required to explicitly disable the request body.
Resolves #72
=> Use request_body=no_body on VersionViewSet.publish

dandiapi/api/dandiset_migration.py, dandiapi/api/views/temporary_hack.py, dandiapi/urls.py, scripts/map_ids.py
* Copy the `map_ids.py` script into the `api` package so it can be referenced by the new views
* Add views to run `map_ids` against a specific dandiset or a single dandiset
* Do some really ugly stuff to log `map_ids` progress into a list of strings rather than stdout, then return it from the views.
=> Map ids endpoint

dandiapi/api/dandiset_migration.py
There are some existing dandisets uploaded that have metadata like this:
```
{
"identifier": {
"propertyID": "DANDI",
"value": "000001",
},
...
}
```
This handles that behavior.
=> Handle more complex identifier formats

.gitignore, dandiapi/api/models/version.py, dandiapi/api/tests/fuzzy.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_search.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/search.py, dandiapi/api/views/version.py
Fixes #63
The main change here is an overriding of the `Version.save` method, to include automatically populating the `VersionMetadata.metadata` field with `name` and `identifier`. The format of `identifier` is dependent on [this](https://github.com/dandi/dandi-cli/pull/348) schema change.
=> Automatically populate name and identifier in VersionMetadata on Version save

dandiapi/api/tests/test_search.py, dandiapi/api/views/search.py
As a part of #77, I added a new test, `test_search_metadata`, which tests searching arbitrary version metadata. This seems to fail sporadically, and the search endpoint is intentionally limited anyway, so this PR removes that test.
=> Remove failing test and add comment

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Assets have a `unique_together` constraint on parent version + path, for good reason. It's possible to request a new Asset with the same parent version + path as an existing Asset, which resulted in a 500 error because of the DB throwing an `IntegrityError`.
Catch that `IntegrityError` and throw an HTTP 400.
Fixes #68
=> Throw meaningful duplicate asset error

dandiapi/api/dandiset_migration.py
Fixes #57 
> don't worry about that one (a dict record) since we now migrated to just use dedicated identifier (e.g. "DANDI:000001") but we do need the "DANDI:" one
Remove support for `identifier: {propertyId: "DANDI", value: [identifier]}` and add support for `identifier: "DANDI:[identifier]"`
=> Support DANDI:{identifier} and remove {propertyId: {identifier}}

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
If `identifier` is in the metadata when creating a new dandiset, attempt to use that identifier instead of using the auto-incrementing sequence.
=> Create dandiset with identifier

dandiapi/api/models/validation.py, dandiapi/api/tests/test_upload.py, dandiapi/api/views/upload.py
Fixes #81 
The upload process will now append a UUID to the `object_key`, so all uploads that go through the validation process are guaranteed to not overwrite eachother.
We do not use the `sha256` value because at upload time, it is given by the client. If we allow the client to give all the information that generates the object key, malicious clients could potentially give the `sha256` of a different file, overwriting the blob.
=> Fix object keys

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Fixes #95 
@jwodder This removes `path` from the asset create/update request body and pulls it from the metadata instead. The CLI should simply stop providing `path` in the request body. Can you confirm that this will resolve #96 to your satisfaction?
=> Populate asset path from metadata

dandiapi/api/copy.py, dandiapi/api/models/asset.py, dandiapi/api/models/validation.py, dandiapi/api/tasks.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_copy.py, dandiapi/api/tests/test_upload.py, dandiapi/api/tests/test_validate.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/upload.py
Uploads now are now stored in the bucket at `uploads/{uuid}`, then are copied to `blobs/{sha256}` after validation succeeds.
This requires copying blobs, which is an operation that is not provided by anything we currently have installed, hence `copy.py`. After the copy is completed, the original blob is deleted to avoid keeping duplicate copies of all files.
Multipart copy is used to avoid the 5GB limit on normal copy operations.
@yarikoptic The only API change is that it will no longer be necessary to specify `filename` when calling `POST /uploads/initialize/`. Nothing will break if you continue to provide `filename`, it is simply no longer necessary.
@yarikoptic edit: likely Closes #114
=> Staging area for uploaded blobs

dandiapi/api/migrations/0001_initial.py, dandiapi/api/migrations/0004_update_asset_model.py, dandiapi/api/models/asset.py, dandiapi/api/models/version.py
Importing from the old location is deprecated. A real migration is not necessary, since the old field wraps the new field, with a warning.
=> Use the built-in JSONField from Django 3.1

Procfile, dandiapi/settings.py
This may resolve the SSL_ERRORs happening during upload of large files by keeping the connection to the broker from dying.
=> Enable Celery broker heartbeat

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
`identifier: {uuid}` and `contentUrl: [{download_url}, {blob_url}]` are
also injected into the asset metadata before the response is sent.
Fixes #136
=> Only return asset metadata from GET .../assets/{uuid}

dandiapi/api/views/upload.py
Very small change to improve the swagger doc for upload validate.
=> Use AssetBlobSerializer to describe upload validate

dandiapi/api/models/upload.py
https://github.com/dandi/dandi-cli/pull/479#issuecomment-805056962
S3 wraps ETags in double quotes, so strip them before testing that expected ETag matches actual ETag.
=> Strip double quotes from S3 ETags

dandiapi/api/models/version.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
* Use `bulk_create` to make creating new `Version`s with lots of `Asset`s faster.
* Move DOI creation to a task so it doesn't block the `/publish` request.
=> Optimize publish

doc/design/blob-uuid-1.md
Extract from https://github.com/dandi/dandi-api/issues/146#issuecomment-793114637 with only minimal editing and placing "Check" first without changing any substance for now.  Re [@satra 's comment](https://github.com/dandi/dandi-api/issues/146#issuecomment-794256248): kept numbering as is to not fight markdown renderers which might decide differently while rendering separated numbered lists.
TODOs as I see it
=> Doc design blob UUID & upload process

dandiapi/api/models/upload.py, dandiapi/api/multipart.py, setup.py
Fixes #160
@brianhelba no real review required, I just wanted you to see how I subclassed the `MultipartManager`. Because of how the factory method picks a different storage subclass, I had to override it to use our subclasses. If we want to support this general use case, the path of least resistance for subclassing could be improved.
=> Use DANDI CLI for calculating part sizes

dandiapi/api/models/upload.py
Uploaded blobs will now be stored in `dev/blobs/abc/123/abc123...def456` in the sponsored bucket.
=> Store uploaded blobs in dev/blobs/{uuid}

dandiapi/api/multipart.py
Uploads to the sponsored bucket are not showing up as readable because the default behavior is for the user doing the upload to retain ownership of the object, even though they do not own the bucket.
Add the canned ACL `bucket-owner-full-control` to both upload clients so that they surrender control properly.
=> Surrender uploads to the bucket owner

dandiapi/api/storage.py
Now that the sponsored bucket requires the `bucket-owner-full-control`
ACL, `storage.save()` cannot write to the sponsored bucket. Add that ACL
to storages so that `storage.save()` can be used.
=> Make storages use bucket-owner-full-control ACL

dandiapi/api/models/version.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/dandiset.py
Fixes #172
* Rename `schema_version` to `schemaVersion` in version metadata.
* No longer inject `schemaVersion` to the version metadata whenever the version is saved.
* Inject `schemaVersion` into the version metadata when creating the initial metadata during dandiset creation. The API can also specify a `schemaVersion` in the metadata when calling `POST /dandisets/`, which will take precedence.
@satra @yarikoptic does that change list sound right?
=> No schema version

dandiapi/api/tests/conftest.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
* Only drafts can be published
* Only admins can publish (for now, this will be reverted when publish is ready)
* The `version` fixture now runs tests twice, once with a draft version and once with a published version. The `published_version` and `draft_version` fixtures can be used if you need a specific version.
=> Lock down publish

.github/workflows/cli-integration.yml
So we do not have both "push" and "pull_request" builds appearing in PRs whenever there is a nice feature branch for the PR
=> ENH: run dandi-cli tests for "push"es only to master

dandiapi/api/mail.py, dandiapi/api/models/dandiset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/serializers.py
Begins addressing #188.
Breaks `most_recent_version` into two properties: `most_recent_published_version`, which can be `None`, and `draft_version`, which is never `None`.
This is ready for review, but should not be merged until corresponding changes are made in the client.
=> Rename `most_recent_version` and add `draft_version`

dandiapi/api/models/asset.py, dandiapi/api/models/upload.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_tasks.py, dandiapi/settings.py
Rather than remove the `"dev/"` from all the bucket paths, I opted to replace it with a new setting, `DANDI_DANDISETS_BUCKET_PREFIX`. This moves where the files are stored from code to configuration, so we won't need any more PRs like this one to switch it on/off.
Fixes #214
=> Bucket prefix

dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/version.py
Make it so that published versions cannot be modified through the API. This means no version metadata changes and no asset creation, update, or delete.
=> Immutable published version

dandiapi/api/tests/conftest.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_users.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py, dandiapi/api/views/users.py
This should fix #226 
Currently we use only the information available in the generic Django `User` class to power the API. This means that we have been exposing user's emails for ownership display/management, which is bad.
This PR will use the `login` and `name` JSON fields from the `extra_data` field on the `SocialAccount` model in place of `username` (which is always the user's email) and `first_name`/`last_name`.
Along with dandi/dandiarchive#624, user's emails will no longer be exposed in the client. Only GitHub handles and names will be used.
=> Use social account info for API endpoints

dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
The version detail endpoint
(/dandisets/{dandiset_id}/versions/{version_id}) has been changed to
only return the version metadata. To avoid changing everything in the
frontend to use the metadata schema, a new version action info was
added.
Requires dandi/dandiarchive#628 to keep the UI from breaking.
Requires dandi/dandi-cli#575 to keep the CLI from breaking. I believe a new CLI release will also fix the tests.
=> Version metadata endpoint

scripts/copy_dandiset_dates.py
I forgot the draft version when I set the date only on the dandiset model. The draft version is where the GUI pulls the dates from.
=> Include draft version in copy_dandiset_dates script

scripts/copy_dandiset_dates.py
The default limit in the girder client is 50, which is less than the number of dandisets to update. Bump that limit to 200, which is significantly more than the number of dandisets.
=> Extend girder client limit so all dandisets are updated

dev/django.Dockerfile
There were some missing steps in `dev/django.Dockerfile` which caused `docker-compose build` to fail, as it couldn't fine `versioneer.py` or `setup.cfg`.
=> Update steps in dev/django.Dockerfile

dandiapi/api/tests/test_upload.py
This seems to have broken spontaneously overnight, but I don't see any changes in Django versions, so not sure what would have triggered it.
Regardless, the fix is simple.
=> Fix test_upload_validate_wrong_size

dandiapi/api/mail.py, setup.py
The from address was hardcoded when sending messages, which broke
message sending on the staging instance. It should instead use the
default Django value, which is set appropriately in Teraform.
Also add a print statement to the user registration signal handler so
there is some debug output when a user signs up.
=> Do not override DJANGO_DEFAULT_FROM_EMAIL

dandiapi/api/mail.py, dandiapi/api/tests/test_users.py
It turns out that django-allauth only sends the `social_account_added`
when a new social account is connected to an existing user, not when a
new SocialAccount + User are registered. Instead we need to use the
`user_signed_up` signal and look up all of the social accounts for the
new user.
The change list is intimidating, but most of it is changing arguments from a `sociallogin` which contained a user+socialaccount, to directly specifying `user` and `socialaccount`.
=> Switch from social_account_added to user_signed_up

dandiapi/api/views/dandiset.py
To assist in possible future troubleshooting of dandisets creation with
unexpected ids
=> ENH: log whenever dandiset created with details of the request

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
We have got dandiset 000105 leaping from 000070.  It seems that operation was initiated
from web-ui so in principle the issue is probably not related to this change.  But especially
now that migration is over, I think it would be wise to allow for creation of dandisets
with a given identifier to be allowed only to the superusers, so someone does not
create 999999 dandiset thus making us run of the "dandiset id namespace"
I am not quite sure if my use of `request.user.is_superuser` is kosher but I saw
```
dandiapi/api/views/version.py:        if not request.user.is_superuser:
```
so decided that it should be ok
=> ENH: disallow non-super users creating dandisets with a specified identifier

dandiapi/api/admin.py, dandiapi/api/migrations/0007_validation_status.py, dandiapi/api/models/version.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/serializers.py, dandiapi/api/views/version.py
* Add `status` and `validation_error` columns to `Version` model
* Add task to validate version metadata
* Add property `valid` to `Version` to describe whether or not the version is valid for publish (valid metadata + valid metadata for all assets)
* Require valid version for publish to be enabled
* Add `status` and `validation_error` to version serializers
=> Version metadata validation

dandiapi/api/migrations/0008_version_validation_status.py
I had added changes to migration 0007 in two different commits which
were deployed to staging at different times. Because the current code of
0007 contains some changes that were applied in staging and some that
weren't, it is impossible to apply or unapply that migration. The
solution is to break it apart into two different migrations.
=> Fix migrations

dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py
The validate_version_metadata task was all set up, but was not actually
triggered when version metadata was modified.
=> Actually validate version metadata

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_stats.py
Filter out any assets that do not belong to a version when collecting
total size statistics.
=> Do not report orphaned assets in size stats

dandiapi/api/models/asset.py, dandiapi/api/models/metadata.py, dandiapi/api/models/version.py, dandiapi/api/tasks.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
A minor overhauling of how metadata is preprocessed before validation and publishing. `publishedBy`, `datePublished`, and `doi` all need to be injected into the version metadata before it is validated or published.
I added a mixin `PublishableMetadataMixin` that I had planned to add to both `VersionMetadata` and `AssetMetadata` that would generate the `publishedBy` field. It's possible that we don't actually need it for `AssetMetadata`, in which case I will rip it out and move it to `VersionMetadata` exclusively.
=> Publish metadata

dandiapi/api/mail.py, dandiapi/api/tests/test_users.py
ATM html is sent as text, and text as html
Just received an email which looked odd after html was processed by lynx for my glorious emacs.
Looked into the code and then confirmed in the email that indeed swapped.
Filed https://github.com/dandi/dandi-api/issues/314 as a supplement
edit 1:
since needed a fix in the test, PR became a little more than just a bugfix and introduced my opinionated changes to the email text body formatting and the test.  Do not hesitate to suggest improvements etc.
=> BF: swap method call names for announcement email renditions

dandiapi/api/views/dandiset.py
Server side changes required for https://github.com/dandi/dandiarchive/pull/732. 
As of right now, this PR determines a given dandiset's `modified` value using only the version metadata and not any of the asset metadata (see discussion [here](https://github.com/dandi/dandiarchive/pull/732#issuecomment-859722370)).
=> Add additional sorting options for dandisets

dandiapi/api/models/version.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/serializers.py
Previously VersionDetailSerializer was simply serializing the Version
data, so it was listing a Version as `VALID` even though it contained
assets that were not `VALID`. This made the Publish button in the UI
available even when publish was not permitted.
Add some computed properties `publish_status` and
`publish_validation_error` that check both the Version status and the
status of all Assets in the Version.
Use those fields in the `VersionDetailSerializer`.
=> Fix publish button

dandiapi/settings.py
The `DANDI_ALLOW_LOCALHOST_URLS` setting worked fine in development and test (which is where it is required), but causes build errors in Heroku because it is not defined for production builds.
Add a default `DANDI_ALLOW_LOCALHOST_URLS = False` to the `DandiMixin`
=> Fix allow localhost urls

dandiapi/api/views/dandiset.py
Closes https://github.com/dandi/dandiarchive/issues/425. The user creating a dandiset will be automatically added as a contributor with a role of `dandi:ContactPerson` when the dandiset is initially created. 
I had to hardcode certain assumptions about the schema to accomplish this, since the API server injects the logged-in user's info into the dandiset's metadata upon creation of it, meaning that a future schema change may break this.
=> Automatically add dandiset creator as contact person

dandiapi/api/views/dandiset.py
Make the default `modified` sorting order go from most recently modified -> least recently modified. 
Closes https://github.com/dandi/dandiarchive/issues/758.
=> Fix order of `modified` sort

dandiapi/api/views/dandiset.py
Backend changes needed for https://github.com/dandi/dandiarchive/pull/760.
=> Don't reverse queryset when sorting by "modified"

dandiapi/api/models/asset.py, dandiapi/api/models/metadata.py, dandiapi/api/models/version.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py
* manifestLocation should only have assets.yaml i think
* the published version also does not show proper assetsSummary in the metadata, so possibly something broke there.
* https://github.com/dandi/dandi-api/pull/370/files#r659029609
* @context is missing
=> Metadata fixes

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Previously, attempting to use `HEAD` requests on the
`/assets/{asset_id}/download/` endpoint resulted in an error 405 Method
Not Allowed, which is different from the behavior of the
`/dandisets/.../versions/.../assets/.../download/` endpoint.
Fix the endpoint so that `HEAD` requests also return 302 redirects.
Fixes #380
=> Allow HEAD requests for direct asset download

dandiapi/api/migrations/0012_merge_20210630_1354.py, dandiapi/api/templates/api/mail/added_message.html, dandiapi/api/templates/api/mail/removed_message.html
The linebreaks cause a spurious space to appear in the linked text between the last character and the trailing period.
=> Remove linebreaks from email template <a> elements

.github/workflows/production-deploy.yml
GitHub action to deploy to production automatically whenever a new release is tagged in GitHub per the [staging design doc](https://github.com/dandi/dandi-api/blob/master/doc/design/staging-1.md).
If I'm correct, this is the only "code" / `dandi-api` repo changes that need to occur for staging to be implemented for the backend, and the rest of the changes need to be made in Heroku/Terraform.
@dchiquito no rush on reviewing since we will tackle staging after publish is all squared away as discussed in person yesterday. 
TODO:
=> Add github action for deploying prod on release

dandiapi/api/models/version.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py
This is a workaround to speed up the bulk updating of asset metadata in dandisets with a large number of assets.
The way the code is currently written, each asset metadata update results in an O(N) computation across all the assets, making an update of all asset metadata an O(N^2) operation in total. This workaround drops that to O(N) at the cost of not updating the summary stats.
@AlmightyYakob and @mvandenburgh helped me review this as I wrote it, so I'm formally self-reviewing and merging to master so that it appears on staging; if it behaves well there, I will promote to production so that @satra is able to speed up his process.
attn: @dchiquito
Closes #384.
=> Disable summary stats temporarily

dandiapi/api/models/version.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py
This reverts commit 93faf5ff2942e800bf9093b4a709c7c566ad3b1d, reversing
changes made to da32e0e6c550100a6dd8529aa68484957a710e42.
AFAIK we (@satra and me) know -- all assets metadata were converted and we should resume normal operations.  I do not expect anything to break, so I might even proceed and merge/mint a release (to get it deployed) soonish unless someone stops me
=> Revert "Merge pull request #386 from dandi/workaround-no-summary"

pyproject.toml, tox.ini
This has several advantages over including args inline:
* It resolves a bug where Black's `exclude` option was being overridden and Black was formatting files in the `.tox/` directory.
* All configuration for each tool is centralized in a single location.
* It makes it easier for developers to run tool commands directly, as tools will always pick up consistent options from config files.
=> Provide additional CLI args for Tox tools in config files

setup.py
django-click is required to run manage.py commands, which is a thing
that needs to happen in deployments as well as locally.
Move it from being a dev dependency to a real dependency.
=> Upgrade django-click to a real dependency

requirements.txt
This might at least partially address a problem of incorrect version
being provided by versioneer (https://github.com/dandi/dandi-api/issues/222).
Because staging and deployment have different ways of deployment it is not
even necessary that this working on one would work on another.
More FTR: https://github.com/heroku/heroku-buildpack-python/issues/1222
=> BF: Do not install in devel mode in requirements.txt

requirements.txt, setup.py
See this [Heroku build failure](https://dashboard.heroku.com/apps/dandi-api-staging/activity/builds/e0bbf36c-0a34-47f4-b099-94fc580b49fd) for details.
=> Add `email-validator` as an install-required package

doc/design/scheduled-tasks.md
@satra I think a scheduled recurring job would be easier to work with than cancelling jobs whenever a new modification occurs.
=> Scheduled tasks design doc

doc/design/staging-1.md
We made a few minor changes to our staging plan after the staging design doc was written. This PR updates the design doc to be consistent with how we actually ended up setting up the staging environment.
=> Update staging design doc to be consistent with staging infrastructure

dandiapi/api/manifests.py, dandiapi/api/models/version.py, dandiapi/api/tests/test_version.py
Previously the calculation of the dandiset metadata field `manifestLocation` was needlessly arcane. It was calculated once during publish and injected, and any metadata without a `manifestLocation` was set to the draft `manifestLocation`. 
Now, every time a Version is saved, `manifestLocation` is calculated correctly for the version (be it published or draft).
=> Simplify calculation of manifestLocation

dandiapi/api/models/version.py
The function that calculates `assetsSummary` can plausibly fail due to invalid asset metadata. In that case, `assetsSummary` is technically invalid and nothing was being logged, which made the error very difficult to diagnose.
Log any errors encountered when calculating `assetsSummary`.
Since this was presumably caused by invalid asset metadata, this problem should be mitigated in the future by #417 and associated frontend improvements.
=> Log errors when calculating assetsSummary

dandiapi/api/models/version.py
Turns out that the `assetsSummary` calculation was taking a long time
because each asset metadata was being fetched from the DB separately, so
a Version with 1000 assets meant 1000 SQL queries. This `select_related`
call should roll them up into a single large query, which cuts down on
network traffic.
=> select_related on asset metadata

dandiapi/api/tests/conftest.py
Running `docker-compose run --rm django tox` was resulting in errors when trying to use the download URLs provided by Minio. We had encountered this error earlier for the S3 fixture, but neglected to apply that fix to the minio fixture. This error only applies when running tox in docker.
=> Fix minio URLs for running tox in docker-compose

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
We do not want normal users to be able to delete dandisets that have been published at least once, but we still want admins to have the power if necessary.
* Update old delete endpoint tests to test dandisets with draft versions.
* Add new tests for deleting dandisets with published verisons.
Fixes #288
=> Do not allow deletion of dandisets with published versions

.github/workflows/cli-integration.yml
This seems necessary as https://github.com/dandi/dandi-cli/commit/7cc845d24def7025426f5d17283ec26793ed1f02 does the same thing for the dandi-cli tests.
=> Set DANDI_ALLOW_LOCALHOST_URLS for integration tests

dandiapi/api/multipart.py, setup.py
dandischema has absorbed the functionality that dandi-api needed dandi-cli for, so once dandischema is bumped we can remove the dependency on dandi-cli.
=> Bump dandischema and replace dandi-cli dependency

dandiapi/api/tests/test_asset.py, dandiapi/api/views/__init__.py, dandiapi/api/views/asset.py, dandiapi/urls.py
This adds a `GET /assets/{asset_id}/metadata` endpoint to the API, allowing for querying asset metadata without specifying a dandiset ID and version.
Closes #436.
=> Add top-level API endpoint for asset metadata

dandiapi/api/doi.py, dandiapi/settings.py, setup.py
The default status for new DOIs is "draft". We want to allow django to
make new DOIs with status "findable", but only in production.
=> Add setting for publishing DOIs

dandiapi/api/management/commands/revalidate.py
Add a script to revalidate all the things. It does not actually use `delay(...)`, so the validations will be done immediately in the script thread instead of being put into the task queue.
=> Add revalidation script

dandiapi/api/models/asset.py, dandiapi/api/tasks.py, dandiapi/api/tests/conftest.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
Fixes #459 
* Refactor the code that generated published Assets into code that mutates a draft asset into a published asset.
* Split `AssetFactory` into `DraftAssetFactory` and `PublishedAssetFactory`
* Add a new test for the publish endpoint that publishes a draft version with a draft asset and a published asset, and verifies that those assets are handled correctly.
=> Fix publish

dandiapi/api/views/dandiset.py
There was a path param in the swagger docs that isn't actually part of the endpoint.
=> Remove incorrect param in swagger doc

dandiapi/api/management/commands/migrate_published_version_metadata.py
This script will migrate the metadata of a specific published version. It will show the diff first and request confirmation. It will also trigger the rewrite of the .yaml and .jsonld files.
=> Add script to migrate metadata of published dandisets

dandiapi/api/tests/test_upload.py, dandiapi/api/views/upload.py, tox.ini
See https://github.com/dandi/dandi-api/issues/468 as a motivator for
introducing this change.  In general I really prefer informative error
messages which can help user to immediately resolve the "problem"
without RTFM etc.  Hence I think besides improving documentation
(no information on what algorithms are supported is shown), error
should be improved as well.
2nd commit adds that listing also to operation_description ~~the docstring... can't test locally ATM if works out as expected~~
=> ENH: list supported digest algorithms in 400 error response

dandiapi/api/__init__.py, dandiapi/api/apps.py, dandiapi/api/mail.py, dandiapi/api/signals.py, dandiapi/api/views/auth.py
Fixes #256 
* Add a signal handler that allows an CORS requests from any origin with method `GET`, `HEAD`, or `OPTIONS`.
* Move our other signal handlers into one location, `signals.py`.
=> CORS signal handler

.github/workflows/staging-deploy.yml
Deploys staging with a GitHub Action instead of using Heroku's automatic github deployment.
Auto-deploy will need to be turned off in Heroku right before merging this (Deploy tab -> Deployment method -> Deselect "GitHub").
Closes #404.
=> Deploy to staging with GitHub Action

dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/tests/test_create_dev_dandiset.py
I decided to manually create the test data because the only alternatives I could think of involved dandi-cli, which is a new dependency and is subject to API changes.
If we ever change the structure of anything, the test should catch it.
Fixes #287
=> Add create_dev_dandiset script

dandiapi/api/views/asset.py
This results in 404 errors instead of 500 errors when an object cannot
be found in the DB.
Fixes #486
=> Use get_object_or_404 in views

dandiapi/settings.py, dandiapi/swagger.py
A follow up to https://github.com/dandi/dandi-api/pull/480#discussion_r689903879
More information/references in the DANDISwaggerAutoSchema docstring.
Without such an overload, any oneline docstring is not used as an action
summary but rather as a description, so not visible until that action is
"clicked on" in the swagger interface.
compare 
to
=> ENH(UX): overload @swagger_auto_schema to show one-line docstrings as summary

dandiapi/api/templates/api/mail/registered_message.html
Would assist with reviewing registered users, so could be just clicked on
to review that user github page
=> ENH: make github ID into a hyperlink in html version of the email

tox.ini
By default, if a developer (say, me) has a user-wide flake8 config file in `~/.config/flake8`, then the flake8 command in `tox.ini` will pick it up and merge the settings there with the ones in `tox.ini`, which often doesn't work out too well.  This PR instructs flake8 to only use the configuration in the `tox.ini` file and ignore any user config.
=> Pass `--config=tox.ini` to flake8

dandiapi/api/apps.py, dandiapi/api/checks.py, dandiapi/api/doi.py
Django has a facility to perform system checks, so this check should run whenever any server starts up.
Fixes #503
=> DOI config check

DEVELOPMENT.md, dandiapi/api/management/commands/import_dandisets.py
Closes #516. This management script can be used to copy dandisets from any deployment of dandi-api into the environment it's being run from.
=> Management script to copy dandisets from another api deployment

Procfile, dandiapi/api/manifests.py, dandiapi/api/scheduled_tasks.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, dandiapi/celery.py, docker-compose.override.yml
* Add `scheduled_tasks.py` to house all our scheduled tasks
* Add a scheduled task that writes all draft manifests every day at 1:00 AM
* Use the `-B` option to start celery beat in the worker processes. The caveats to this are documented in commit history and in `Procfile`.
* Set `manifestLocation` to the real manifest location for draft metadata, instead of the workaround we were using while there was no manifest.
Closes #522.
=> Scheduled draft manifests

dandiapi/settings.py, setup.py
Some tasks are too memory intensive for celery, so having a setting is
useful for tuning staging/production without releasing a new version.
Requires https://github.com/dandi/dandi-infrastructure/pull/98
=> Add environment setting for Celery concurrency

doc/design/new-user-questionnaire.md
A design doc describing the new approval-driven user registration workflow.
Link to markdown rendered doc https://github.com/dandi/dandi-api/blob/design/new-user-questionnaire/doc/design/new-user-questionnaire.md
=> New user questionnaire design doc

Procfile
This lets us scale the number of workers without inadvertently firing multiple beat events.
The downside is that we need a separate dyno just to run chron, but such is life.
=> Add separate dyno for celery beat

dandiapi/api/management/commands/import_dandisets.py, dandiapi/api/management/commands/migrate_version_metadata.py, dandiapi/api/scheduled_tasks.py, dandiapi/api/tasks.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py, dandiapi/settings.py
* `validate_asset_metadata` has proven to be consistently very quick, so we can simply do it in band and save the overhead of dispatching a task.
* Instead of revalidating Versions every time they are modified in any way (including adding, updating, removing Assets in the Version), we have a scheduled task that checks for any draft Versions with status `PENDING` and validates them then. This effectively debounces Version validation.
* Since we want to revalidate draft Versions basically any time they are changed, that is also a good time to dispatch the draft manifest task, which means we can do away with the 1:00 AM scheduled job and the associated inefficiencies.
This should also fix https://github.com/dandi/dandi-api/issues/537
=> Optimize celery tasks

dandiapi/api/scheduled_tasks.py
* We were using `draft_version.id` instead of `draft_version['id']` to dispatch the draft manifest writing task
* The scheduled job triggers frequently and most often finds nothing to do, so remove extraneous log messages to reduce log spam.
=> Fix optimize tasks

dandiapi/api/admin.py
Since inlines aren't paginated, inlines would try to load every asset in
a version, which would hit the Heroku timeout when trying to load the
admin page for a version.
Limit admin inlines to 10 entries to avoid this.
#539 it does not fix, there are problematic version with no assets
=> Limit admin inlines to 10 entries

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Adds pagination to the asset paths endpoint. Will unblock https://github.com/dandi/dandiarchive/pull/919.
=> Paginate asset paths endpoint

Procfile, dandiapi/api/tasks.py, docker-compose.override.yml
* SHA256 calculations now go to their own queue, `calculate_sha256`. Every other task still goes to the default queue, `celery`.
* The dev environment still pulls from both queues.
* In production there is one worker that handles checksums only, and one worker that handles every other task + running celery beat. The only tasks that eat up worker time are checksums, so we can now scale that separately without having to worry about scaling the high priority worker.
Fixes #542 
dandi-cli tests will break until https://github.com/dandi/dandi-cli/pull/787
=> Checksum queue

docker-compose.yml
This lets you view the RabbitMQ management console GUI when running RabbitMQ locally in Docker (just like the one in CloudAMQP).
=> Expose port for RabbitMQ management console

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
* Include `schemaKey` in metadata when creating new dandiset
* Run the metadata through the pydantic model to ensure it has all preset fields
Fixes https://github.com/dandi/dandiarchive/issues/931
=> Always add schemakey

dandiapi/api/tests/test_version.py
Some tests assume minio is running at `localhost:9000`, but this is only true when running tox natively. If running it via docker, minio will be running at `minio:9000`. To fix this, I had the tests retrieve the minio url from the `DJANGO_MINIO_STORAGE_ENDPOINT` environment variable.
=> Fix failing tests when running tox with docker

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
This seems to be the standard way to implement this.  With this, sort order can be specified in API requests with the `ordering` query parameter, e.g., `ordering=created` (or `ordering=-created` for reverse order).
Closes #563.
=> Support requesting sorted assets (take 2)

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Manually paginates the asset paths endpoint. Also improves performance by removing the calls to the `AssetSerializer` constructor on every iteration of the asset loop.
=> Paginate asset paths endpoint (take 2)

dandiapi/api/mail.py, dandiapi/api/tests/test_users.py
This visually separates the "need to register" emails from the "there's a new user" emails.
=> Update subject line on review email

dandiapi/api/tests/factories.py, dandiapi/api/tests/test_users.py, dandiapi/api/views/users.py
Previously we used `jane` as a generic name for user search tests. This
worked most of the time, but would break whenever the User factory
happened to generate a use with the name `Jane`.
Switch the generic name to `Odysseus`, which is presumably not in
Fakers name pool.
Take 2: explicitly order the users in the search endpoint.
Also clean up the SocialAccountFactory a bit to tie it more tightly to the base User object.
=> Use odysseus in tests with names

dandiapi/api/templates/api/account/questionnaire_form.html, dandiapi/api/views/auth.py
This is one potential solution to #570.
This adds a check to the `oauth/authorize` endpoint that is called whenever a user logs in. If the user doesn't have a first or last name, they are redirected to a form that they must fill out before being allowed to log in. This would need to be accompanied by a manual operation to revoke all session cookies from users without first or last names.
Closes #570
=> Collect first and last names from users who don't have them

dandiapi/api/tests/conftest.py, dandiapi/api/tests/factories.py, tox.ini
I learned recently that the `factory.post_generation` decorator is usually used to represent many-to-many relationships with Factory Boy, and that `RelatedFactory`/`RelatedFactoryList` is a thing and lets you express one-to-one/one-to-many relationships more naturally. This PR changes the way `UserFactory` handles `UserMetadata` to take advantage of `RelatedFactory` instead.
I've also updated the pytest config settings in `tox.ini` to the ones in the latest cookiecutter. This will eliminate those Django 4 warnings that keep appearing after every test run, which I found made the tests more annoying to read when I was debugging a test failure recently.
=> Cleanup testing

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
This lets the frontend properly display owners' names when an owner does not have an associated `SocialAccount` (which is always true in local dev and E2E browser testing environments).
=> Return names for users with no social account

README.md, docker-compose.override.yml
Adds
- Note about where to find `manage.py` scripts documentation to README
- Instructions for running celery beat to README (which is now required for things to work correctly locally)
- celery beat as a service in `docker-compose.override.yml`
=> Improve README

setup.py
This will make CI pass again. Once https://github.com/jazzband/django-oauth-toolkit/issues/1037 is fixed we can revert this and upgrade to Django 4.
=> Temporarily pin django~=3.2

dandiapi/api/models/dandiset.py
I noticed some test flake on https://github.com/dandi/dandi-api/actions/runs/1559780662/attempts/1
(That run was from my PR that pinned the Django version, which did not touch any endpoints. Note the second attempt of that run succeeds.)
I ran the test in question locally (`test_dandiset_rest_add_owner`) 1000 times and got 335 failures, all of which failed because the ordering was off. 
In other words the test expected 
`[{'username': 'user1'}, {'username': 'user2'}]` 
but roughly a third of the time the API server would return 
`[{'username': 'user2'}, {'username': 'user1'}]`
This suggests the order of the list returned by the Django guardian `get_users_with_perms` function is not deterministic. This PR explicilty orders the list before returning it. I ran the problematic test with these …
=> Fix flaky test

dandiapi/api/templates/dashboard/user_approval.html
I believe @satra mentioned this before.
The user approval admin page is difficult to read when using the "dark mode" browser setting. This is because the CSS framework we're using for this view doesn't support this mode (yet?). To fix this, I added a CSS media query to darken the background color when the user is in dark mode. The page remains the same for users not using dark mode.
Current page in dark mode:
New page in dark mode:
=> Fix user approval page styling when browser is in dark mode

dandiapi/api/dashboard.py, dandiapi/api/filters.py, dandiapi/api/templates/dashboard/base.html, dandiapi/api/templates/dashboard/index.html, dandiapi/api/templates/dashboard/user_approval.html, dandiapi/api/templates/dashboard/users.html, dandiapi/api/tests/test_dashboard.py, dandiapi/urls.py
We already have a list of *approved* users in the dashboard, so to address #575 I moved that list to a separate dashboard page and added a filter for user `status`. I also added a new `DashboardMixin` that can be subclassed by all dashboard pages to ensure only admins are allowed to view them. I think this is a cleaner approach to authentication over raising an exception in `get_context_data` now that we have multiple dashboard views.
Closes #575.
=> User admin dashboard page

doc/design/zarr-support-3.md
Everything required for zarr, except publishing.
I've already started implementing this as it is written with no issues.
Outstanding requests from the last PR:
* calling the `dandiarchive/zarr/...` directory in S3 something else, to reflect that we can store any kind of folder structure in it. I think that we are building this for zarr files, and we are only planning on putting zarr files in it. If there are other formats that we want to explicitly include, we can always create new directories for those formats.
* Keeping `.checksum` files in `dandiarchive/zarr/ZARR_ID.checksum/...` instead of `dandiarchive/zarr_checksums/ZARR_ID/`. I like having two directories for two kinds of files, rather than having `dandiarchive/zarr` contain pairs of directories, but I don't feel that strongly.
=> 3rd draft of zarr design doc

dandiapi/api/views/zarr.py
The current code allows non-approved users to upload zarr files. I will make a follow up PR for #638 that makes these permission classes the default so this can't happen again.
=> Fix `ZarrViewSet` permission class

dandiapi/api/tests/test_zarr_checksums.py, dandiapi/api/zarr_checksums.py, doc/design/zarr-support-3.md
* Swap the order of checksum object keys: `{"md5":"...","path":"..."}`
* Swap the order of checksum listing object keys: `{"directories":...,"files":...}`
Everything should now be alphabetical.
Fixes #631
=> Order .checksum JSON object keys alphabetically

dandiapi/api/models/zarr.py, dandiapi/api/tests/test_zarr_upload.py
* Specify ACL=`bucket-owner-full-control`. I'm not sure why it is the way it is, but AWS requires that the client declare who will be the owner of the uploaded object. The staging (and also production) buckets have a rule that only requests with ACL=`bucket-owner-full-control` are permitted, which effectively makes it so that uploaded objects are always owned by the bucket owner. The downside of AWS doing it this way is that clients need to explicitly do this or their requests are not permitted, which is awful UX.
* Fix a bug where minio presigned zarr upload urls pointed to `http://minio:9000/...`, the name of the `minio` docker container.
=> Fix zarr s3 upload

dandiapi/api/views/__init__.py, dandiapi/api/views/zarr.py, dandiapi/urls.py
I've tested this code with the endpoint, it authenticates and can read a zarr file:
```
API_KEY = '...an API key...'
AUTH_HEADERS = {'Authorization': f'token {API_KEY}'}
zarr_archive = zarr.open(
'http://localhost:8000/api/zarr/61b2ff83-314f-4f80-a92d-7b08885af059/explore/',
storage_options={'headers': AUTH_HEADERS},
)
print(zarr_archive[:])
```
No tests yet for quick iteration
=> Add zarr browse endpoint

dandiapi/api/tests/test_users.py, dandiapi/api/views/users.py
When the input to user search doesn't validate, it leaks a 400 error through to the browser (specifically, in the user search form that appears in the "manage ownership" dialog) but doesn't break user functionality in any way. In fact, the user typing bad input into this field *shouldn't* be considered an error, and should instead just return no results.
Closes https://github.com/dandi/dandiarchive/issues/708.
Asking @dchiquito for a direct review, and @mvandenburgh to verify that this doesn't negatively impact frontend behavior.
=> Don't leak spurious 400 error to client

dandiapi/api/admin.py
Currently, `Version` detail admin pages such as https://api.dandiarchive.org/admin/api/version/636/change/ fail to load because they are querying the entire `Asset.versions` through table for every asset in order to display them in an inline. 
The asset inline's use is limited by the fact that it only shows a small subset of assets, so I just removed it.
Fixes #539.
=> Remove `AssetInline` to improve performance

dandiapi/api/manifests.py, dandiapi/api/models/asset.py, dandiapi/api/models/zarr.py, dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
* Fixes #676 
* Fixes #677 
* Include a full S3 URL as the second `contentUrl` metadata field for zarr archives.
Triggered by discussion on https://github.com/dandi/dandi-cli/issues/852#issuecomment-1007758461
=> Fix zarr metadata

dandiapi/api/views/asset.py, dandiapi/api/views/version.py
Turns out `NestedViewSetMixin` already implemented `get_queryset`, so when I overwrote it I also overwrote the code that filters versions/assets. This restores it.
=> Correctly invoke super().get_queryset()

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py
Resolves #645 
Add an `...?embargo=true` query parameter to the create dandiset endpoint. If present, the dandiset will be embargoed and the `access` metadata field set accordingly.
=> Embargo create dandiset

.github/workflows/backend-ci.yml, .github/workflows/cli-integration.yml, .github/workflows/production-deploy.yml, .github/workflows/staging-deploy.yml
Fixes some lingering GH Actions issues that were revealed after merging #675.
- Don't run Heroku deployment actions for frontend-only changes
- Fix `paths-ignore` formatting in some workflow files
=> Fix GH Actions config files

dandiapi/api/views/asset.py, dandiapi/api/views/version.py
The query to filter versions/assets against visible Dandisets involves a
JOIN, which causes duplicate assets to be included in the queryset when
the same asset belongs to multiple versions in the same Dandiset.
The solution is to make the queryset distinct.
Fixes #686
=> Make ViewSet querysets distinct

web/src/components/DLP/OverviewTab.vue
If `name` isn't present on an `AssetsSummary` item, fall back to the identifier instead of rendering JSON.
Fixes #695
=> Fall back to identifier for AssetsSummary DLP card

dandiapi/api/tests/test_zarr.py, dandiapi/api/views/zarr.py
* Add a `checksum` field to the zarr directory listing endpoint containing the checksum for the directory
* Add a `checksums` field to the zarr directory listing endpoint containing the checksums for all subfiles and subdirectories of the directory
Addresses API deficiencies brought up in #674
=> Add checksum fields to zarr explore API

web/src/components/DLP/OverviewTab.vue
=> Collapse assets summary card into rows on small screens

web/src/components/DLP/OverviewTab.vue
Fixes 2nd point in #707.
@satra what fields from associated projects should be displayed on the DLP? So far it displays just the `name` and `identifier`. 
To provide context since it's been some time since we've discussed DLP - this is only for the general "overview" display, in the future we will have separate tabs for the metadata, so we'll have a view like [this](https://www.figma.com/file/rBobiAvSLCsJmyYUYmU1OX/DLP?node-id=504%3A36884) for associated projects where we can display more detailed info with more/all of the fields.
=> Add Associated Projects card to DLP

web/src/components/DandisetsPage.vue, web/test/src/tests/dandisetsPage.test.js
This PR also hides the filtering menu when on the My Dandisets page. A person could become confused as to why changing those options doesn't change what is shown in that view, and could become further confused as to why changes happen *later* when they return to the public dandisets view (if the time between making the change and seeing the change is long enough for the state change to be forgotten by the user).
Closes #696.
=> Do not filter out empty and draft dandisets in the "My Dandisets" view

dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_embargo.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/version.py
* Throw 401 whenever a client attempts to do anything to an embargoed version/asset without authenticating.
* Throw 403 whenever a client attempts to do anything to an embargoed version/asset without owning the dandiset.
* Add a single test for all embargo permissions. This should cover all negative testing for embargo permissions.
Fixes #669
=> Embargo permissions

web/README.md
The README was out of date, so this PR fixes it. Incidentally, this will serve as a test for the new frontend deployment strategy introduced in #841.
=> Update web/README.md with correct information

web/src/views/CreateDandisetView/CreateDandisetView.vue, web/src/views/DandisetLandingView/DandisetSidebar.vue
All of the embargo UI has been merged and is currently sitting behind feature flags - this PR removes those feature flags. We do not want to merge this until we are ready to release embargo to production, so I'll mark this as draft for now.
Closes #833 (visual indicator for embargoed in dandisets list)
=> Enable embargo UI

dandiapi/api/views/zarr.py
This is to help get a better grasp of how much time each phase of the zarr upload process takes.
=> Add logging to zarr uploads

dandiapi/api/management/commands/revalidate.py
Only revalidate invalid assets/versions when running the `revalidate` command.
Add `--revalidate-all` flag to disable that behavior.
Add `--dry-run` flag to only log the number of assets/versions being revalidated without revalidating.
=> Only revalidate invalids in revalidate command

.github/workflows/frontend-production-deploy.yml
Netlify-cli deploys are currently [failing](https://github.com/dandi/dandi-archive/actions/runs/1761849006). I think this is happening because we're not specifying `NETLIFY_AUTH_TOKEN` as an environment variable for one of the steps. https://answers.netlify.com/t/netlify-deploy-texthttperror-unauthorized/28591/4
I don't believe we ever tested deploying after adding [this line](https://github.com/dandi/dandi-archive/blob/master/.github/workflows/frontend-production-deploy.yml#L42), I'm guessing that is what introduced this error.
=> Add `NETLIFY_AUTH_TOKEN` var to netlify env var step

tox.ini
Black was recently released as [non-beta](https://github.com/psf/black/releases/tag/22.1.0). This change pins black to at
least use this version (exclude previous beta versions)
=> Specify minimum black version

dandiapi/api/tests/test_zarr.py
Currently, these tests fails if running in docker, as the endpoint is `minio:9000` not `localhost:9000`. Plus, we probably shouldn't be hardcoding that anyway.
=> Sub hardcoded value with MINIO_STORAGE_ENDPOINT setting

dandiapi/api/admin.py
`github_username` is a display only property that we extract from the
user metadata, so it cannot be searched. Whenever searches tried to they
encountered an error.
fixes #874
=> Remove github_username from admin search

dandiapi/api/tasks.py, dandiapi/api/tests/test_unembargo.py
Closes #875 
@dchiquito I didn't add `validate_asset_metadata` into the tests as no asset metadata is touched during unembargo. If you think that should be added lmk, but it will clutter up the tests even more. Also, please make sure I haven't missed anything regarding asset/version/dandiset validation.
=> Check draft version metadata after unembargo

dev/delete_from_versioned_bucket.py
This speeds up the versioned bucket delete script pretty substantially.
AWS doesn't have a good way to delete a lot of stuff from a versioned bucket, their [official recommendation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html) is to just write your own script.
=> Add threads to delete_from_versioned_bucket

web/src/components/AppBar/AppBar.vue, web/src/utils/constants.ts
Finishes closing #697.
Note that this addition makes the navbar too crowded. However, once #890 is merged, this should be resolved.
=> Add dandihub link to navbar

dandiapi/api/views/dandiset.py, web/src/components/DandisetsPage.vue
This essentially keeps embargoed dandisets out of the Public Dandisets
view, showing them in the My Dandisets view of their owners, and admins.
Closes #834.
EDIT: The deploy preview (https://deploy-preview-889--gui-staging-dandiarchive-org.netlify.app/#/dandiset) doesn't work properly because this PR involves a backend change that isn't deployed to staging yet. But it works locally, so if reviewers want to build locally to see it in action and give me feedback on the code changes, we can deploy this to staging to make sure it works there.
=> Only show embargoed dandisets in My Dandisets view

dandiapi/api/tests/test_users.py, dandiapi/api/views/auth.py
We have a lot of users in the system who signed up before the user questionnaire was a thing. All such users were "grandfathered in" and simply approved via a database migration. Currently, If one of these users fills out the first/last name form, the questionnaire code will send emails to them + the admins; this occurs because they have no answers to the signup questionnaire stored, and because of that the system thinks they are new users.
This PR fixes this by checking that the user is actually new (i.e. they have a `status` of `PENDING`) before sending any emails.
=> Don't send emails when existing users fill out the name form

web/src/rest.ts, web/src/views/DandisetLandingView/DandisetPublish.vue, web/src/views/DandisetLandingView/DandisetSidebar.vue, web/src/views/DandisetLandingView/DandisetUnembargo.vue
This removes the "feature flag" that was preventing the unembargo ui from rendering. I've also added additional logic to display an appropriate message when a dandiset is in the process of being unembargoed.
=> Turn on unembargo UI

web/src/components/Meditor.vue
This slightly improves the look of the meditor by condensing the sizes of the form inputs.
Before / After:
=> Add `dense` prop to meditor form elements

web/src/components/AppBar/AppBar.vue
Closes #933
This is just a stopgap measure to make sure the behavior of the DANDI logo is consistent across both chrome and firefox; there's an underlying issue with the styling that causes this issue and others that I have captured in #934.
=> Make DANDI svg icon a fixed size

dandiapi/api/admin.py, dandiapi/api/management/commands/ingest_dandiset_zarrs.py, dandiapi/api/management/commands/ingest_zarr_archive.py, dandiapi/api/tasks/zarr.py, dandiapi/api/tests/test_ingest_zarr_archive.py, dandiapi/settings.py
This is a follow up to #914, which adds a method for dispatching ingestion for all zarrs within a given dandiset.
=> Add Dandiset Zarr Ingestion Script

dandiapi/api/views/asset.py
Closes #917
I'm not sure why this ever worked in the past but apparently using `JsonResponse` instead of just `Response` was the issue.
=> Fix DRF UI for Asset endpoints

dandiapi/api/tasks/zarr.py, dandiapi/api/tests/test_ingest_zarr_archive.py
Previously, related assets weren't updated upon zarr ingestion, leaving the metadata invalid. This change saves all assets related to a zarr upon ingestion.
=> Save related assets after zarr archive ingest

.github/workflows/backend-ci.yml, .github/workflows/frontend-ci.yml, docker-compose.yml
Some of the recent backend CI runs have been [failing](https://github.com/dandi/dandi-archive/runs/5454211381?check_suite_focus=true), and it seems to be tied to the latest `bitnami/minio` container image. I'm not sure the underlying cause, but pinning the version seems to fix the issue.
=> Pin minio version

dandiapi/api/copy.py, dandiapi/api/mail.py, dandiapi/api/models/asset.py, dandiapi/api/multipart.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tests/conftest.py, dandiapi/api/tests/test_ingest_zarr_archive.py, dandiapi/api/tests/test_users.py, dandiapi/api/views/upload.py, dandiapi/api/zarr_checksums.py
Following up on the python version change in #958 - apparently collection types from the `typing` module are deprecated as of Python 3.9 (see [PEP-585](https://peps.python.org/pep-0585/)).
While we don't do any python type checking currently, I think it's still good to move away from using deprecated types.
=> Use standard collection types instead of deprecated ones from `typing`

web/src/components/Meditor/Meditor.vue, web/src/components/Meditor/state.ts, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/DandisetLandingView.vue
Fixes #915 
This basically just moves the `Meditor` to a higher level in the component tree. Before, the tree looked like this
```
<App>
<router-view>
<DandisetLandingView>
<DandisetSidebar>
<DandisetActions>
<Meditor />
</DandisetActions>
</DandisetSidebar>
</DandisetLandingView>
</router-view>
</App>
```
Now, it looks like this
```
<App>
<router-view>
<DandisetLandingView>
<Meditor />
</DandisetLandingView>
</router-view>
</App>
```
=> Prevent responsive breakpoints from closing meditor

dandiapi/settings.py, setup.py
The `STATICFILES_STORAGE` bug has been fixed upstream in `django-composed-configuration`, so this PR bumps it to the latest version and removes the workaround.
=> Bump `django-composed-configuration` and remove STATICFILES_STORAGE workaround

Procfile, dandiapi/api/tasks/__init__.py
The `write_manifest_files` has proven to be far from instantaneous, which means it's time for it to have it's own queue and worker.
Add a new queue `write_manifest_files` and a new worker `manifest-worker` which only has a single thread to avoid running out of memory.
=> Add manifest queue+worker

.autorc, .github/workflows/release.yml
Closes #968 
Summary of what this gets us -
- `auto` handles creating releases for us. To cut a release, simply tag a PR with the `release` label. 
- I've included the `conventional-commits` auto plugin, which lets us use the [conventional commits](https://intuit.github.io/auto/docs/generated/conventional-commits) format in commits to tell `auto` whether this is a MAJOR, MINOR, or PATCH release. Then, on the next release `auto` will bump the version number accordingly. 
- `auto` defaults to a PATCH release if no "conventional commits" are in the PR.
- For every release, `auto` will attach the `released` label to any issues that were closed by a PR in that release. 
- This functionality provided by the [`released`](https://intuit.github.io/auto/docs/generated/released) plugin.
=> Use `intuit/auto` to manage releases

.github/workflows/release.yml
The default GITHUB_TOKEN doesn't have permission to push to `master`. See https://intuit.github.io/auto/docs/build-platforms/github-actions#running-with-branch-protection
=> Use custom github token for auto release workflow

docker-compose.override.yml
I added the `manifest-worker` to the `Procfile` Heroku uses in
staging/production, but I forgot to add it to the development
configuration.
=> Add manifest-worker to Celery in dev environment

dandiapi/settings.py
[django-allauth introduced a breaking change in a recent release](https://github.com/pennersr/django-allauth/blob/HEAD/ChangeLog.rst#backwards-incompatible-changes-2) that disallows signing into a 3rd party oauth service via a GET request. 
Apparently there are some security issues that come with doing this - https://github.com/pennersr/django-allauth/blob/HEAD/ChangeLog.rst#security-notice, which we probably want to think about @waxlamp @dchiquito @AlmightyYakob . For now though, I'm just going to merge this because we've been doing it this way up to this point anyways, and new user signup is currently in a broken state without it.
Closes #996
=> Allow github login with GET request

dandiapi/api/models/zarr.py, dandiapi/api/tasks/zarr.py, dandiapi/api/tests/test_ingest_zarr_archive.py, dandiapi/api/tests/test_zarr.py, dandiapi/api/tests/test_zarr_checksums.py, dandiapi/api/views/zarr.py, dandiapi/api/zarr_checksums.py, setup.py
https://github.com/dandi/dandischema/pull/120 made some changes to the zarr API:
* Add `size` of files/directories to the serialization
* Only record the name of the file/directory in the .checksum file instead of the entire path relative to the zarr root.
* Add suffix `-{file_count}--{file_size}` to directory digests
* ZarrChecksum.md5 -> ZarrChecksum.digest, since directories are no longer technically just an MD5
* ZarrChecksum.path -> ZarrChecksum.name, since only the name is stored rather than the whole path.
A depressingly large number of changes are required to enact this change.
Fixes #925
=> Bump dandischema to 0.6.0

dandiapi/api/models/zarr.py, dandiapi/api/tests/test_zarr.py, dandiapi/api/zarr_checksums.py
Currently, if the `.checksum` file is malformed, any API request that
requires the checksum (like `GET /zarr/` or `GET /zarr/{zarr_id}/`)
throws an error 500 because of the validation error. That should be
handled gracefully and `None` returned instead.
Should fix #1004
=> Handle validation errors when fetching zarr checksums

Procfile, dandiapi/api/tasks/zarr.py, docker-compose.override.yml
Currently zarr ingestion runs on the main task queue, which blocks other
shorter tasks from running. Instead, have a separate
`ingest_zarr_archive` queue which is consumed by the existing
`checksum-worker`.
Having a separate worker for blob checksums and zarr checksums seems
like overkill to me, since we will almost never have a spike in both at
the same time, and even if we did, the solution is to scale the number
of `checksum-worker`s even higher.
=> Make checksum_worker responsible for zarr ingest

web/src/components/DandisetSearchField.vue
Closes #936.
This PR changes the search bar styling to use a percentage-based width instead of viewport-size based width, which prevents it from extending offscreen on the homepage.
=> Fix search bar overflowing offscreen

dandiapi/api/management/commands/ingest_dandiset_zarrs.py, dandiapi/api/management/commands/ingest_zarr_archive.py, dandiapi/api/tasks/zarr.py, dandiapi/api/tests/test_ingest_zarr_archive.py
Addresses underlying cause of #1004.
@dchiquito Right now, the management command defaults to `force=False`. I'd think most of the time we're using the management command, we'd want to use `force=True`. Do you think we should default `force=True` in the management command? I'm leaning towards yes.
I'm also wondering how we can improve the process of checksum updates. That is, if there is ever a need again to update the checksum format, it'd be good to have some automated process around this, rather than someone needing to manually run a management command. I get the feeling that any automated solution would be overly costly in the average case of not needing to update. @dchiquito any thoughts?
=> Add force argument in `ingest_zarr_archive`

doc/design/apex-domain-netlify.md, doc/design/deployment-1.md
A brief description of our desired deployment process.
I also pre-emptively ripped out the bits describing the JSON file netlify caching mechanism from the domain shuffle design doc. That document is currently under revision, in part because of the new deployment process.
Fixes #1023
=> Deployment design doc

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml
This is a temporary fix to address a recent [Heroku Incident](https://status.heroku.com/incidents/2413), which resulted in Heroku disabled Heroku Github integration for all Heroku applications. This requires us to temporarily add back a Heroku CLI based deployment mechanism, until Github integration is restored.
=> Fix disabled Heroku Github integration for staging and production deployment

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/api/views/common.py, dandiapi/api/views/serializers.py
Closes #1002.
Note that Postgres doesn't support querying with globs, but it does support querying with a regex. So, the approach I've taken to support globbing here is to convert the glob pattern to a regex pattern and then use that in the query. Python has a built-in function (`fnmatch.translate`) that converts a glob expression to a regex, but the regex syntax it uses is incompatible with Postgres's regex syntax. I found [this 81-line library](https://github.com/Salamek/glob2regex) that does work with Postgres, so I've used that here.
=> Add support for glob/regex filtering on `NestedAsset` list endpoint

dandiapi/api/views/asset.py
This addresses the unnecessarily slow behavior that's partially to blame for this issue: https://github.com/dandi/dandi-api-webshots-tools/issues/14.
Zarr and embargoed asset blobs weren't being selected along with the asset itself for the paths queryset. This resulted in sequential database calls for each asset, drastically increasing request time.
=> Select all underlying asset storage fields in asset paths endpoint

dandiapi/api/tests/test_info.py, dandiapi/api/views/info.py, dev/.env.docker-compose, dev/.env.docker-compose-native
Closes #1044
The test is pretty barebones but will ensure tests fail if the endpoint structure is modified.
This also fixes a typo in the `DJANGO_DANDI_JUPYTERHUB_URL` env var in `dev/.env.docker-compose` and `dev/.env.docker-compose-native`.
=> Fix incorrect fields in info endpoint

dandiapi/api/tests/test_info.py, dandiapi/api/views/info.py
Closes #1048
Fixes accidental breaking change introduced by #1018
=> Include `api/` suffix in info endpoint api url

web/netlify.toml
Deploy previews are currently failing because their environment variables are not being set properly. https://app.netlify.com/sites/gui-staging-dandiarchive-org/deploys/6260642d8016f900092a15b1
I've created a seperate entry in `netlify.toml` for deploy previews like they have [in the docs](https://docs.netlify.com/configure-builds/file-based-configuration/)
=> Add configuration for deploy previews to `netlify.toml`

dandiapi/api/dashboard.py, dandiapi/api/mail.py, dandiapi/api/management/commands/migrate_published_version_metadata.py, dandiapi/api/models/dandiset.py, dandiapi/api/models/version.py, dandiapi/api/models/zarr.py, dandiapi/api/tasks/zarr.py, dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/version.py, dandiapi/api/views/zarr.py, dandiapi/api/zarr_checksums.py
I noticed a bunch of code that did things in a slightly incorrect and/or outdated way, this PR fixes them -
1) Updates any use of `.filter(~Q(...))` to `.exclude(...)`. `exclude` behaves the same and is the "correct" way to do this sort of query in Django
2) Update DRF viewsets to use `rest_framework.generics.get_object_or_404` instead of `django.shortcuts.get_object_or_404`.
- DRF's version of the function wraps the vanilla Django one and adds some DRF specific validation/error handling https://stackoverflow.com/questions/68001954/difference-between-django-shortcuts-and-rest-framework-generics
3) Replace instances of `typing.Union` and `typing.Optional` with new union type syntax
Technically, 3) isn't necessarily incorrect (from what I understand, `typing.Optional` and `typing.Union` are …
=> Misc. Django/Python improvements

.github/workflows/auto-add-issues.yml
See [the new action](https://github.com/marketplace/actions/add-to-github-projects-beta) for doing this.
=> Add actions workflow to auto-add issues to beta project board

doc/design/garbage-collection-1.md
A design doc for garbage collection policies.
Fixes #523 
Fixes #177
=> Add garbage collection design doc

setup.py
The upgrade to 2.0.0 caused the check-migrations test to fail since one of the breaking changes was to change the DB schema. I'm pinning this to 1.x now to prevent breakage in production, but this opens up two issues:
1. If we're pinning this to major versions, we should pin all our dependencies to major versions as well.
2. If we do *that*, then we need to discuss a procedure for keeping up on major version changes so that we can do the work of upgrading when warranted.
Thoughts on the above welcome.
=> Pin django-oauth-toolkit to 1.x

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py
If is completed, Closes #1076 
- first commit is a basic RF, worth adopting if the rest not
- follow up commit implements tentative solution
- last commit provides an attempt at establishing a test but I am not sure how to augment draft asset factory so it would allow for assetblob **or** zarrfile
TODOs
=> Add *ZarrArchive sizes into total_size

DEVELOPMENT.md, web/README.md
From my experience while trying to make it running locally
on my Debian OS laptop
Minimal changes. If anyone wants to expand -- please suggest the diffs.
=> Extend docs with information about devel env

dandiapi/api/views/users.py
Underlying issue is somewhere in the logic/instructions so that locally created
user lacks .metadata somehow, although it seems to be available within /admin
interface among Users table for that user.  So must be some glue missing etc.
With this workaround it should still work ok, but would avoid crashing
and due to INCOMPLETE I would expect that user lacking any super powers
otherwise granted
Note: pycharm checker highlights `.metadata` since it is not defined in `User` class at all.  Is it indeed just ducktyped into it?
Workaround for https://github.com/dandi/dandi-archive/issues/1085
=> BF(workaround): to avoid crash for user lacking metadata - return INCOMPLETE

dandiapi/api/views/zarr.py
Unfortunately it is no a complete fix, since for 400 there could be 2
possible responses, but only one is documented.  I did not find a way to
document both as possible valid choices, but may be it should be a different
from 400 for upload_in_progress anyways?
Also for 204 -- not sure what was motivation for using that reponse
instead of 200 with some message such as "Dispatched ingestion" to inform user
that all is good etc.  But probably such discussion is worth another issue/PR
=> BF DOC(incomplete): /zarr/.../ingest has 204 not 200 response

web/src/views/DandisetLandingView/DandisetPublish.vue
opening Meditor when clinging "FIX ISSUES".
fixes #950
@yarikoptic - see if this is what you wanted. I used `openMeditor` instead of `meditorLink`. I'm pretty sure there was soe idea behind it, so don't know if I should remove it completely
=> Fix opening Meditor when clicking on "Fix Issues" in the list of dandiset metadata issues

.github/workflows/release.yml
this is a suspect for why we lacked deployment releases and possibly for
some commits off in the staging as well
ref: https://github.com/dandi/dandi-archive/issues/1100#issuecomment-1125119989
=> BF: provide custom commit message without token to skip the beat

dandiapi/api/views/common.py
Should result in x4 fold reduction of logs from such requests,
speed up client interactions etc.
Motivation: https://github.com/dandi/dandi-cli/issues/1018
edit 1: possible "visible" side effect is 100 assets to be displayed per page in file navigator per dandiset. Might be considered pros or cons
=> ENH: increase page size from 25 to 100

Procfile
Downstreaming https://github.com/girder/cookiecutter-girder-4/pull/190 from the cookiecutter.
This will help distinguish Heroku request timeouts from other errors that cause a `SystemExit` in sentry.
=> Add timeout to gunicorn in heroku

dandiapi/api/tests/test_users.py, dandiapi/api/views/users.py
Closes #661
Closes #630
It turns out that the allauth `SocialAccount.extra_data` field isn't _actually_ a JSONField in postgres, it's just a text field. This makes search a little more finicky, but I think I've taken a careful approach.
=> Restrict user search

dandiapi/api/tasks/__init__.py
Fixes #1095 
- Uses `QuerySet.iterator()` to avoid loading every asset into memory at once
- Uses `QuerySet.values()` to load only each asset's id into memory, instead of the entire `Asset` object
- Delays the asset validation task instead of running it in the same thread as the checksum calculation
=> Optimize loop in checksum task

dandiapi/api/views/users.py
#1124 removed the explicit ordering of user search results, which I believe is causing the flaky CI failures.
=> Sort user search results

dandiapi/api/models/version.py, dandiapi/api/models/zarr.py, dandiapi/api/tasks/__init__.py
Fixes #1151 
There's a couple places where logs indicating "errors" on the part of the client are logged as ERROR level, which are then reported as a sentry error. I think ERROR-level logging should be reserved for actual programming errors or abnormal system failures, not user "errors" like validation failures that are a normal part of the system. Any thoughts @AlmightyYakob @waxlamp?
=> Use `logging.info` for user errors instead of `logging.error`

dandiapi/api/tests/test_unembargo.py, dandiapi/api/tests/test_zarr_upload.py, dandiapi/api/views/zarr.py, dandiapi/settings.py
I believe this is the root cause of https://github.com/dandi/dandi-cli/issues/1028, it seems that zarr upload cancelling has never worked from the API.
This was never caught, as while the function did result in an exception being raised, celery didn't propagate the exception up to the test function, and so all seemed good. To mitigate anything like this happening in the future, I've added the `CELERY_TASK_EAGER_PROPAGATES` setting to our testing configuration. This allows exceptions to propagate up.
Adding that setting also caused an error in the `test_dandiset_rest_unembargo` function to show up, which this PR fixes.
=> Fix missing zarr_id in `cancel_zarr_upload`

dandiapi/api/models/version.py
This line [https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/models/version.py#L224-L226](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/models/version.py?rgh-link-date=2022-06-30T20%3A20%3A35Z#L224-L226) loads metadata of every Asset into memory as a dict using .values, and then coerces it into a list. This means that we're essentially storing two copies of the asset metadata in memory for every Asset in the Version being validated. So for dandisets like [dandiarchive.org/dandiset/000026](https://dandiarchive.org/dandiset/000026), it appears that we're loading 80,000 JSON blobs into memory at once.
This PR changes this line to 
1) Use `QuerySet.values_list(..., flat=True)` to convert the queryset directly into a list of asset metadata JSON blobs, instead …
=> Fix excessive memory usage in asset summary calculation

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py, dandiapi/settings.py, web/src/components/DandisetList.vue, web/src/components/DandisetsPage.vue
Closes #1132
Previously, this endpoint was making heavy use of model properties in the `Dandiset` and `Version` models, in order to populate various computed / annotated fields. This caused many repeated queries (~900 SQL queries for ~350 dandisets, so around 2.5 queries per dandiset).
I've consolidated this aggregation into both a larger SQL query, and some manual aggregation in python. After this change, there are only 3 SQL queries being made by this endpoint (out of the 5 or 6 total queries you might see in the Django Debug Toolbar).
Looking back, much of this was caused by rampant use of Django model properties. I think in the future we should discourage this pattern, as it leads to lots of repeated queries (for not all that much abstraction).
=> Optimize dandiset list endpoint

dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_tasks.py
Waits until the current transaction is commited before running asset validation. 
As part of the asset validation process, the sha256 checksum is injected into the metadata. The recent changes to delay asset validation to a new task after checksumming means that there is a good chance it will run before the sha256 checksum has been commited to the database. This PR uses the `transaction.on_commit` hook to avoid this. I also made a small memory optimization by changing a `queryset.values` to a `queryset.values_list`.
Fixes #1156
=> Fix race condition in sha256 calculation

dandiapi/api/admin.py, dandiapi/api/dashboard.py
This should make all admin listing/detail pages viewable. Prior to this several of the pages were hitting timeouts or trying to render tens of thousands of DOM elements.
=> Improve load times of admin pages

dandiapi/settings.py, setup.py
`SHELL_PLUS_PRINT_SQL_TRUNCATE` is automatically set in the newer version of composed config.
=> Upgrade django-composed-configuration

web/src/components/DandiFooter.vue
or should we just make it correspond to current  year (programmatically) or the year of the last commit in the repo?
=> boost copyright to 2022 from 2019

dandiapi/api/scheduled_tasks.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tasks/zarr.py
This adds (relaxed) time limits to the tasks where it makes sense. This will help to prevent "runaway tasks" from potentially blocking the queue.
=> Add time limits to celery tasks

Procfile, dandiapi/api/manifests.py, dandiapi/api/tasks/__init__.py
This significantly speeds up and reduces the memory usage of the write_manifest_files task that takes place on publish.
The manifest files are now written in a streaming fashion, and the YAML output now uses the C implementation. Worst case time/memory usage went from ~2m20s and ~1gb ram to ~20s and ~25mb (constant time) memory usage.
As a result, I'm removing the manifest-worker since this task doesn't need to be treated differently than any others on the main worker.
Fixes #985
=> Improve manifest file writing performance

web/src/views/DandisetLandingView/DandisetPublish.vue
Adds a dialog with the checklist from #1090  that pops up when the publish button is clicked.
Closes #1090
=> Add publish "checklist"

dandiapi/api/management/commands/rename_ngff.py
Adds the script I wrote to rename .ngff files to .ome.zarr as a management command so we have it for future reference
=> Add ngff rename script as a management command

setup.py
There are several folders in `dandiapi/` that contain data files but no Python source code, and we want these to be included when dandiapi is installed.  Currently, these folders are automatically included by the combination of `graft dandiapi` in `MANIFEST.in` and `include_package_data=True` in `setup.py`, but because we set `packages` in `setup.py` to `find_packages()` instead of `find_namespace_packages()`, the folders themselves are not recognized by setuptools as packages.  [This combination of settings is deprecated](https://github.com/pypa/setuptools/issues/3340), and the setuptools developers recommend using `find_namespace_packages()` instead of `find_packages()` for such situations.
=> Properly include "data packages" in project

dandiapi/api/views/asset.py
I was using the asset paths code for [OASIS](https://github.com/ResonantGeoData/RD-OASIS) project, and I noticed a bug: If you provide part of an asset's path in `path_prefix`, the resulting path in `files` will be the remainder, not the entire filename, as you'd expect.
For example, given an asset with the name `a/b/c.zip`, providing `a/b/c` to `path_prefix` yields an entry in `files` with `.zip`.
This PR just fixes the name if it's a file. The behavior is still valid if it's a folder, so it doesn't touch that branch.
While that endpoint does have the following description
>The specified path must be a folder; it either must end in a slash or
(to refer to the root folder) must be the empty string.
I don't see a reason not to handle this case  :man_shrugging:
=> Fix partial filename from paths_prefix

dandiapi/api/management/commands/import_dandisets.py
The user can specify a new identifier for the cloned dandiset, so using the identifier from the newly created `Dandiset` is not correct. Instead, use the identifier from the dandiset API response.
Fixes https://sentry.io/organizations/dandiarchive/issues/3453536368/
=> Fix bug in `import_dandisets` script

.github/workflows/cli-integration.yml
Fixes https://github.com/dandi/dandi-cli/issues/1083
=> Unpin `numpy` dependency in CLI tests

web/src/components/DLP/DandisetOwnersDialog.vue
=> Present dialog if attempting to remove self from dandiset

dandiapi/api/tests/factories.py, dandiapi/api/tests/test_users.py, dandiapi/api/views/users.py
This fixes an unintentional behavior modification introduced in #1124, that caused user data to be displayed instead of any social account data.
=> Prefer social account data over direct user data

doc/design/zarr-support-3.md
The Zarr checksum format was changed in https://github.com/dandi/dandi-schema/pull/120, yet the design doc (the only reference outside of the code itself) was never updated to reflect this change.  This PR fixes that.
=> Update Zarr design doc for changes to checksum format

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/api/views/serializers.py
Closes #1217.
Addresses in part #397.
This specifically addresses the metadata flag for the asset list endpoint. If we want to address other aspects of that issue, they should be filed as their own respective issues.
=> Add metadata flag for asset listing

web/vue.config.js
This PR adds an "endpoint" to the frontend that proxies to the backend server info endpoint, emulating the mechanism in place on the Netlify-controlled deploys.
This works but only if you ask for the path complete with trailing slash, and I'm not sure why. Reviewers, perhaps you can recommend a better way to make this work so that the trailing slash is not required.
Closes #1108.
=> Add "/server-info" frontend endpoint in development builds

web/src/views/FileBrowserView/FileBrowser.vue
but may be JS has somewhat different syntax for regexes? dunno how we would have missed it in original review, so may be I am just wrong.
=> Escape . in regex for EXTERNAL_SERVICES

dandiapi/api/migrations/0006_default_oauth_application.py, dandiapi/api/migrations/0016_remove_metadata_tables.py, dandiapi/api/migrations/0022_upload_dandiset_alter_stagingapplication_user.py, dandiapi/api/migrations/0025_zarrarchive_dandiset.py, dandiapi/api/views/version.py, tox.ini
IME this rule rarely catches problems and regularly frustrates in the cases where uppercase variable names are often necessary e.g. migrations.
=> Remove flake8 linting rule

tox.ini
Flake8 v5 was just [released](https://pypi.org/project/flake8/#history), and causes flake8-isort to break. Pinning the version to < 5 fixes this for now.
=> Pin flake8 version

web/src/components/DandisetList.vue, web/src/components/DandisetsPage.vue, web/src/utils/constants.ts, web/src/views/DandisetLandingView/DandisetLandingView.vue
**Proposed Solution:**
We add prev and next buttons on the top right within the search toolbar as indicated in the screenshot below:
- The search parameters (query, sorting) would be inherited from the list page as query params
- Implemented using `<v-pagination>` with a page size of 1
- Any navigation event would trigger a new fetch request with a page size of 1 and page number = position of the current item. The position is calculated wrt the entire result set i.e. `page number * no of items per page + position on current page`
**Limitations**
- Query parameters may not be persisted on directly opening a DLP
**TODO**
=> Navigation buttons on landing page

dandiapi/api/views/zarr.py
This orders ZarrArchive models by created time in the Zarr viewset, eliminating some warnings in the logs.
Closes #1136.
=> Use an ordered QuerySet in Zarr viewset

dandiapi/api/admin.py, setup.py
It seems the release of Django 4.1 caused a breaking change with our admin models. As far as I can tell from the [release notes](https://docs.djangoproject.com/en/4.1/releases/4.1/), nothing else in our codebase was affected.
This PR also pins our django version to `4.1.*`, to avoid this in the future.
=> Use tuples for Admin model actions and inlines

tox.ini
Reverts dandi/dandi-archive#1226
The issue causing this (https://github.com/gforcada/flake8-isort/issues/115) has been resolved upstream.
=> Revert "Pin flake8 version"

web/src/types/index.ts, web/src/views/FileBrowserView/FileBrowser.vue
The vtk/itk js viewer (https://kitware.github.io/itk-vtk-viewer/app) used for zarr viewing automatically appends a trailing slash to the URL it is given. So, this PR changes the URL formation to automatically strip off a trailing slash if one exists.
Fixes #1235
=> Fix zarr viewer

mypy.ini, pyproject.toml, setup.py, tox.ini
Closes #1232.
This makes the necessary changes to `tox.ini` to enable `mypy` static type-checking locally and in CI. Type-checking can be run via `tox -e type`.
=> Configure mypy

dandiapi/api/tasks/zarr.py, pyproject.toml
Removes `dandiapi/api/tasks` from the excluded files list in mypy, and fixes all type errors reported by it.
=> Fix type errors in `tasks`

dandiapi/api/models/asset.py, dandiapi/api/models/dandiset.py, dandiapi/api/models/upload.py, dandiapi/api/models/version.py, dandiapi/api/models/zarr.py, dandiapi/api/tests/factories.py, pyproject.toml
Removes `dandiapi/api/models` from the excluded files list in mypy, and fixes all type errors reported by it.
=> Fix type errors in `models`

dandiapi/api/views/asset.py
Fix n+1 problem in the asset listing endpoint.
Partially addresses #1221.
=> Fix asset list performance issue

pyproject.toml
`mypy` doesn't actually report any type errors in the migrations, so this PR just removes that directory from the excluded list.
=> Remove `migrations/` from excluded mypy files

pyproject.toml
`mypy` reports no errors for the management scripts as-is, so this PR just removes it from the excluded list for type-checking.
=> Remove `management/` directory from excluded mypy files

dandiapi/api/views/asset.py
Closes #869
This change ensures that any query parameters are preserved upon pagination. To accomplish this, corresponding function has been reworked to more closely resemble the DRF pagination implementation.
=> Update assets path pagination

dandiapi/api/templates/api/mail/pending_users_message.txt
We're no longer planning to use Django Sites (#286), so this TODO is no longer valid.
=> Remove TODO about Django Sites

.github/workflows/frontend-ci.yml, web/package.json, web/src/components/DLP/DandisetOwnersDialog.vue, web/src/components/DLP/OverviewTab.vue, web/src/components/DandisetsPage.vue, web/src/components/Meditor/Meditor.vue, web/src/components/Meditor/VJsfWrapper.vue, web/src/views/DandisetLandingView/DandisetOwners.vue, web/src/views/HomeView/HomeView.vue, web/yarn.lock
We're currently using [`vue-type-check`](https://github.com/Yuyz0112/vue-type-check), a third party wrapper for `vetur`, to perform type-checking on our Vue templates. This PR removes that in favor of [`vue-tsc`](https://github.com/johnsoncodehk/volar/tree/master/packages/vue-tsc), which is the "official" type-checker for Vue introduced in Vue 3. It is also backward-compatible with Vue 2.7, so we can now use it as of #1258. Also, `vue-type-check` doesn't seem work with Vue 2.7, so this is a prerequisite for #1258 to be merged.
=> Replace `vue-type-check` with `vue-tsc`

web/src/App.vue, web/src/components/AppBar/ApiKeyItem.vue, web/src/components/AppBar/AppBar.vue, web/src/components/AppBar/UserMenu.vue, web/src/views/CreateDandisetView/CreateDandisetView.vue, web/src/views/DandisetLandingView/CiteAsDialog.vue, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/DandisetOwners.vue, web/src/views/DandisetLandingView/DandisetUnembargo.vue, web/src/views/DandisetLandingView/DownloadDialog.vue, web/src/views/HomeView/HomeView.vue, web/src/views/HomeView/StatsBar.vue, web/src/views/MyDandisetsView/MyDandisetsView.vue, web/src/views/PublicDandisetsView/PublicDandisetsView.vue, web/src/views/SearchDandisetsView/SearchDandisetsView.vue
Converts several vue components to `<script setup>`.
Partly addresses #1260
=> Convert some vue components to `<script setup>`

dandiapi/api/models/asset.py, dandiapi/api/tests/test_asset.py
It's not possible for this to return false anymore due to database constraints.
=> Remove unnecessary conditional check for schemaVersion

dandiapi/__init__.py, dev/django.Dockerfile
~~Due to the following line~~
https://github.com/dandi/dandi-archive/blob/5d721709ad06041debbee93ca592ad470dd719ab/dandiapi/__init__.py#L8
~~The existing dev docker setup doesn't work as it's described in the `README.md`, as the `dandiapi` folder isn't copied into the container at the time of pip install, causing the `dandiapi` package to not be found. This wasn't an issue before, since we didn't rely on pip actually having knowledge of our `dandiapi` package to run django. However, due to our current versioning setup, any time our app is run, it runs the above line, to determine the current version. At that point, it finds that the `dandiapi` package isn't installed, causing an error.~~
~~We can't just copy the `dandiapi` directory into the container before pip install is run, since when …
=> Fix missing package error when first using docker-compose setup

web/src/views/DandisetLandingView/DandisetPublish.vue
Fixes the `[Vuetify] The activator slot must be bound, try '<template v-slot:activator="{ on }"><v-btn v-on="on">'` console error that happens on the DLP currently.
This issue was that we were manually setting the `v-model` for the publish checklist `v-dialog` instead of letting Vuetify do it with slots (which is the correct way).
=> Fix vuetify console error on DLP

web/src/views/HomeView/HomeView.vue
`useRouter()` should be called at the top level of `script setup`, not inside `watchEffect`.
=> Fix `useRouter()` sentry error

.github/workflows/cli-integration.yml
The CLI tests have been flaky recently, and the large amount of log input makes it difficult to see what's going wrong. The `-s` flag in particular causes the output from _every_ test to be logged in realtime, while the default behavior of pytest is to only log output from failed tests at the conclusion of the test run.
=> Remove `-s` and `-v` flags from CLI integration test invocation

dandiapi/api/models/asset.py, dandiapi/api/tests/test_unembargo.py
Closes #1264
Closes #1278 
There were a couple of things wrong with the asset unembargo method
1. The metadata wasn't saved, so the metadata remained out of date and incorrect
2. The sha256 value wasn't copied to the unembargoed asset blob, leaving that field null.
@yarikoptic I believe the latter is the cause of #1278.
=> Fix asset unembargo method

web/src/components/AppBar/AppBar.vue, web/src/components/DandisetList.vue, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/FileBrowserView/FileBrowser.vue
Closes #792
Reviewers, please especially look at f4790be63307f95296e467cb0b0968e61923a6f0 and tell me if that `exact` is actually supposed to be there in some other capacity (it has no corresponding `:to`, and doesn't look like it's supposed to).
=> Use `exact` prop consistently

dandiapi/drf_utils.py, dandiapi/settings.py, dandiapi/zarr/views/__init__.py, setup.py
This creates a custom exception handler for DRF which will properly handle core django exceptions (like `ValidationError`and `PermissionDenied`) and raise them as the DRF versions. I think we should still explicitly the context specific exceptions when we can (e.g. in DRF views) - but this will allow internal APIs that aren't context aware to raise the builtin django exceptions.
=> Allow for using django core exceptions with DRF 

web/src/views/DandisetLandingView/DownloadDialog.vue
The current link in the "Download" dropdown on the DLP is invalid.
=> Fix link to download help handbook page

dandiapi/api/templates/api/mail/added_message.txt, dandiapi/api/templates/api/mail/approved_user_message.txt, dandiapi/api/templates/api/mail/new_user_message.txt, dandiapi/api/templates/api/mail/pending_users_message.txt, dandiapi/api/templates/api/mail/registered_message.txt, dandiapi/api/templates/api/mail/rejected_user_message.txt, dandiapi/api/templates/api/mail/removed_message.txt
Fixes #1165.
We shouldn't be escaping html entities in plain text emails.
=> Turn off autoescaping for text/plain emails

setup.py
This reverts commit e447f743d639dea7d09bdbcf1cd22adf720e9541.
drf-yasg fixed their bug upstream - https://github.com/axnsan12/drf-yasg/releases/tag/1.21.4.
=> Revert "Temporarily pin DRF"

dandiapi/api/tasks/__init__.py
Bump the time limit since we're running against it on our largest dandiset
=> Increase time limit for write_manifest_files

dandiapi/api/views/version.py
This makes it consistent with the Asset viewset. It also means that the query parameter to change the order of returned Versions is now `order` instead of `ordering`, making it consistent with the Asset `order` query parameter.
=> Use `django_filters` instead of DRF for Version viewset filtering

web/src/rest.ts
When I merged #1308 I didn't realize the frontend made use of that query param :facepalm:
=> Update frontend to use new query parameter for version listing endpoint

web/test/src/tests/account.test.js
Since merging #1306, this particular test has been flaky in CI for me. I suspect it might be because we're running a much newer version of puppeteer than we were before. This PR adds additional calls to `waitForRequestsToFinish` to ensure background API calls are completed before the automated browser starts clicking things.
=> Add additional waits to account E2E test

web/src/stores/dandiset.ts
These can happen when a dandiset is embargoed, and should not be reported as sentry errors.
=> Fix 401 errors from `/versions/` endpoint being reported to sentry

web/src/App.vue
Adds a [global error handler](https://v2.vuejs.org/v2/api/#errorHandler) that renders a snackbar error message whenever an uncaught exception occurs.
Closes #768.
=> Render error message in UI when uncaught exception happens

dandiapi/api/services/dandiset/__init__.py
This fixes the underlying issue causing these two sentry errors
https://sentry.io/organizations/dandiarchive/issues/3650822437/?project=5266078&query=is%3Aunresolved
https://sentry.io/organizations/dandiarchive/issues/3650556448/?project=5266078&query=is%3Aunresolved
Both of them are from an attempt to publish dandiset 204774 in staging, which doesn't exist. I'm guessing what happened is the user
1) created the dandiset
2) uploaded assets
3) clicked publish
4) deleted the dandiset.
There's a potential race condition in there between 3 and 4 where the queue is backed up with so many tasks that the publish task doesn't get kicked off until much later, potentially after the user has deleted the dandiset. In production we have dedicated queues for long-running tasks like checksumming and zarr …
=> Prevent deletion of dandisets currently being published

.github/dependabot.yml, .github/workflows/backend-ci.yml, .github/workflows/cli-integration.yml
We are currently using older versions of the updated GitHub Actions actions, and these older versions still use Node 12, [which is deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/).
This PR also configures Dependabot to create PRs updating workflows whenever a new version of a used action is released, as discussed in https://github.com/datalad/datalad-extensions/pull/105.
=> Update GitHub Actions action versions

web/src/views/DandisetLandingView/DandisetLandingView.vue
I noticed that we have a visual loading indicator on the DLP that wasn't appearing [due to a bug](https://github.com/dandi/dandi-archive/blob/master/web/src/views/DandisetLandingView/DandisetLandingView.vue#L12-L20). This PR fixes the conditional so that that loading bar appears properly. I also went ahead and added a `v-skeleton-loader` to the page as the linked issue suggests.
Closes #1013.
=> Restore DLP loading bar, add skeleton loader

.github/workflows/auto-add-issues.yml
Reverts dandi/dandi-archive#1325
Adding issues to the project board fails after merging this https://github.com/dandi/dandi-archive/actions/runs/3238087336. i guess there are some changes needed here, reverting for now so we don't miss any issues
=> Revert "[gh-actions](deps): Bump actions/add-to-project from 0.0.3 to 0.3.0"

dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_tasks.py
Following up on https://github.com/dandi/dandi-archive/pull/1006#discussion_r976903612
=> Wait until after publish transaction commits to create DOI

.github/workflows/cli-integration.yml
See https://github.com/dandi/dandi-archive/issues/1336#issuecomment-1286926124 etc.; depends on https://github.com/dandi/dandi-cli/pull/1141.
=> Disable pulling of all Docker images from Docker Hub

dandiapi/api/asset_paths.py, dandiapi/api/tests/test_asset.py, dandiapi/zarr/tasks/__init__.py
Closes #1336 
The reported issue was caused by the following:
* When a zarr is created and associated to an asset (but not ingested) it initially has a size of zero
* Ingest can then be performed, giving it a non-zero size
* If the containing asset is then updated / deleted, all parent paths are updated, decrementing the size of the asset. However, now that size is non-zero, and was never updated, so a possibly zero value is being decremented by a non-zero value, causing the value to be negative, and throwing an integrity error.
This PR updates the `ingest_zarr_archive` task to delete all asset paths that are associated with the zarr, and then re-add them after the ingestion is finished. This is essentially the same process as updating an asset path (path deletion and immediate addition), …
=> Fix asset update/deletion when associated with zarr

dandiapi/api/services/dandiset/__init__.py, dandiapi/api/tests/test_dandiset.py
Closes #1344 
This bug was due to the fact that zarrs are directly associated with a dandiset, and it so happened that their deletion was cascaded before the deletion of any dandiset versions. Since direct asset deletion is [protected](https://github.com/dandi/dandi-archive/blob/7c153de02726c89beddc35526e93a0c7d317f880/dandiapi/api/models/asset_paths.py#L12-L15) (to avoid desync), this caused an exception.
=> Fix dandiset deletion when containing zarrs

dandiapi/api/templates/dashboard/user_approval.html
This conditionally disables the approve button when a user's status is `APPROVED`.
The `REJECT` button remains enabled in case we need to revoke approval from a user for some reason (attn: @satra, is this correct?)
Closes #1341.
=> Disable APPROVE button if user is already approved

dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/dandiset/exceptions.py, dandiapi/api/services/exceptions.py, dandiapi/drf_utils.py, tox.ini
This adds specific exceptions that the services module is going to start making use of. This is part of an effort to let our different contexts (celery, drf, cli, etc) catch errors and handle them appropriately.
I'm marking this as draft for the moment because I'd like to try it out on one or two subsequent PRs.
=> Add Dandi exception classes

dandiapi/api/asset_paths.py, dandiapi/api/tests/test_asset_paths.py
This unblocks asset path ingestion in staging/prod. Previously, transactions were being used in such an inefficient way that ingestion would essentially halt.
=> Optimize version/zarr asset path ingestion

web/package.json, web/src/rest.ts, web/yarn.lock
[The `girder-oauth-client` library defaults to `window.location` for the OAuth redirect URL](https://github.com/girder/girder-oauth-client/blob/master/src/oauth-client.ts#L22). That means when trying to log in from, for example, https://dandiarchive.org/dandiset/000108, the oauth client was sending `https://dandiarchive.org/dandiset/000108` as the redirect URL. 
Note that this approached worked fine before #997 since we were using "fake" hash-based URLs, but now that we're using history mode, `https://dandiarchive.org/dandiset/000108` != `https://dandiarchive.org/` for redirect URLs.
This PR updates our oauth client to always use the current URL's `origin` instead of the entire URL. Note, explicitly specifying the redirect URL was introduced in girder-oauth-client 0.8.0, so this PR also …
=> Fix oauth client error

.github/workflows/backend-ci.yml
IMO it's annoying to have to open the job logs and sift through the entire log output from flake8, mypy, pytest, and the migrations check just to figure out why one of them failed. Any objections to running these in separate jobs so it's easy to distinguish? This will make it easier to tell at-a-glance which one failed, and also declutter the log outputs.
=> Separate backend CI into separate jobs

dandiapi/api/templates/api/mail/approved_user_message.txt, dandiapi/api/templates/api/mail/registered_message.txt
Would be useful for them and for us -- when we reach 100 subscribers, we would be able to get a shortcut name for the channel!
=> Add YouTube channel to approved/registered emails

dandiapi/api/asset_paths.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/services/asset/exceptions.py, dandiapi/api/tests/test_asset.py
=> Properly handle conflicting asset paths

dandiapi/api/services/publish/__init__.py, dandiapi/api/services/publish/exceptions.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tests/test_asset_paths.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/version.py
Refactors publishing into a service layer module.
=> Internal publishing service

web/src/components/FileBrowser/FileBrowserPagination.vue, web/src/views/FileBrowserView/FileBrowser.vue
Fixes #725.
I implemented Jared's design from #725, and also added an error message when an invalid path is entered by the user. 
Previously, a user would only run into this error if they manually edited the query params in the browser URL bar, so our very basic solution was to just kick the user back to the root directory of the dandiset if that happened. But now that there's an input to specify the page number, it's much easier for a user to enter something invalid. So, I've changed this behavior to display an error message instead of kicking them back to the root. 
I still think the UX here could use some significant improvement, but for the purposes of this PR I think it's sufficient.
=> Improved pagination design in file browser

dandiapi/api/tasks/__init__.py
After validating asset metadata, instead of looping over every Version in Python and calling .save() to update the `modified` field, just directly update them with a single query.
=> After Asset metadata validation, update Version timestamp with single query

web/src/views/FileBrowserView/FileBrowser.vue
After merging #1311, the "no files found" error message is displayed when the list of files is being fetched. This PR tweaks the list of files so that it is initially `null` instead of an empty array. `null` indicates the data hasn't been fetched yet, while an empty array would indicate the fetch occured but there was no files at the given path.
=> Fix file browser bug

tox.ini
Temporarily pins flake8, should be reverted once [the breakage in `flake8-quotes`](https://github.com/zheller/flake8-quotes/issues/110) is fixed.
=> Temporarily pin flake8

dandiapi/api/services/publish/__init__.py
#1363 introduced a bug where dandisets with pending assets could still be considered valid at publish time, this PR fixes it.
=> Fix publishing being allowed for pending assets

web/src/components/FileBrowser/FileUploadInstructions.vue, web/src/views/FileBrowserView/FileBrowser.vue
=> Add file upload instructions to file browser UI

dandiapi/zarr/views/__init__.py
Zarr upload steps unintentionally lock the dandiset it's operating on because of a `select_related`. This could cause unnecessary blocking for parallel processes that want to perform zarr uploads on the same dandiset.
=> Prevent locking dandisets during zarr upload

dandiapi/zarr/tasks/__init__.py, dandiapi/zarr/tests/test_zarr_checksums.py
Addresses the underlying issue of #1378
My original approach to this was to delete any necessary checksum files alongside zarr file deletion, but I think it complicated the zarr workflow/lifecycle too much.
=> Always clear checksum files during zarr ingestion

CHANGELOG.md, dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/zarr/checksums.py, dandiapi/zarr/tasks/__init__.py
This optimization is achieved in two main ways:
1. Using a priority queue (heap) in the `ZarrChecksumModificationQueue` class, instead of a normal queue
2. Storing all s3 files in the queue before doing any processing (see below for memory usage).
The main benefit this provides is being able to update the checksum tree strictly from the bottom up, removing duplicate file updates.
Previously, a batch of files were fetched, immediately processed, and the next batch fetched, etc. This resulted in all parent checksum files being updated (up to the root checksum file) in every batch. The optimized method only updates each checksum file once.
The outcome of this optimization is an almost 2x speed improvement. For a zarr archive with ~37k files (52.5GB), I observed an average runtime of ~83s, …
=> Optimize `ingest_zarr_archive` task

dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/management/commands/revalidate.py, dandiapi/api/services/asset/metadata.py, dandiapi/api/services/metadata/__init__.py, dandiapi/api/services/metadata/exceptions.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tasks/scheduled.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_unembargo.py, dandiapi/api/tests/test_version.py
This is the start of a metadata service layer module. For this first PR, I've just moved the `validate_asset_metadata` and `validate_version_metadata` tasks into a `metadata` service.
The goal is to eventually have all metadata changes go through the service layer, so there's definitely other metadata-related functionality that can be moved into this service; but, I wanted to start with what are hopefully the least controversial changes.
=> Move metadata validation tasks into the service layer

dandiapi/api/apps.py
Related #1094 
I've verified the `backups2datalad` user agent isn't noisy anymore since the improved asset endpoint was merged.
=> Remove special casing of backups2datalad user agent

dandiapi/zarr/checksums.py, dandiapi/zarr/management/commands/ingest_dandiset_zarrs.py, dandiapi/zarr/management/commands/ingest_zarr_archive.py, dandiapi/zarr/tasks/__init__.py
Depends on #1387 and #1390
This PR simplifies the zarr ingest task in the following ways:
* Don't explicitly count files/size, just retrieve from the checksum afterwards
* Remove `no_checksum`, `no_count`,  `no_size` flags
=> Simplify ingest_zarr_archive task

.github/dependabot.yml, setup.py, tox.ini
We keep having issues with CI/testing dependencies introducing breaking changes, causing CI to fail. 
#1359 
#1380 
https://github.com/dandi/dandi-archive/pull/1387#issuecomment-1343052208
etc...
I think we should just pin all testing dependencies and let dependabot manage updating them for us. Since we'd only be pinning testing dependencies, any dependabot PRs that pass CI can just be merged without a second thought.
=> Manage CI dependencies with dependabot

dandiapi/zarr/views/__init__.py
From https://docs.djangoproject.com/en/4.1/ref/models/querysets/#select-for-update
> By default, select_for_update() locks all rows that are selected by the query. For example, rows of related objects specified in [select_related()](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#django.db.models.query.QuerySet.select_related) are locked in addition to rows of the queryset’s model. If this isn’t desired, specify the related objects you want to lock in select_for_update(of=(...)) using the same fields syntax as [select_related()](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#django.db.models.query.QuerySet.select_related). Use the value 'self' to refer to the queryset’s model.
=> Use proper syntax for only locking ZarrArchive table

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/urls.py, dandiapi/zarr/tests/test_zarr.py, dandiapi/zarr/views/__init__.py
This is a simplification, and will as a result fix any zarrs with out of sync file listings (any other zarrs affected by the underlying issue to https://github.com/dandi/dandi-archive/issues/1378).
@jwodder This is a breaking change and will require a corresponding CLI update. If anything here seem infeasible / unreasonable, please let me know.
Notable breaking changes:
* The url is now `zarr/{zarr_id}/files`
* To filter by prefix, use the `prefix` query param
* To limit the number of files returned, use the `limit` query param (default 1000)
* To perform pagination, provide the `after` query param, setting it to the key of the last item in the previous listing
* To be redirected to file download (requires providing file name in `prefix`), set the `download` flag to `true`
* The asset …
=> Use flat file listing in zarr file browser

dandiapi/api/services/asset/__init__.py
Removing the old asset and creating the new one already sets up the correct asset paths.
=> Remove redundant call to update_asset_paths

docker-compose.yml
See https://www.postgresql.org/docs/current/runtime-config-logging.html.
This should log all queries that take > 100ms and all queries that take more than 1s to acquire a lock.
=> Add more detailed logging to development postgres

.github/dependabot.yml
This should make dependabot even less noisy by only providing PRs for minor and major updates.
I also added a label to our project called `skip-release`. It has no effect and shouldn't be used, but it will trick dependabot into omitting the major/minor labels that conflict with our release process, see:
- https://github.com/dependabot/dependabot-core/issues/3465
- https://github.com/dependabot/dependabot-core/blob/5dc907e3148961c74ddc0b4494730f8e86118f79/common/lib/dependabot/pull_request_creator/labeler.rb#L206
Meanwhile, we should subscribe/upvote the grouped updates feature https://github.com/dependabot/dependabot-core/issues/1190.
=> Ignore patch updates for dependabot

dandiapi/api/apps.py
Asset download has seen an uptick in traffic lately and is using up a lot of our sentry performance transactions.
=> Reduce sentry performance sample rate for asset download

doc/design/zarr-performance-redesign.md
@satra, @yarikoptic, and @jwodder, please take a look at this design doc ([rendered](https://github.com/dandi/dandi-archive/blob/zarr-overhaul-dd/doc/design/zarr-performance-redesign.md)).
This simpler design should solve the remaining performance problems with Zarr upload without compromising correctness, only requiring minor changes in how the archive and the CLI coordinate to accomplish it (see the doc itself for details).
=> Add design doc for Zarr upload process simplification

.github/dependabot.yml
I misread the [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore) :sweat_smile:
=> Fix dependabot ignore type

dandiapi/api/services/dandiset/__init__.py
User reported being unable to delete a dandiset and it was not clear why it was denied.  If we do channel those messages in responses - this should make it clear why request was denied.
=> ENH: explicitly describe both cases of not allowed dandiset deletion

web/src/stores/dandiset.ts, web/src/views/DandisetLandingView/DandisetLandingView.vue, web/src/views/DandisetLandingView/DandisetPublish.vue
To replicate this bug, go to a publishable dandiset and click publish:
https://gui-staging.dandiarchive.org/dandiset/204686?page=6&sortOption=0&sortDir=-1&showDrafts=true&showEmpty=false&pos=41
https://gui-staging.dandiarchive.org/dandiset/204685?page=6&sortOption=0&sortDir=-1&showDrafts=true&showEmpty=false&pos=42
https://gui-staging.dandiarchive.org/dandiset/204677?page=6&sortOption=0&sortDir=-1&showDrafts=true&showEmpty=false&pos=45
https://gui-staging.dandiarchive.org/dandiset/204681?page=6&sortOption=0&sortDir=-1&showDrafts=true&showEmpty=false&pos=44
After clicking publish, the UI immediately starts bugging out and rerendering the DLP every few seconds. This is caused by some reactivity bug with the `loading` variable in the store. This particular variable is only used in a single …
=> Fix publishing UI bug

dandiapi/api/templates/dashboard/user_approval.html, dandiapi/api/views/dashboard.py
=> Require rejection reason when rejecting a new user

.github/workflows/frontend-ci.yml, dandiapi/api/views/stats.py, dandiapi/settings.py, web/test/src/tests/homePage.test.js
Closes #1412 
Notably, this doesn't actually change how the stats are computed, it just adds a cache. Using the asset paths models to compute this results in a slightly different value than we have now. Rather than try to determine what course of action we should take (a behavior change), I just wanted to get the difference making optimization in.
=> Add 12 hour cache to stats endpoint

dandiapi/api/models/version.py, dandiapi/api/services/metadata/__init__.py, dandiapi/api/services/publish/__init__.py, dandiapi/api/tasks/scheduled.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_version.py
For some background: modifying assets requires modifying the draft version to update the asset summary. This creates write contention on the version when assets that belong to the same version are being modified concurrently. The problem is complicated because the asset summary can take several seconds on larger dandisets and the time grows linearly with the asset count. To date this has only been a problem with our largest dandiset. 
This PR moves the asset summary computation to an asynchronous task, similar to version metadata validation. 
@mvandenburgh Can you take a look at this PR closely since it touches some of your recently modified publishing code? 
This is a draft for right now, I want to look closer into the version lifecycle before I merge.
=> Compute asset summary asynchronously for draft versions

web/src/components/DLP/OverviewTab.vue
=> Update DLP UI for asynchronous assets summary

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_tasks.py
This restores some of the logic from #1431 to get valid `PublishedDandiset`s for not-yet-published dandiset versions.
=> Restore published version emulation for validation purposes

doc/design/zarr-performance-redesign.md
This reverts an addition we made to the original design in #1415.
=> Simplify zarr upload process design

dandiapi/zarr/tests/utils.py
This was causing an interesting bug where the path could be a/something.nwb and this trimming would turn the path from relative to absolute.
=> Stop trimming characters off of test zarr paths

web/src/components/DLP/OverviewTab.vue
Follow on PR to #1452 updating the `OverviewTab` to the latest `<script setup>` and `import type` syntax.
=> Convert `OverviewTab` component to `<script setup>`

dandiapi/api/asset_paths.py, dandiapi/api/tests/test_asset_paths.py, dandiapi/api/views/asset.py
Closes #1469
~~Opening this as a draft, as the locking has been added, but I haven't figured out a good way to test this, since we'd need to test against a race condition.~~
This adds a lock at the API level for asset update and delete, as well as updates the asset paths implementation to raise an `AssetAlreadyExists` error, if the `unique-version-path` unique constraint fails on asset path creation (i.e., if an asset with a conflicting path is attempted to be added to a version).
Since we can't effectively test the API level race condition, I've done testing locally _without_ the included changes, confirmed I was able to reproduce the error, and then tested locally _with_ the included changes, and confirmed that the API behaves as expected.
=> Add locking to asset update/delete at API level

.github/workflows/frontend-ci.yml
CI is currently failing due to the `setup-node` action now defaulting to Node 18. Ideally we would use node 18, but 18 isn't compatible with vue-cli 4. I tried updating to vue-cli 5, but that also implicitly bumps webpack from v4 to v5, which one of our dependencies has some compatibility issues with. We're presumably going to upgrade to Vue 3 relatively soon, at which point this will all be moot because we'll be using Vite instead of vue-cli/webpack. So, for now I've just pinned our node version to 16.
=> Pin to Node 16 in CI

dandiapi/api/services/metadata/__init__.py
Related #1489 
@satra I think I understand what you're getting at and this PR is what I'm hoping satisfies requirements. I'll recap my understanding of these changes and rationale for confirmation/discussion.
1. Stop catching ValueErrors when validating assets
We shouldn't be marking assets invalid for what are likely bugs in our dandi-archive/dandi-schema software. Instead, an exception will be unhandled and thus tracked in Sentry. The asset will be unable to be validated until we intervene to fix the bug. Since we've been masking this error and storing the results, we can say that all ValueErrors that have been caught to date are of the form `Metadata version x.y.z is not allowed. Allowed are: x.y.z, ...`. (Maybe this is related to https://github.com/dandi/dandi-cli/issues/935).
2. Stop …
=> Remove overly aggressive exception handling

dandiapi/api/storage.py, dandiapi/zarr/models.py, dandiapi/zarr/tests/test_zarr_upload.py, dandiapi/zarr/views/__init__.py, doc/design/zarr-performance-redesign.md
Related #1494 
The MD5 parameter needs to be part of the original signed URL, otherwise S3 will reject the upload URL. This means the MD5 header used by the client is mandatory.
The CLI will need to update the `/files` step to take a `[{path: foo, md5: bar}, ...]` structure instead of a plain list of paths.
=> Add back md5 to zarr object url signing

dandiapi/api/storage.py, dandiapi/zarr/models.py, dandiapi/zarr/tests/test_zarr_upload.py, dandiapi/zarr/views/__init__.py
=> Rename field in zarr file request to `base64md5` for clarity

.codespell_dict, .codespellrc, dandiapi/api/models/oauth.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_asset_paths.py, dandiapi/api/tests/test_upload.py, dandiapi/api/views/serializers.py, dandiapi/zarr/tests/test_ingest_zarr_archive.py, doc/design/deployment-1.md, doc/design/embargo-full.md, doc/design/embargo-mvp.md, doc/design/publish-1.md, doc/design/zarr-performance-redesign.md, doc/design/zarr-support-3.md, tox.ini, web/src/components/Meditor/state.ts, web/src/rest.ts
I will monitor https://github.com/codespell-project/codespell/issues/2727 to introduce here whenever a way given.
=> Add codespell config and fix typos to `tox -e lint`, fix typos, add custom dictionary (not enabling for now)

scripts/papertrail.py
This script aids in the download of papertrail logs, as past 2 weeks, we can't easily search papertrail from the UI, and must download the hourly logs. To aid in this, this script will concatenate the logs into one file that can be easily searched.
=> Add script to download papertrail logs

web/src/views/CreateDandisetView/CreateDandisetView.vue
There was an inconsistency because we were hardcoding the max lengths for name and description, while the meditor was pulling them from the schema. This PR updates the create dandiset page to pull these values from the schema as well.
Fixes #1474
=> Fix max length for name/description on Create Dandiset page

dandiapi/zarr/tests/test_zarr_upload.py
This typo was causing linting errors in an unrelated PR
=> Fix mispelling of "occurred"

web/src/views/CreateDandisetView/CreateDandisetView.vue
=> Only allow selecting one license on create dandiset page

web/src/rest.ts, web/src/types/index.ts, web/src/views/DandisetLandingView/DandisetPublish.vue
To see this in action, go to this [dandiset](https://deploy-preview-1517--gui-staging-dandiarchive-org.netlify.app/dandiset/207380) that only contains a single Zarr and a single NWB file, and hover over the publish button.
Closes #857.
=> Disable the publish button when Zarrs are contained in the Dandiset

setup.py
Closes #1520
Should be done soonish since otherwise we would end up with situation where users can't upload after they get their dandischema upgraded somehow (pip is not strict enough at times) and they start to try uploading with newer version of schema which archive does not support.
If I got it right there is no need for explicit specification of DANDI_SCHEMA_VERSION to be 0.6.4 , if that is not true -- please share how it should be done.
=> Boost dandischema to 0.8.0 to get newer DANDI_SCHEMA_VERSION 0.6.4 supported

web/src/rest.ts
`params` must be used to pass query parameters for a GET request with axios. Since we weren't using that, no dandiset id was being sent to the zarr endpoint, causing the zarr endpoint to return the count of zarrs in the entire system, which in turn caused dandisets with no zarrs to be flagged as having zarrs.
=> Fix zarr publish error bug

DEVELOPMENT.md
In a local dev environment, the `createcachetable` Django management command needs to be run in order to initialize the cache introduced in #1416. This PR adds this step to our development docs.
=> Update development instructions

dandiapi/api/services/asset/metadata.py, dandiapi/api/tests/test_asset.py, dandiapi/zarr/tasks/__init__.py, dandiapi/zarr/tests/test_ingest_zarr_archive.py
Closes #1362
This should fix the issues with all of the zarr assets stuck in the `PENDING` state. However, when we do deploy this, we'll need to manually queue any existing zarr assets for metadata validation.
=> Handle zarrs properly in asset metadata validation

web/src/views/DandisetLandingView/DandisetMain.vue
closes #1194 
closes #1525
closes #1451
Adds the ability to copy the ID to clipboard
=> Add button to copy id to clipboard

web/src/views/DandisetLandingView/DandisetMain.vue, web/src/views/DandisetLandingView/ShareDialog.vue
closes #712 
Adds DOI link to share modal:
=> Add doi share link and update styles

web/test/src/tests/registerDandiset.test.js
This would help catch a malformed license, like the bug I introduced in #1505
=> Test for "Licenses" DLP element in E2E test

dandiapi/api/storage.py, dandiapi/api/views/asset.py, dandiapi/api/views/common.py, dandiapi/api/views/serializers.py, web/src/rest.ts, web/src/views/FileBrowserView/FileBrowser.vue
Closes #1389
Closes #1057 
This is a simple premise: add the generation of asset download URLs with a content-disposition of `inline`, and use those to drive an in-browser view of assets in the file browser.
This works for many file types, including text files and video files, but specifically not for `.mkv` files. This PR contains a hack to generate an HTML response with a `<video>` tag that "shims" the lack of support for those files.
=> Enable inline view of assets

dandiapi/api/asset_paths.py, dandiapi/api/models/asset_paths.py, dandiapi/api/models/version.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/serializers.py
These endpoint were making an excessive number of SQL queries and aggregations. This may have gone unnoticed due to this behavior stemming from properties on the `Version` model. I noticed this when viewing the DLP of dandiset `000026`, which takes several seconds to load due to these queries. This PR should greatly reduce that time.
This PR also removes the `publish_status` property from the `Version` model. This property is funtionally equivalent to the `valid` property, and causes unnecessary API slowdown, as the same information is already included in the `asset_validation_errors` field.
=> Optimize dandiset/versions and dandiset/versions/info endpoints

web/src/views/CreateDandisetView/CreateDandisetView.vue, web/test/src/tests/registerDandiset.test.js, web/test/src/util.js
- closes #758
- depends on https://github.com/dandi/handbook/pull/82 being merged and deployed
Some background: my intent here was to add a link to a new handbook page including information about licenses (see the first commit in this PR, https://github.com/dandi/dandi-archive/commit/4a42b189a3caeeb446f2ff7511df721ecc099751). But due to the way I had to add that information (without using a `hint` prop since the v-select component lacks it), this created a style dissonance. Then I looked closer and discovered several other inconsistencies in the page, which I addressed over the course of the remaining commits.
So I'd be ok with reformulating some of the changes into follow-on PRs, but I also think the improvements are of enough value that we could just accept them in this PR. As for …
=> Add license info to dandiset creation page + do a style overhaul

web/package.json, web/src/views/DandisetLandingView/DandisetMain.vue, web/yarn.lock
This PR introduces the use of [marked](https://github.com/markedjs/marked) and [DOMPurify](https://github.com/cure53/DOMPurify) to treat the description metadata field as a Markdown document.
The background here is that we'd like a way to give a bit more control to end users over the formatting of their Dandiset descriptions so they can put, e.g., "release notes" here to let consumers of their data know why they published a new version. The fuller solution for this is tracked in #189, but this feature allows a minor form of that ability in addition to its value in itself.
Closes #1567.
=> Render description field as markdown

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Closes #1563
This makes the `glob` parameter of the asset search endpoint more useful. Now, when supplying a string to the parameter, the search will be for exact matches to the string. The original behavior can be recovered by prepending and appending `*`s to cause the search to allow for an arbitrary prefix/suffix to the supplied string.
This is a breaking change, but my suspicion is that no one is using the `glob` parameter at present; furthermore, this fix adds a new capability to the system of finding assets by exact path, something that was requested in #444.
We should discuss whether a warning to the userbase is necessary because of this change.
=> Embed glob-derived regex inside a ^/$ pair

dandiapi/api/tests/test_version.py, setup.py
This test can fail when it runs across time boundaries e.g. one version is published at HH:MM and the other at HH:MM+1. This mocks the current time so the test reliably passes.
=> Fix flaky version string test

web/src/components/Meditor/Meditor.vue
Disables the feature that allows users to restore metadata saved in local storage. This is a temporary "fix" to prevent users from unintentionally overwriting their metadata due to (1) in #1574. Once fixed, this feature will be re-enabled.
=> Temporarily disable meditor local storage restore

web/src/components/DLP/OverviewTab.vue, web/src/views/DandisetLandingView/DandisetPublish.vue
This fixes a bug where the `setInterval` would continue firing after the user navigates from one dandiset to a new dandiset. This would result in unexpected behavior, such as the overwriting of the new dandiset with the metadata from the old one retrieved by the `setInterval` call.
One note about the changes - I changed the use of `setInterval` to `window.setInterval`. I couldn't get TypeScript to play nicely with the return value of `setInterval` for some reason; it was trying to get me to import a type from NodeJS, but since we're in a browser environment it was erroring out. They are functionally identical though.
=> Call `clearInterval` after `setInterval` when needed

dandiapi/celery.py
This should log the args and kwargs for each task received by a celery worker. https://docs.celeryq.dev/en/stable/userguide/extending.html#customizing-task-handling-logs
=> Add celery argument logging

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml
I was having trouble finding where our production deployment was happening, because the name of the github action ("Update release branch") didn't make that clear. This PR updates that, plus the individual steps of our staging/production deploy workflows to make it easier to identify them in the github UI.
=> Make deploy workflow names more consistent

setup.py
Deploys are currently failing https://github.com/dandi/dandi-archive/actions/runs/5047436699, due to a breaking change in the `minio` python library ([this commit](https://github.com/minio/minio-py/commit/b81883a98e6f8a09e2903609caabbf0956dd0ec9), for reference)
I explained the issue behind this in the code comment, but to summarize:
- `django_s3_file_field[minio]` does not pin `django-minio-storage`, but does pin `minio` to <7. https://github.com/girder/django-s3-file-field/blob/master/setup.py#L72
- dandi does not pin either of these dependencies, but we do list `django-minio-storage` (unpinned) in our production dependencies.
- Because `django_s3_file_field[minio]` is a dev dependency, it's not installed in the Heroku environment, thus the pip resolver does not take into account the …
=> Pin `django-minio-storage`

dandiapi/analytics/tasks/__init__.py, dandiapi/analytics/tests/test_download_counts.py
There are some bugs with using this method concurrently as it stands. In order to keep the queue moving along this short circuits the task while we troubleshoot.
=> Temporarily disable s3 log file processing

web/src/views/CreateDandisetView/CreateDandisetView.vue, web/src/views/DandisetLandingView/DandisetMain.vue
This fixes some linting warnings that have been hanging around for a while.
=> Fix GUI linting warnings

web/src/components/DandiFooter.vue
old one leads to legacy and no issues could be found or filed
=> Fix URL to the dandi archive repo

dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/upload.py, dandiapi/api/views/version.py, dandiapi/zarr/views/__init__.py
As we discovered last week while discussing #1598, serializer classes used in the `swagger_auto_schema` decorator don't need to be instantiated; just passing the class itself is sufficient. Instantiating the class causes the `__init__` constructor to be called, which in most cases has no negative impact, but has the potential to lead to strange bugs like we saw with the search serializer.
=> Avoid instantiating classes in `swagger_auto_schema` when possible

web/src/components/Search/SearchParameters.vue, web/src/components/Search/forms/FileSizeForm.vue, web/src/views/SearchView/SearchView.vue
The search UI is unusable on smaller screens. I played around with different viewport heights/widths in the chrome dev tools and fixed all of the issues I could find -
- Remove some unneeded padding
- Make file size inputs "dense" to make them look nicer on smaller screens
- Specify a minimum width for the file size inputs
- Introduce a bit of responsive design for smaller screens - if the screen is not wide enough to accommodate the search filters on the left and the search results on the right, they will instead stack on top of each other.
=> Fix search UI for smaller screens

Procfile, dandiapi/analytics/tasks/__init__.py
Sibling PR to https://github.com/dandi/dandi-infrastructure/pull/152.
Ultimately there is too much contention between updating blob counts to do it in parallel. This is because closeby log files often contain similar blobs and so multiple jobs are fighting over which gets to lock those blob records first.
=> Add concurrency=1 worker dyno for processing S3 logs

web/netlify/plugins/server-info-build/index.js
By default, the /api/info endpoint (to which the frontend /server-info endpoint performs a rewrite) serves a response with `format=api` which includes framing content, including CSS, etc., and a dropdown to switch formats, all of which is inappropriate for this frontend endpoint.
This PR changes the target of the rewrite to the `format=json` URL, sidestepping the problems reported in #1593.
Closes #1593.
=> Serve pure JSON from /server-info frontend endpoint

web/test/package.json
`test` is the name of a core node module and shouldn't be used here. This will silence the warning that gets printed in CI when the e2e tests run.
ref: https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields
=> Rename e2e test package

dandiapi/api/models/version.py, dandiapi/api/tests/test_version.py, web/src/components/DLP/ValidationErrorDialog.vue, web/src/types/index.ts, web/src/views/DandisetLandingView/DandisetPublish.vue
This displays validation errors in a modal, instead of a small menu next to the sidebar. The version metadata validation errors remain largely unchanged. The asset validation errors have been improved to both display the path of the asset, as well as group the errors of an asset, if an asset contains multiple errors.
This is how it looks now:
=> Improve validation error display

dandiapi/api/views/dashboard.py
The user approval form handler was relying on "active" being the default state for a Django user, and therefore users who were approved after being rejected retained their "inactive" status. This PR fixes that by explicitly setting users to active whenever they are approved.
Closes #1619.
=> Fix user approval workflow

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_version.py
Fixes https://github.com/dandi/dandi-schema/issues/183.
This should remove the `encodingFormat` errors we've been getting for a while. After this I'll manually trigger a re-aggregation for draft versions.
=> Limit aggregate asset summaries to valid assets

dandiapi/zarr/tasks/__init__.py
It's unlikely this has happened in practice, but this guarantees a change can't occur during zarr ingestion without failing loudly.
=> Prevent race condition during zarr ingestion

web/test/package.json, web/test/src/tests/registerDandiset.test.js, web/test/src/util.js, web/test/yarn.lock
This PR adds core-js to frontend testing allowing us to use `scrollIntoView` on the puppeteer DOM.
It is good to note that this is a workaround. Ideally we would use the `scrollIntoView` function provided by puppeteer but that was not introduced until `v19.9.0`. We are currently on `v17.1.3`. There are quite a few breaking changes between these releases though.
https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v19.9.0
=> add scrollIntoView for UI tests

web/src/views/HomeView/HomeView.vue, web/src/views/HomeView/SingleStat.vue, web/src/views/HomeView/StatsBar.vue
fixes #1611 
Removes excess rows and adjusts props for remaining rows to fix the responsive view of stats bar. Phone view shown below.
=> Remove excess rows to fix responsive view of stats bar

dandiapi/api/services/publish/__init__.py
We're evaluating two querysets here (which produces two SQL queries), when we really only need to evaluate one.
=> Consolidate two DB queries into one

dandiapi/api/services/dandiset/__init__.py
This wasn't actively causing problems, but it's a good idea to do these in a transaction.
=> Atomically delete dandiset and its versions

web/src/views/FileBrowserView/FileBrowser.vue
=> Adding neurosift to external services

dandiapi/api/views/asset.py
x-matroska is not the only one which browsers should be able to play. E.g. video/mp4, video/webm, and video/ogg are the other ones I (and chat gpt) knows to generally be supported.  To avoid needing to list them all explicitly and thus always playing catch up game of assumptions, I would just allow browser to try on any video/ one. Worse could happen it would not work, and might ask to download I guess.
Might close (edited by @waxlamp: it doesn't) #1626 but I didn't check if it would work for those files:
❯ curl --silent https://api.dandiarchive.org/api/assets/942b0806-2c8b-4289-a072-9e965884fcb6/ | jq .encodingFormat
"video/x-msvideo"
=> Assume that browser can play any "video/" content type.

web/src/components/DandiFooter.vue
It seems the app prop causes the footer to overlap with the rest of the page content in an undesirable way. @marySalvi applied another change via #1633 which fixes the underlying issue (#1611) more directly, so the `app` prop can be removed.
=> Remove "app" prop from footer

.github/dependabot.yml, setup.py, tox.ini
#1402 was a useful experiment to see if we could avoid having to deal with CI failures due to breaking changes in flake8, black, mypy, etc. by pinning them and managing upgrades via dependabot. But as we discussed, the large volume of dependabot PRs that it resulted in ends up consuming more time to approve and merge than it is to deal with the (very) occasional breakage. Thus, this PR effectively reverts #1402.
=> Unpin dev-only dependencies + disable dependabot

dandiapi/settings.py, dandiapi/urls.py
Currently, we use allauth's regular "account" provider for user management in dev, and its github "socialaccount" provider for prod. However, we expose endpoints for both of these auth flows in prod and dev. This means that someone can sign up using the regular "account" provider in production, bypassing github entirely. In practice, this hasn't happened before because we don't advertise these URLs publicy; however if you know the URL, a user could navigate to https://api.dandiarchive.org/accounts/signup/ directly and sign up.
This PR adds a new setting `ENABLE_GITHUB_OAUTH`. If enabled, only the github socialaccount provider endpoints are exposed. If disabled, only the "account" provider endpoints are exposed.
=> Add new Django setting to restrict allauth endpoints that are exposed

setup.py
There is a breaking change in this version, so we need to ensure we are at or above it for compatibility reasons. 
Merging #1678 caused the fix for this breaking change to get applied in staging, but staging is still running an older version of allauth due to Heroku's dependency caching.
Should be reverted when https://github.com/girder/django-composed-configuration/pull/189 is merged.
=> Pin django-allauth to minimum version

setup.py
There is a breaking change in the latest release of `django-storages` that is causing CI to fail. For now, I've pinned it to the last working version in order to get CI unblocked while I debug this further.
=> Pin django-storages temporarily

dandiapi/api/copy.py, dandiapi/api/manifests.py, dandiapi/api/services/metadata/__init__.py, dandiapi/api/views/dandiset.py, doc/design/publish-1.md
`full_metadata` can require reaching into the `blob` and `zarr` which can be costly for bigger versions.
=> Remove n+1 queries when using full_metadata

dandiapi/api/tasks/__init__.py, dandiapi/api/tasks/scheduled.py
The length of these tasks has started creeping up (especially for dandiset 26). Increasing these timeouts in response to sentry timeout errors.
=> Increase task timeouts for manifests/asset summaries

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml
We don't enforce any `concurrency` rule on the github actions that deploy our Django app to Heroku. This opens us up to potential issues, such as a scenario where an older deploy job ends up running after a newer job, causing the older version of the app to "overwrite" the newer one on Heroku.
=> Fix possible race condition in deployment actions

web/src/views/FileBrowserView/FileBrowser.vue
When an external service is called from the file browser, the asset URL used is always the S3 URL, even in the case of an owner browsing an embargoed Dandiset. In the latter case, the S3 URL, which is _not_ presigned, does not allow general access to the asset, causing the external service to fail when it tries to retrieve the data.
This PR modifies the generation of that asset URL to emit the S3 URL for open Dandiset assets, and the internal DANDI API asset URL (which redirects to the correct presigned S3 URL) for embargoed Dandiset assets. (Note that the target external service must still authenticate to the DANDI server in order for this redirection to succeed; that in turn requires a design that supports using DANDI API keys, etc.)
=> Use correct asset download URL for external services

dandiapi/api/models/asset.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/tests/test_asset.py
The logic for PUT on asset metadata includes a check to see if the asset is "different" enough to warrant an actual change. This works in part by stripping the supplied metadata of all computed fields, of which `path` is one, and then comparing what remains. This had the effect of barring any "move" type operations (by changing just the `path` value of a metadata and performing a PUT), as changes to the path did not "count" towards being different enough. The workaround was to _also_ change a _non_-computed metadata field; this made the asset different enough to trigger a change, which included the changed path.
The fix is to teach the "is different" function about path-only changes.
Thanks to @AlmightyYakob for his help in figuring this out.
TODO:
Closes #1682.
=> Enable path-only changes to metadata to trigger asset change

.github/workflows/backend-staging-deploy.yml
After #1679, the staging deploy that occurs during a release merge gets interrupted by a second staging deploy triggered by `auto`'s push to master containing the updated `CHANGELOG.md`.
This PR prevents that second deploy from running, avoiding a spurious deploy failure that happens when the first deploy is canceled.
Thanks to @mvandenburgh for helping me debug this problem.
=> Prevent CHANGELOG.md from triggering staging deploy

setup.py
Fixes #1702. 
#1702 was fixed in `dandischema` a while back with https://github.com/dandi/dandi-schema/pull/167 and a new version of `dandischema` was released, but we never bumped the version of `dandischema` in dandi-archive. 
Note this does not solve the underlying fake doi injection issue, but it will fix DOI creation on dandiarchive.org. As part of this, I will query for all published dandisets that do not have a DOI due to this bug and re-run the DOI generation on them.
=> Upgrade `dandischema` dependency

dandiapi/api/doi.py
A recent release of `requests` changed the type of `requests.exceptions.HTTPError.response` from `Response` to `Response | None`, so it's now necessary to check if `HTTPError.response` is `None` before inspecting it.
This will fix the `mypy` failures on master.
=> Fix `requests` type errors

web/src/components/FileBrowser/FileBrowserPagination.vue, web/src/views/FileBrowserView/FileBrowser.vue
Closes #1677 
This PR adds the page index value to the route query.
Please also note that I removed a few watch statements in favor of reactive values as the watch statements were causing multiple calls with the added query value. I think its generally good practice to avoid watches when possible.
=> File page index fix

.github/workflows/cli-integration.yml
This disables the broken CLI tests, while leaving the rest of the CLI test suite enabled. This should get CI green again and prevent legitimate CLI test failures from going unnoticed.
=> Temporarily skip broken dandi-cli tests

dandiapi/api/copy.py, dandiapi/api/management/commands/cleanup_blobs.py, dandiapi/api/storage.py, dandiapi/api/views/asset.py, dandiapi/conftest.py, setup.py
The bug that mandated pinning this dependency (#1691) has been fixed in the latest release of `django-storages` ([here's the changelog entry](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#s3)), so we can remove the pinning.
Additionally, the latest minor release of `django-storages` also deprecates `storages.backends.s3boto3.S3Boto3Storage` in favor of `storages.backends.s3.S3Storage`, as well as changes the install extra from `[boto3]` to `[s3]`, ([changelog entry](https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#s3-2)), so I went ahead and made those changes here as well.
=> Remove pinning on django-storages[boto3]

dandiapi/api/services/publish/__init__.py, dandiapi/api/tasks/__init__.py
I don't think the `atomic` decorator actually does anything for these task functions, but please correct me if I'm missing something @danlamanna @AlmightyYakob. 
Any complex operations that do need to be atomic are already wrapped in an `atomic` block inside the service layer functions that the tasks are calling.
=> Remove unnecessary atomic decorators from tasks

dandiapi/api/asset_paths.py, dandiapi/api/views/dandiset.py
This reduces the load time of the dandiset listing endpoint by optimizing the `_get_dandiset_to_version_map` function. This means the search endpoint should also experience a slight performance improvement, since it also uses that function.
The optimization is accomplished with the following changes:
1. Removes an unnecessary query being made in the `get_root_paths_many` function
2. Shifts the version stats aggregation to be done in postgres, making it more efficient
3. Optimize the query for retrieving the latest version. Similar to the other optimized query, this leverages postgres aggregation to efficiently return the latest published versions for all relevant dandisets
4. Use two smaller queries instead of one union-ed query when retrieving drafts and published versions, to take …
=> Optimize dandiset listing endpoint

dandiapi/api/templates/api/account/questionnaire_form.html
I think we start to get an increasing number of registration requests from people who are not intending to upload data to DANDI.  This explicit message might help to avoid those registration requests.
=> Add a note to registration page that no account is necessary to access public data

dandiapi/api/asset_paths.py, dandiapi/api/views/info.py
The actual problem here is inappropriate use of `os.path.join` for joining components of a URL (which should always use `/`, not an OS-dependent delimiter).
Joining the components with f-strings matches the way other parts of the code create URLs.
Future work could use some URL library to manipulate URLs, but that's out of scope of this fix.
=> Fix PTH118 `os.path.join()` should be replaced by `Path` with `/` operator

dandiapi/api/manifests.py
This follows #1184, but reduces unnecessary re-encodings from bytes to strings. It also cleans up the `manifest.py` module, by making more of the API private and adding additional type annotations.
=> Clean up and improve the performance of manifest file creation

dandiapi/api/views/dandiset.py, setup.py
Now that django-allauth uses a regular JSONField for `SocialAccount.extra_data`, we can optimize the dandisets owner PUT endpoint to be more efficient and do less SQL queries. See release notes for allauth here https://github.com/pennersr/django-allauth/blob/main/ChangeLog.rst#0580-2023-10-26
=> Optimize dandiset owner PUT endpoint

web/src/views/FileBrowserView/FileBrowser.vue
This adjusts the external endpoint URL for neurosift such that it:
* always provides the version of the asset URL that includes that asset ID (rather than just doing this for embargoed dandisets)
* provides the dandiset ID and version
This is information I would like to have access to on the neurosift end.
I tried to do this in the most straightforward way I could -- if adjustments are needed in the future I think it wouldn't be a problem since it only affects the one file. But if there is a better way @waxlamp, feel free to suggest.
The other external services should work the same as they did before.
I realize that this is related to https://github.com/dandi/dandi-archive/pull/1655 but I wanted to start from the latest commit that includes the other related changes from …
=> adjust neurosift service endpoint URL, passing additional info

dandiapi/analytics/tasks/__init__.py, dandiapi/api/mail.py, dandiapi/api/tasks/__init__.py, dandiapi/api/user_migration.py, dandiapi/zarr/tasks/__init__.py, dandiapi/zarr/views/__init__.py
See https://docs.astral.sh/ruff/rules/logging-f-string/ for the basic rationale.
However, this is particularly relevant to the use of Sentry. By ensuring variable parts of the log message are always passed as parameters, it is much more likely that Sentry consolidate multiple events with different parameters into the same issue.
=> Fix G004 Logging statement uses f-string

dandiapi/api/models/version.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/serializers.py
Currently, we assume that `Version.metadata['contributors']` is a list of JSON objects. This holds true for any metadata uploaded by the DANDI CLI, but there's nothing preventing users from uploading arbitrary JSON. Invalid metadata will be marked as invalid, but there's some places in the code where we assume it's valid anyway which results in a crash. This PR adds some additional checks to those places to avoid outright crashes.
Closes #1769
=> Fix invalid contributors causing crash

web/src/views/FileBrowserView/FileBrowser.vue
I overlooked this in #1706. The replacements on service url aren't being done correctly.
=> [FIX] serviceUrl replacement

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_version.py
Changes to version metadata that came in while `version_aggregate_assets_summary` is running can be overwritten. This change will only update the assetsSummary if the metadata is the same at save time, otherwise, it's a noop and the summary aggregation is retried.
=> Avoid clobbering version metadata when calculating assets summary

dandiapi/api/doi.py, dandiapi/api/mail.py, dandiapi/api/models/asset.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/storage.py, dandiapi/api/views/asset.py, dandiapi/api/views/auth.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/upload.py, dandiapi/api/views/version.py, dandiapi/drf_utils.py, dandiapi/swagger.py
I'm not sure if I like this rule or not. Most of the time, I think it probably is the right thing for readability, but sometimes it seems worse. Maybe I'm just not used to it?
=> Fix RET505 Unnecessary `else` / `elif` after `return` statement

dandiapi/api/asset_paths.py, dandiapi/api/management/commands/cleanup_blobs.py, dandiapi/api/management/commands/collect_garbage.py, dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/management/commands/depose_placeholder.py, dandiapi/api/management/commands/migrate_published_version_metadata.py, dandiapi/api/management/commands/migrate_version_metadata.py, dandiapi/api/management/commands/revalidate.py, dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/version/metadata.py, dandiapi/api/signals.py, dandiapi/api/user_migration.py, dandiapi/zarr/management/commands/ingest_dandiset_zarrs.py, dandiapi/zarr/management/commands/rename_ngff.py, dandiapi/zarr/tasks/__init__.py, scripts/delete_from_versioned_bucket.py, scripts/papertrail.py
This explicitly expects Django signals and Click options to be called with keyword arguments.
=> Fix FBT001 Boolean-typed positional argument in function definition

dandiapi/zarr/tests/test_zarr.py
Part of dandi/dandi-schema#209
=> `test_zarr.py`: Import `EMPTY_CHECKSUM` from `zarr_checksum`

doc/design/embargo-redesign.md
This PR adds the design doc that outlines the new embargo design, with unified bucket storage.
=> Add embargo re-design doc

dandiapi/api/views/dashboard.py
If the user is not authenticated, they will now be redirected to the login URL instead of getting an unauthorized error.
Fixes #1701
=> Add login redirect to user dashboard

web/src/components/AppBar/AppBar.vue, web/src/components/AppBar/UserMenu.vue, web/src/components/DLP/DandisetOwnersDialog.vue, web/src/components/Meditor/localStorage.ts, web/src/components/Search/forms/GenotypeForm.vue, web/src/components/Search/forms/SpeciesForm.vue, web/src/components/UserStatusBanner.vue, web/src/rest.ts, web/src/stores/dandiset.ts, web/src/views/DandisetLandingView/DandisetOwners.vue, web/src/views/DandisetLandingView/DandisetPublish.vue, web/src/views/FileBrowserView/FileBrowser.vue
The `rest` module seems to be blocking the upgrade to Vue 3; in Vue 2, it was possible to initialize a Vue object as follows:
```javascript
const dandiRest = new Vue({
data() {
return { user: null }
},
...
});
```
And then access a data object like this:
```javascript
console.log(dandiRest.user)
```
But, the equivalent Vue 3 code doesn't work:
```javascript
const dandiRest = Vue.createApp({
data() {
return { user: null }
},
...
});
console.log(dandiRest.user) // doesn't work
```
I'm not sure what the issue is or how it was changed, but I can't even find the docs that specified this behavior for Vue 2. I'd be curious to hear if anyone has any ideas why that is. But regardless, converting to Composition API avoids this issue and is also something we've planned for a long time, so I just …
=> Convert `rest.ts` to composition API

dandiapi/analytics/tasks/__init__.py, dandiapi/api/asset_paths.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/publish/__init__.py
In non-test parts of the codebase, `assert` shouldn't be used. See https://docs.astral.sh/ruff/rules/assert/ for rationale.
=> Fix S101 Use of `assert` detected

requirements.txt, setup.py
We don't use pydantic directly anywhere. Also, dandischema lists the `pydantic[email]` extra as a dependency now, so we can remove it from `requirements.txt` as well.
=> Remove explicit dependency on `pydantic`

dandiapi/api/views/dashboard.py
Fixes #1701 
This is a follow on to #1781. After that PR, accessing the user approval pages while unauthenticated results in a redirect to the login endpoint, which subsequently redirects to github; but, github redirects the user back to the root path `/` because it doesn't know where the user came from. They allow specifying an optional `next` query parameter, which github will respect and redirect the user to if it's supplied, so I updated the redirect to do that here.
=> Approval view: automatically redirect back to page after authentication

requirements.txt
This was added a few years ago to work around issues with Heroku using an older pip version. This should no longer be the case, so we can remove this and let Heroku use setup.py for dependency management only.
=> Remove `requirements.txt` file

dandiapi/api/services/dandiset/exceptions.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py
Fixes #1788
This slightly changes the way the API behaves, aside from the stated goal. Previously, we defaulted to a value of `true` when `embargoed` was not specified. This PR changes that default to `false`, as otherwise, any un-authenticated users would need to always explicitly pass `embargoed=false` when calling the dandiset list endpoint.
cc @yarikoptic
=> Return 401 on unauthenticated embargo dandiset list

dandiapi/api/services/metadata/__init__.py
As described in #1805, it's possible for a `Version` to get deleted at the same time that it's being validated. This can result in an exception being raised if it gets deleted prior to [this query](https://github.com/dandi/dandi-archive/blob/master/dandiapi/api/services/metadata/__init__.py#L130-L136) being executed. To avoid this, this PR adds a check that exits the validation function early if that query returns nothing.
Fixes #1805
=> Check if version still exists before proceeding with validation

dandiapi/api/services/version/metadata.py, dandiapi/api/tests/test_tasks.py
This PR resolves the remaining failures in tests for backend in #1823 once https://github.com/dandi/dandi-schema/pull/218 is merged to the master of the `dandi-schema` repo, a new version of `dandi-schema` is published, and set to be used by `dandi-archive`.
=> Resolve remaining failures in #1823

web/netlify.toml
Setting the `ignore` value to `false` means that the `false` program (which always exits with non-zero code) will cause Netlify to always rebuild the frontend, even if there are no changes to the code. We want to do this because in fact the *git tag* that is installed as part of our deployment process *always* changes, and we need to reflect that version number in the frontend application itself.
Closes #1089
=> Always rebuild and deploy the frontend

dandiapi/api/models/version.py, dandiapi/api/views/auth.py, dandiapi/zarr/models.py, pyproject.toml
I noticed a few linting errors popping up in CI. This PR fixes them, in three bits:
1. Update pyproject.toml to use the correct ruff config section names.
2. Eliminate some explicit dictionary key checks in favor of `dict.get()`.
3. Use `logging.getLogger()` in place of directly instantiating a `Logger` object.
I believe (1) and (2) are fine (though I'd appreciate validation); (3) might be trickier: although the change I made is a best practice (even recommended directly by the [docs for the `logging` module](https://docs.python.org/3/library/logging.html#logger-objects)), it does represent a semantic change in the codebase.
Let me know if I should peel off one or more of these commits into separate PRs--glad to do so if it makes reviewing/merging easier.
=> Fix lint errors

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml, dev/django.Dockerfile, pyproject.toml, setup.py
dandi-archive is currently building its tarballs via `python setup.py`, [which is deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) and which is not the currently supported way to build with the `setuptools_scm` build-time requirement (used for storing the Git tag in the project version).
Indeed, [the latest "Deploy backend to production run"](https://github.com/dandi/dandi-archive/actions/runs/7546255291) has the following in the logs for the "Build app into tarball" step:
```
/usr/lib/python3/dist-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
warnings.warn(
/home/runner/work/dandi-archive/dandi-archive/.eggs/setuptools_scm-8.0.4-py3.10.egg/setupto …
```
=> Build project with `build` & `pyproject.toml`

web/src/views/FileBrowserView/FileBrowser.vue
This splits out a contribution from #1666 that adds tooltips to the file browser view's action icons.
(attn: @magland)
=> Add tooltips to describe FileBrowserView action icons

flake.lock, flake.nix
This PR makes it much easier for anyone running NixOS, or using the Nix package manager, to spin up a dev shell for running DANDI in native mode. For people not using those platforms, this will have zero impact.
=> Add a Nix Flake for native build dependencies

web/src/views/FileBrowserView/FileBrowser.vue
This PR improves the presentation of the file browser view icons:
- replace the "eyeball" icon with an "open in app" icon
- replace the triple dot menu with an explicit button-based dropdown menu
The open in app icon makes more sense for what that button does. And the explicit dropdown uses standard language for "open an external program", and makes the presence of those integrations more discoverable.
This was inspired by discussions on #1666.
Depends on #1845.
(attn: @magland)
=> Improve file browser view action icons

web/src/views/FileBrowserView/FileBrowser.vue
This splits out a contribution from #1666 that initiates the "view in app" action when the item itself is clicked.
Depends on #1846.
Closes #761.
(attn: @magland)
=> Open asset on click

dandiapi/analytics/tasks/__init__.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_upload.py, dandiapi/api/views/asset.py, dandiapi/zarr/models.py, dandiapi/zarr/tests/test_zarr.py, dandiapi/zarr/views/__init__.py
Following #1743, this removes the remaining uses of the filesystem APIs `os.path` and `pathlib` (which are platform-dependent and contain methods for local filesystem manipulation) to process URLs.
The `zarr_checksum` package still has this confusion in its `ZarrArchiveFile` class, but attempts to refactor some of that code failed due to other issues with it. So, the `ZarrArchiveFile.path` field is just cast to a `str` when interfacing with local application code.
=> Don't use filesystem APIs to manipulate URLs

dandiapi/settings.py
The comment used to correspond to reality, and was needed for some ad-hoc manual invocation to setTokenHack but it was removed in 984451c822525343a6f54bffad4c8fa39a68ac78 AKA `v0.1.37~27^2~9^2~79^2`
a few years ago.  Now this is the correct specification of DRF
=> Remove obsolete/not-applicable TODO

DEVELOPMENT.md
While following some instructions like this I would prefer to just be able to copy/paste and not follow unnecessary interactive prompts.
In the beginning of the doc we recommend to use the same email as for github which is likely to be the one configured in git. Hence I decided to just query `git`.
One other aspect I am fixing -- I am adding explicitly the email to `createsuperuser` so me/developer does not need to think twice to enter some other email from what I just entered interactively.
Sits on top of #1827
=> DEVELOPMENT.md: set email to the one known to git

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_tasks.py
We're seeing a very prevalent race condition, resulting in version asset summary aggregations being skipped (this can be observed via copious amounts of `Skipped updating assetsSummary for version ***` in the papertrail logs).
Here's what I believe is happening:
1. A version is updated in some way, and status set to `PENDING`
2. The scheduled task [`validate_draft_version_metadata`](https://github.com/dandi/dandi-archive/blob/65eca4a4586bfbad820d4b44ba40f97ce487a1ae/dandiapi/api/tasks/scheduled.py#L75) is run, dispatching the [`validate_version_metadata`](https://github.com/dandi/dandi-archive/blob/65eca4a4586bfbad820d4b44ba40f97ce487a1ae/dandiapi/api/services/metadata/__init__.py#L100) and [`aggregate_assets_summary`](https://github.com/dandi/dandi-archive/blob/65eca4a4586bfbad820d4b44ba4 …
=> Don't use .save() in validate_version_metadata

dandiapi/api/services/version/metadata.py, dandiapi/api/tests/test_tasks.py, setup.py, web/src/components/Meditor/types.ts, web/src/views/CreateDandisetView/CreateDandisetView.vue
Closes #1820 
TODOs
- context.json should be the same as before.
- All other files are generated by Pydantic V2 with a small modification from the default behavior, and they are compliant with JSON Schema Draft 2020-12 (https://docs.pydantic.dev/latest/concepts/json_schema/ for details)
- The small modification in behavior  is documented in point `#2` in "Additional notes regarding changes entailed by Pydantic V2" in the top post of https://github.com/dandi/dandi-schema/pull/203.
=> Boost dandischema to 0.9.* series so we get support for pydantic 2.0 and schema 0.6.5

.codespellrc, doc/design/audit-trail-mvp.md
=> Design doc for Audit MVP

dandiapi/api/tests/test_info.py, dandiapi/api/views/info.py
This PR changes the `cli-minimal-version` to v0.60.0, which is the first version of the CLI that uses Pydantic 2.
=> Require v0.60.0 of `dandi-cli`

tox.ini
Without the `ignore_errors` configuration option set to `True`, Tox exits as soon as any command in the list fails. In the case of the lint tests, we would like to continue running the commands, since they are essentially independent tests.
This was masking formatting errors whenever the `check` command was failing, preventing us from knowing that we should fix those.
(attn: @marySalvi)
=> Run all linting commands, even if some of them fail

dandiapi/api/migrations/0006_asset_path_collation.py, dandiapi/api/models/asset.py
Follow up to #1885 
While the `C.utf8` collation seemed to work locally and in CI, that collation doesn't seem to exist in the production database, and so that migration failed in production. However the basic `C` collation _is_ present across all of these environments (all postgres environments, detailed [here](https://www.postgresql.org/docs/current/collation.html#:~:text=On%20all%20platforms%2C%20the%20collations%20named%20default%2C%20C%2C%20and%20POSIX%20are%20available)) and as far as I can tell, seems to operate in largely the same way. If/when we upgrade our database version in heroku, we could perhaps change _back_ to `C.utf8`, if it mattered. 
This fix modifies the last migration, since the deployment failed in staging/production. If I were to create a new migration, I believe …
=> Change asset path collation to "C"

dandiapi/api/views/serializers.py
As @jwodder mentions [here](https://github.com/dandi/dandi-cli/issues/1413#issuecomment-1969007877), the Swagger page is unclear about some of the query parameters for the `/dandisets/` endpoint. This PR adds some help_text for them, which will be rendered on the Swagger UI.
I also changed the `user` query parameter to be a `ChoiceField` over a `CharField`, as it has only one possible value, "me"(or two if you count `null`/missing). This improves the Swagger interface by making it a dropdown select instead of a freeform textbox.
=> Improve Swagger documentation for /dandisets/ query params

setup.py
without this now dandi-cli tests failing since would use fresh dandischema which would produce records in 0.6.7 schema. AFAIK, since just patch version increment probably no adjustment needed on dandi-archive side, but let's see if tests (and/or @satra or @bendichter) say otherwise
relevant change to schema:
- Add ResourceType enum and associate with Resource model https://github.com/dandi/dandi-schema/pull/232 ([@bendichter](https://github.com/bendichter) [@pre-commit-ci[bot]](https://github.com/pre-commit-ci%5Bbot%5D))
and then also 0.10.0 had change to functionality:
- Remove Zarr checksum code https://github.com/dandi/dandi-schema/pull/217 ([@jwodder](https://github.com/jwodder))
but I hope (tests will show?) that this functionality was not used here
=> Boost dandischema to 0.10.1 which released 0.6.7 schema

dandiapi/api/views/asset.py, dandiapi/settings.py
This PR adds a rate limit of 60 requests per minute to the asset list endpoint for unauthenticated users. Logged-in users are not rate-limited. This is a short-term fix for #1891.
=> Rate limit assets list endpoint for unauthenticated users

dandiapi/api/views/asset.py, dandiapi/settings.py
=> Revert rate limiting of asset list endpoint

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Closes #1891
The existing asset list endpoint is inefficient with how it queries the database, resulting in unnecessarily long response times from that endpoint. This is improved in the following ways:
* Paginate and fetch IDs of desired assets first, before doing left joins
* Remove duplicate queries as a result of class inheritance
* Remove extra query in `raise_if_unauthorized` method
The results of these improvements are shown below. Note that these are the times for the SQL queries themselves, not the overall page load, as that can be inflated by the amount of data returned, and isn't useful for this discussion.
| Operation | Original (ms) | Improved (ms) | Speedup |
| --- | --- | --- | --- |
| No filters | 300 | 30 | 10x |
| Ordering only | 295 | 92 | 3.2x |
| Path filter only | 235 …
=> Optimize asset list endpoint

dandiapi/api/tests/test_pagination.py, dandiapi/api/views/asset.py, dandiapi/api/views/common.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/pagination.py, dandiapi/api/views/version.py, dandiapi/settings.py, dandiapi/zarr/views/__init__.py
Currently regardless of which page from a paginated endpoint is fetched, we return the count of the _entire_ queryset, which requires a full table scan. This is a problem for endpoints where optimization is key, since regardless of how efficient you structure the database queries, you'll always scan the _entire_ table to get the total number of objects that match query.
This can be wildly inefficient for queries with a large result set. If, for example, you were to list the assets from a dandiset containing 50k assets and page through them 100 at a time, you'd be making 500 requests, and for every request would scan the _entire_ table to count all of these assets, even though you're only fetching 100.
To fix this behavior, this PR introduces a few new pagination related classes. Since the …
=> Only include total count in the first page of list views

web/src/views/DandisetLandingView/DownloadDialog.vue
@dandi/archive-maintainers is there an easy way to avoid hardcoding dandi-cli version here and take it from `cli-minimal-version` of https://github.com/dandi/dandi-archive/blob/HEAD/dandiapi/api/views/info.py#L65 ?
Change is "inspired" by a user who pointed me to that line which didn't work on his mac with OSX having python 3.7 systemwide
=> Update our instructions for installation to state newer versions of python and dandi-cli

dandiapi/api/management/commands/migrate_published_version_metadata.py
Ruff [`0.4.2`](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#042) updates the `blind-except (BLE001)` rule to not trigger if an exception is raised from within the blind exception `except` block. 
This may still error locally if you have an older version of ruff, so I would recommend upgrading.
=> Remove unnecessary `noqa` directive

.autorc
This plugin is causing our release workflow to fail, and we don't use it anyway.
=> Remove all-contributors auto plugin

web/README.md
When https://github.com/dandi/dandi-archive/pull/1725 was merged, the name of the server downtime env var was never changed in `web/README.md`. This PR fixes that.
=> Fix documentation for server downtime message var

web/src/views/FileBrowserView/FileBrowser.vue
Provides a neurosift external service button for .nwb.lindi.json files.
Also changes https://flatironinstitute.github.io/neurosift -> https://neurosift.app (note that currently github io gets redirected, so both work right now)
Example on staging site:
https://gui-staging.dandiarchive.org/dandiset/213569/draft/files?location=000946%2Fsub-BH494&page=1
[Link to LINDI project](https://github.com/neurodataWithoutBorders/lindi)
See discussion here: https://github.com/NeurodataWithoutBorders/lindi/pull/42
=> neurosift external service for .nwb.lindi.json

dandiapi/api/storage.py, setup.py
and caused .config to become None
and I believe that caused our tests to start failing etc
If tests succeed, Closes #1940
=> In 1.14.3 it became client_config and .config was announced deprecated

dandiapi/api/tests/test_pagination.py, dandiapi/api/views/asset.py, dandiapi/api/views/pagination.py
Fixes #1917
#1911 greedily implemented the custom pagination class (not including `count` in every page of the paginated response) for every listing endpoint. In reality, the main target of that PR was the asset list endpoint. Since there are various places in the web client that assume the removed `count` field is present, this PR reverts the functionality for all list endpoints except for the asset list endpoint.
=> Only use custom pagination class for asset list endpoint

dandiapi/api/tasks/__init__.py
The `asset_blob` could potentially change out from under us in the time it takes to calculate the SHA256, so using an UPDATE here is safer.
=> Fix race condition in sha256 calculation task

dandiapi/api/models/dandiset.py, dandiapi/api/models/version.py, dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/version/metadata.py, dandiapi/api/tests/factories.py, dandiapi/api/tests/test_version.py
Closes #1787
Closes #1831
It seems both these issues were due to us not prohibiting the `access` field from being updated. A user should never update the `access` field (as it is derived from the embargo status of the dandiset), nor is there a natural way for that to happen using the meditor. However, it was not actually disallowed in anyway, so the following situations were possible:
1. After the dandiset is embargoed, if the meditor uses old metadata in some way, it can overwrite this field with the old embargoed access field. All without the user being aware, since that field isn't available in the meditor
2. If someone were to simply use the API outside of the meditor, they could set that field to whatever they want, intentional or not.
~This PR updates that field to treat it as …
=> Restrict updates to metadata `access` field

dandiapi/api/mail.py, dandiapi/api/migrations/0008_migrate_embargoed_data.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/dandiset/exceptions.py, dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/embargo/exceptions.py, dandiapi/api/services/publish/__init__.py, dandiapi/api/tasks/scheduled.py, dandiapi/api/templates/api/mail/dandiset_unembargoed.html, dandiapi/api/templates/api/mail/dandisets_to_unembargo.txt, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_unembargo.py, dandiapi/api/tests/test_upload.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/upload.py, dandiapi/api/views/version.py, doc/design/embargo-redesign.md, web/src/views/DandisetLandingView/DandisetUnembargo.vue
This change will help prevent race conditions that could arise if modifications are allowed while un-embargo is ongoing.
=> Lock dandisets during un-embargo

setup.py
`django-storages` and `dandischema` have new versions out that are now being installed and are causing tests to fail. This PR pins these to bring master back to normal.
=> Pin updated dependencies

dandiapi/api/tests/factories.py, setup.py, web/src/components/Meditor/types.ts
Depends on #1977
Fixes #1975
With this schema version upgrade, the meditor was failing to show certain fields. The reason for the breaking logic was due to a change in #1823 ([dd2c7b32](https://github.com/dandi/dandi-archive/commit/dd2c7b32ddea5984ee2b876f6b8aba8e6ce2e010)). The underlying reason for this logic was fixed with the new version of the schema (`0.6.8`), and so that code was no longer necessary.
=> Bump dandischema to 0.10.2 (schema version 0.6.8)

dandiapi/api/templates/dashboard/base.html, dandiapi/api/views/__init__.py, dandiapi/api/views/dashboard.py, dandiapi/urls.py
This is needed to automate a somewhat tricky process when done by hand. The resulting CSV can be used to import the users to a Mailchimp account in order to keep the Mailchimp audience accurate when sending (infrequent) mass emails.
=> Add dashboard link to view to emit user list as Mailchimp-compatible CSV

dandiapi/api/tasks/__init__.py
=> Add retries to sha256 checksum calculation task

dandiapi/api/services/asset/__init__.py, dandiapi/api/tests/test_asset.py
Depends on #1886 
As a part of the audit backend PR, I noticed that we do something peculiar in the `change_asset` service layer function, which required an undesirable workaround for audit. The `change_asset` function at its core just calls `remove_asset_from_version` and `add_asset_to_version` sequentially. This achieves the desired outcome, but with the following downsides:
1. Each service layer function (including `change_asset`) contains its own set of checks and filters to ensure the asset being created/modified/destroyed is not malformed. This is largely similar between the services, but they each differ slightly. So when `remove_asset_from_version` and `add_asset_to_version` are called from `change_asset`, they are each making checks that were already made in `change_asset`, …
=> Separate core model logic from top-level asset service layer functions

dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_unembargo.py
This addresses what I believe to be the cause of https://github.com/dandi/helpdesk/issues/158. Previously, when a dandiset was unembargo, we re-populated the version metadata but never validated it. This is in contrast to the normal flow of updating a version, which sets its status to `PENDING` and is eventually validated.
Now, this is performed inline as a part of unembargo.
@danlamanna Curious about your thoughts on my changes and additional test for `validate_version_metadata`. Previously, we assumed that versions with a status besides `PENDING` were passed into the function correctly, and were concurrently modified, changing the status. However, the function could easily be called mistakenly with a different version status, and so I think the log message should be updated to reflect …
=> Re-validate version metadata during unembargo

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
Fixes #1996
I also included a slight formatting / structural change of the `raise_if_unauthorized` function, since there was several nested if statements with no else statements.
=> Fix admin access to embargoed asset blobs

web/src/views/FileBrowserView/FileBrowser.vue
This is a small change to add an "Open With -> Neurosift" entry for .avi files.
DANDI supports uploading of .avi files, but currently there is no way to preview/stream those files in the browser (browsers do not support AVI).
Neurosift now provides a workaround by using Dendro to precompute .mp4 files associated with portions of the .avi files.
For example:
https://dandiarchive.org/dandiset/001084/draft/files?location=sub-DL18%2Fsub-DL18_ses-211110_image%2Bophys&page=1
With this PR you would be able to "Open With" Neurosift and be directed to
https://neurosift.app/?p=/avi&url=https://api.dandiarchive.org/api/assets/3d760886-c1ac-467d-bd87-3dfd71a5cb65/download/&dandisetId=001084&dandisetVersion=draft
At that link, you should be able to view the first X minutes of that video because the …
=> Add Neurosift service for AVI files

dandiapi/analytics/tests/test_download_counts.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_asset_paths.py, dandiapi/api/tests/test_audit.py, dandiapi/api/tests/test_auth.py, dandiapi/api/tests/test_create_dev_dandiset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_embargo.py, dandiapi/api/tests/test_garbage.py, dandiapi/api/tests/test_manifests.py, dandiapi/api/tests/test_pagination.py, dandiapi/api/tests/test_permission.py, dandiapi/api/tests/test_search.py, dandiapi/api/tests/test_stats.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_unembargo.py, dandiapi/api/tests/test_upload.py, dandiapi/api/tests/test_users.py, dandiapi/api/tests/test_version.py, dandiapi/conftest.py, dandiapi/search/tests/test_permissions.py, dandiapi/search/tests/test_views.py, dandiapi/zarr/tests/test_zarr.py, dandiapi/zarr/tests/test_zarr_upload.py
Applies new `ruff` rules to the codebase. See https://astral.sh/blog/ruff-v0.6.0 for info on all changes. It seems the only change applicable to us is the changes to `PT001` and `PT023`.
This will fix the failing CI on `master` and PRs like #2008.
=> Apply new `ruff` rules

dandiapi/api/tests/test_upload.py, dandiapi/api/views/upload.py
Fixes #1920 
The existing upload pathway has a race condition where a competing asset blob gets created after our check. The `select_for_update` doesn't lock anything if it can't find any existing rows. Using [get_or_create](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#get-or-create) should handle this edge case. Even though we still need to handle these conditions, I'm curious why clients are concurrently uploading identical blobs :man_shrugging:.
I haven't tested this locally yet, but it's probably worth a sanity check already.
=> Respond with 409 when creating duplicate asset blobs

dandiapi/api/admin.py
ATM shows only blobs, so to get to zarr requires 2 clicks. As long as we have zarr as valuable as blob, we better list both.
Having said that, I do not feel strongly about it yet, so feel free to quickly close if you feel we better keep it just to blobs for now.
=> admin view: Also show (list) zarr for Assets view

dandiapi/settings.py
This is just codifying the current behavior so that celery will stop complaining about the setting changing in the future.
=> Manually configure celery to retry connections on startup

.gitignore, web/src/components/FileBrowser/FileUploadInstructions.vue, web/src/views/DandisetLandingView/DownloadDialog.vue
When using `gui-staging.dandiarchive.org`, a minor inconsistency was observed where the CLI command was incorrect.
This PR makes a simple fix to render the appropriate text depending on if the user is using staging or production.
Closes #1553 
Cc @kabilar
=> For staging environment, include dynamic text for `dandi download` command

web/src/views/FileBrowserView/FileBrowser.vue
This small update enables external Neurosift links for assets with the .nwb.lindi.tar file extension. Support for the .nwb.lindi.json extension was previously added in #1922.
**Background**
For more information on the purpose of lindi, and why both .lindi.json and .lindi.tar extensions are necessary, please refer to the [Lindi repository](https://github.com/neurodataWithoutBorders/lindi).
**Next Steps**
Currently, I plan to upload lindi files only to the staging site, as Lindi is not yet officially supported. Over the coming weeks, I will be working on making a case for future DANDI support, and look forward to discussion on the topic. I know there are issues about avoiding broken references.
In the meantime, having this menu option functional would be highly beneficial to me. …
=> add external neurosift service for .nwb.lindi.tar

dandiapi/api/views/asset.py
"Update" (or "change", both words are used, see blow) IMHO implies in-place operations which is not the case here: if metadata is different, we get a new asset returned, hence there is really no "update" to an existing asset, but rather CoW style of operation on an asset upon change. 
To be frank: there is a notion of "update" as the new created asset is assigned to the same dandiset, hence it is replacing previous asset present in the dandiset. But as we are talking about a new asset object with new asset id, I think it is important to get the only visible API documentation "straight".
```shell
❯ git grep '\(change\|update\)_asset\>' -- dandiapi | grep -v test_
dandiapi/api/migrations/0010_auditrecord.py:                            ('update_asset', 'update_asset'), …
```
=> ../assets/{asset_id}/ PUT: clarify that new asset is created

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py
Determine emptiness of Dandisets based on emptiness of the newest Version contained within it. See https://github.com/dandi/dandi-archive/issues/1992#issuecomment-2307802787 and the commit message at https://github.com/dandi/dandi-archive/commit/002466ad11b4fce3ec03c111529a35944ce51677 for details.
Closes #1992.
=> Fix Dandiset emptiness detection logic

.codespellrc, dandiapi/api/management/commands/calculate_sha256.py
Added ability to specify either blob id (where it applies) or asset id since that is the id we typically know for which a blob lacks sha256.
Refs:
- https://github.com/dandi/dandi-archive/issues/471
- https://github.com/dandi/dandi-archive/issues/1578
- #1937 
has a chance to properly address the underlying issue but IMHO having an interface to trigger such a task manually could still be valuable e.g. in case of that automation failing to perform for some reason etc.
=> Add calculate_sha256 management command to trigger (re)computation for a blob

.github/workflows/cli-integration.yml
Otherwise, since limiting is done per IP and we do not know where requests would be coming from to the docker hub, we could get
```
#3 [auth] library/python:pull token for registry-1.docker.io
#3 DONE 0.0s
#2 [internal] load metadata for docker.io/library/python:3.11-slim
#2 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/python/manifests/sha256:5501a4fe605abe24de87c2f3d6cf9fd760354416a0cad0296cf284fddcdca9e2: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
------
> [internal] load metadata for docker.io/library/python:3.11-slim:
------
django-public.Dockerfile:1 …
```
=> Do login into docker hub so we could reliably build our docker image

.github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml
This is currently resulting in deploy failures to staging, and will also impact production the next time a deploy happens there. https://github.com/dandi/dandi-archive/actions/runs/11349812410
GitHub Actions' switch to Ubuntu 24.04 breaks the deploy workflows. We currently use `pip` to install the `build` package prior to packaging the `dandiapi` sdist. But, we do not explicitly install the Python runtime before doing this. It looks `pip` was available on the default Ubuntu 22.04 runners, but not 24.04, so this was basically working by accident before.
=> Explicitly install Python in CD workflows

dandiapi/api/management/commands/extract_metadata.py, setup.py
=> Add command for asset metadata re-extraction

.github/workflows/auto-add-issues.yml, .github/workflows/backend-ci.yml, .github/workflows/backend-production-deploy.yml, .github/workflows/backend-staging-deploy.yml, .github/workflows/cli-integration.yml, .github/workflows/frontend-ci.yml, .github/workflows/release.yml
`ubuntu-latest` upgraded to 24.04 recently, causing breakages in some builds. This PR generalizes #2042 to make that change universal in all CI jobs.
The linting failure will be fixed by #2053.
=> Pin ubuntu-22.04 for all CI jobs

tox.ini
Since ruff is fast moving and freely publishes [new versions with breaking changes](https://docs.astral.sh/ruff/versioning/), it behooves us to pin a ruff version so that local dev and CI don't go out of sync with each other, complicating the review process for PRs.
This PR pins ruff to the 0.6.x minor series and adds a version report to each test (to make version numbers easier to determine in the future).
(See commit messages for details.)
=> Pin ruff version to avoid spurious test failures

dandiapi/api/templates/api/account/questionnaire_form.html, dandiapi/api/views/auth.py
=> Update new user registration questions

dandiapi/api/tests/test_dandiset.py, web/src/views/DandisetLandingView/DandisetLandingView.vue
Fixes #1350
The following is now displayed when an embargoed dandiset that the current user is not an owner on is accessed.
=> Display message in GUI when accessing embargoed dandiset

CHANGELOG.md, web/src/views/DandisetLandingView/DandisetActions.vue, web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
Addresses #2039 
This doesn't yet include any of the general framework proposed by @yarikoptic in #2039. I do agree with what you are describing there, so we can view this as step 1 toward that. Whether it gets merged as is first or whether we wait until it is generalized that of course is up to you guys. I can work on it futher, but it will take me time to become more familiar with how data are passed around in the application.
=> Add neurosift external service for dandisets

web/src/stores/dandiset.ts, web/src/views/DandisetLandingView/DandisetLandingView.vue
Fixes #1350
Follow on to #2060
It turns out the change I made to display "access denied" to embargoed dandisets didn't properly handle all cases of that access. This led to the display of "Dandiset does not exist" on dandisets that did exist, but were embargoed.
=> Fix display of embargoed dandiset error page in GUI

dandiapi/api/doi.py, dandiapi/api/views/upload.py
Most of the other submodules already used a dedicated logger. I have just identifier where root  logging.  was still used and similarly established loggers based on the files __name__ which should include the path starting with dandiapi. happen someone needs tighter control over logging of the application
=> Use a dedicated logger. not top level logging. module

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py, web/src/rest.ts, web/src/types/index.ts, web/src/views/DandisetLandingView/DandisetUnembargo.vue
Recently we've had several instances of a dandiset unembargo being blocked by incomplete/active uploads. Most of the time, these uploads are junk and the owners simply wish to clear them, which requires admin intervention. This PR adds the API and Vue client support for users to list and delete these lingering uploads themselves.
Here is a video of the new UI.
https://github.com/user-attachments/assets/6033cd6b-9b10-4c8d-96e1-f85ea3df2598
=> Add incomplete upload dialog to DLP when unembargo is blocked

dandiapi/api/services/metadata/__init__.py, dandiapi/api/tests/test_tasks.py
As documented in #1814, we receive the following validation error on the web application when uploading only Zarr asset(s) to a Dandiset (and not blobs):
```
assetsSummary: A Dandiset containing no files or zero bytes is not publishable
```
The error is raised from `dandi-schema` when a validation check occurs on the `assetSummary` field in the `dandiset.yaml`.  See the [models module](https://github.com/dandi/dandi-schema/blob/bdb7dd681435f1092814041eb01eb4fabe87bf57/dandischema/models.py#L1495-L1501):
```python
@validator("assetsSummary")
def check_filesbytes(cls, values: AssetsSummary) -> AssetsSummary:
if values.numberOfBytes == 0 or values.numberOfFiles == 0:
raise ValueError(
"A Dandiset containing no files or zero bytes is not publishable"
)
return values
```
And it arises because …
=> Fix validation error when only Zarr assets are uploaded

web/package.json, web/src/views/DandisetLandingView/DandisetLandingView.vue
Currently, linting warnings emitted by `eslint` don't cause a CI failure. This is why we see the "Unchanged files with check annotations" on new PRs like this one https://github.com/dandi/dandi-archive/pull/2062/files#annotation_29329773434
Setting `--max-warnings` to zero will make the CI fail if there are any linting warnings.
=> Set `--max-warnings` to zero for `eslint`

web/src/views/DandisetLandingView/DandisetActions.vue
Closes #2094
A trivial PR. Seems to work locally I see
and then for OPEN
NB error is there even on master, I didn't dig in.
=> DLP: Have "Cite as" only for OPEN (non embargoed) dandisets

.github/workflows/cli-integration.yml
and which FAILed or PASSed.  Just now realized that we do not run in verbose mode so cannot `grep` for specific test in the logs collected by tinuous for the past
=> ENH: run pytest  against dandi-cli with -v to see which tests ran

DEVELOPMENT.md
Re-opening #2105 from @candleindark using a `dandi/dandi-archive` branch so that CI works correctly
=> doc: update instruction to natively(locally) run Celery service

.pre-commit-config.yaml, DEVELOPMENT.md, dev/django.Dockerfile, setup.py, tox.ini
This extends #2045 to use the same pre-commit hooks to perform linting and formatting via tox.ini. In particular, this "refactors" the specification of what versions of codespell and ruff to use to just one place: the pre-commit config file.
The variants of the pre-commit hooks that are needed to replace the tox.ini commands are listed in the pre-commit config using the `manual` stage specifier with appropriate aliases, meaning they will not be invoked as a git hook ever, and enabling them to be invoked by name in the tox config.
This PR also modifies the dev Dockerfile to build it to run as the user from the host system. That is, instead of running as root inside the container, it will instead run as the same (non-root) user who is doing development work (including building this …
=> Use pre-commit hooks in tox configuration

dandiapi/api/doi.py, dandiapi/api/tasks/__init__.py, dandiapi/api/tasks/scheduled.py
While troubleshooting
- https://github.com/dandi/dandi-cli/issues/1488
I would like to know if any of those tasks was ran at all.  That is conditioned on correct condition to happen first, so it is valuable to add explicit debug level log entry if condition was not met
To be used along with
- #2078 
which makes logging level configurable
=> Add some .debug level messages in tasks upon no action to be performed

web/README.md
This PR updates the instructions for serving the web app, the frontend, through a development server.
=> Update instructions for serving the web app through a development server

dandiapi/zarr/tasks/__init__.py, dandiapi/zarr/tests/factories.py, dandiapi/zarr/tests/test_ingest_zarr_archive.py
Closes #2091
@mvandenburgh The last commit fixes some zarr tests that didn't have a draft version associated with their dandiset, due the chain of `SubFactory` definitions. I originally tried to fix this on the `DandisetFactory` class itself, so that all dandisets generated in this way would always have a draft version, but that proved troublesome. For now, I've settled for just fixing the zarr tests.
=> Set version status to PENDING in ingest_zarr_archive

web/src/components/DLP/OverviewTab.vue
The `MetadataCard` component wraps its contents in a `v-row` and `v-col`, which adds some additional padding around the card. The "Contributors" card, however, is the only DLP card that doesn't use the `MetadataCard` component. Prior to this change, the "Contributors" card didn't use `v-row` and `v-col`, so it didn't have the same padding as the other cards.
=> Fix inconsistent padding on Contributors card in DLP

.github/workflows/cli-integration.yml
I think this could be the only solution (may be besides also adding retries in addition) to allow testing against dandi-cli to be done also in PRs from forks of the project, where there is no credentials.  We could also advise our developers to provide such (own) credentials in their forks.
FTR: login originally was added in 6b815dc6aabf33aebf846aa56b67fb952e13bc77
- I think we can state that it closes https://github.com/dandi/dandi-archive/issues/2107 . If it fails to pull from docker -- it would be a differently titled issue ;-)
- note: this PR submitted from a personal fork, so would test ability to pass for similar ones
=> Login to docker hub only if credentials were provided

web/src/components/DLP/OverviewTab.vue
Closes #2071
There seems to be a little design gotcha -- a space from prior section which I do not know framework well enough to see where to add anything to make it not indent itself.
=> DLP: Add "Protocols" card

dandiapi/api/admin.py
This adds the `github_username` field to the list of searchable fields in the `User` admin console.
=> Enable User search by GitHub username

dandiapi/api/services/embargo/__init__.py, dandiapi/api/tests/test_unembargo.py
This addresses the effects of #2116. Currently, without this change, every asset of a previously unembargoed dandiset can be left with the validation error `An embargo end date is required for NIH awards to be in compliance with NIH resource sharing policy.`. Now, when a dandiset is unembargoed, all assets will be set to `PENDING` status, so that their metadata can be re-validated.
=> Set assets to pending during unembargo

web/src/components/DLP/OverviewTab.vue, web/src/views/DandisetLandingView/DandisetPublish.vue, web/src/views/DandisetLandingView/DandisetUnembargo.vue, web/src/views/DandisetLandingView/DandisetValidationErrors.vue
Fixes #2089.
We currently don't display validation errors on the DLP for embargoed dandisets. This seems to be an oversight due to much of the UI being duplicated between the `DandisetPublish` and `DandisetUnembargo` components. I've taken an initial stab at refactoring some of the duplicate templates into a reusable component in this PR, but we could probably clean it up a bit more. 
The text displayed when the Assets Summary is missing (`This Dandiset does not contain any assets.`) is also slightly misleading. A dandiset that contains _only invalid assets_ will also not have an Assets Summary; I've updated that text to reflect that.
=> Display validation errors on DLP for embargoed dandisets

dandiapi/api/mail.py, dandiapi/api/management/commands/extract_metadata.py, dandiapi/api/models/dandiset.py, dandiapi/api/services/asset/__init__.py, dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/embargo/__init__.py, dandiapi/api/services/permissions/dandiset.py, dandiapi/api/services/publish/__init__.py, dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_audit.py, dandiapi/api/tests/test_create_dev_dandiset.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_tasks.py, dandiapi/api/tests/test_unembargo.py, dandiapi/api/tests/test_upload.py, dandiapi/api/tests/test_version.py, dandiapi/api/views/asset.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/upload.py, dandiapi/api/views/version.py, dandiapi/search/models.py, dandiapi/zarr/tests/test_ingest_zarr_archive.py, dandiapi/zarr/tests/test_zarr.py, dandiapi/zarr/tests/test_zarr_upload.py, dandiapi/zarr/views/__init__.py
The goal of this PR is to abstract most of the use of `django-guardian` into the permissions service layer, instead exposing functions that achieve the same effect. This has the following benefits:
1. Consolidates permission logic in the application, most notably used in endpoints.
2. Allows for easier modification or extension of our permissions logic.
One notable use case for this is forks of the codebase that may need to modify how permissions are done (e.g. LINC). This refactor and consolidation makes that much easier, as everything can be easily found in one file. cc @aaronkanzer.
=> Create permissions service layer

web/src/views/DandisetLandingView/DandisetLandingView.vue
Fixes #2081
This PR adds a `key` to the `Meditor` component consisting of the currently selected dandiset identifier and version. This will result in the meditor re-rendering when the user selects a new version, fixing the issue in #2081.
I initially attempted to fix this by making the `editorInterface` variable properly reactive (https://github.com/dandi/dandi-archive/commit/62f2bb2ce2bb01858331a050197bd4486fd76f7b), but that ended up breaking a bunch of other things in the meditor. Eventually after fixing a long trail of new bugs, I ran into this issue again https://github.com/dandi/dandi-archive/blob/master/web/src/components/Meditor/state.ts#L4-L7 and got stuck.
I think this code could use a refactor to be less brittle and fix whatever bizarre reactivity bug is going on with the …
=> Fix reactivity bug in meditor

dandiapi/api/tests/test_dandiset.py, dandiapi/api/views/serializers.py
On any endpoint that used `DandisetDetailSerializer` for its response, the dandiset information was being included twice. Once at the top level, and once nested under each nested version serializer (`draft_version` and `most_recent_published_version`).
=> Prevent duplicate serialization of dandiset in detail view

web/src/components/DandiFooter.vue
minor.  I would merge Monday if nobody does it before or says we must not do it.
Ideally, at somepoint, we might just want to automate that value based on the year of the last commit in the codebase.
=> Move to 2025 from 2024 in the footer

README.md, dandiapi/api/templates/api/mail/approved_user_message.txt, dandiapi/api/templates/api/mail/registered_message.txt, dandiapi/api/templates/api/mail/rejected_user_message.txt, web/src/components/FileBrowser/FileUploadInstructions.vue, web/src/utils/constants.ts, web/src/views/CreateDandisetView/CreateDandisetView.vue, web/src/views/DandisetLandingView/DownloadDialog.vue
=> Update URL for DANDI Docs

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py, dandiapi/api/views/serializers.py, web/src/views/DandisetLandingView/DandisetPublish.vue
Closes #2149
This PR adds a simple `zarr` boolean query param to the `/assets` endpoint, and updates the client to use that endpoint when checking for zarrs in a dandiset (to prevent publishing of zarrs).
=> Check if dandiset contains zarr assets using asset list endpoint

.git-blame-ignore-revs
For motivation/details, see also:
- https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame
- https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
=> Add .git-blame-ignore-revs to improve blame view

web/src/components/DandisetsPage.vue
The existing icons for sorting on any dandiset list page is backwards of what you'd expect (arrow pointing up is actually "descending"). This PR fixes that.
=> Fix dandiset ordering icons, default to descending

web/src/components/DandiFooter.vue
I felt odd when saw 2024 back online, while seeing #2144 merged and released.  It also took a bit to track it down since apparently `git log -p` does not show merges, and here I believe it happened in #2135 while resolving conflict merges in 700abad2c5f3ae28cb32ce8bc1099a3501347c5d .
See
git diff 700abad2c5f3ae28cb32ce8bc1099a3501347c5d^2..700abad2c5f3ae28cb32ce8bc1099a3501347c5d -- web/src/components/DandiFooter.vue
To at least partially assist and annotate merges which were problematic and how, I have in my `~/.gitconfig`
```
[merge]
summary = true
log = true
```
and then when I do merge locally I get commented out section listing conflicted files, which I uncomment and add description on why conflict and how was handled. See e.g. …
=> Boost us back to 2025 in the footer after having it lost during merge conflict resolving

CHANGELOG.md, web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue, web/src/views/FileBrowserView/FileBrowser.vue
Neurosift has been updated to v2, and with this update, the URL specification has changed slightly. The old URLs still work, but they redirect to the new ones. It would be best to have DANDI use the new URL scheme for the external links.
For example, for a dandiset:
old:
https://neurosift.app/?p=/dandiset&dandisetId=001335&dandisetVersion=draft
new:
https://neurosift.app/dandiset/001335?dandisetVersion=draft
And for an NWB file:
old:
https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/7d5046f1-12b5-4b88-9ccf-9e738f265652/download/&dandisetId=000409&dandisetVersion=draft
new:
https://neurosift.app/nwb?url=https://api.dandiarchive.org/api/assets/7d5046f1-12b5-4b88-9ccf-9e738f265652/download/&dandisetId=000409&dandisetVersion=draft
For an AVI file, this is not (yet) …
=> Adjust Neurosift external URLs for v2 of Neurosift

dandiapi/api/services/exceptions.py
Currently, if no values are provided for these fields when subclassed, an exception is raised here, due to the values not being set at all:
https://github.com/dandi/dandi-archive/blob/830f034fcb6d7f912b4d7f0d11d366143c9e3219/dandiapi/api/services/exceptions.py#L13
Since these field are optional (union-ed with `None`), this PR simply sets those values to `None` as a default.
=> Set default values for optional DandiError fields

dandiapi/api/views/serializers.py
Despite the fact that the `/dandisets` endpoint accepts a query parameter `search` that is used to filter by the search terms, the parameter is not listed in the input serializer, and thus does not show up in the Swagger docs.
I built and tested this locally and it seems to work as expected.
Fixed #2214.
=> Add search query parameter to dandiset list endpoint serializer

dandiapi/zarr/views/__init__.py
This needs to lock, otherwise an ingestion could trigger in between fetching the zarr object and changing it to UPLOADED.
=> Remove TODO for locking zarr finalizing

web/vite.config.mts
This was removed inadvertently in the Vue 3 upgrade (#2186)
=> Add version string back into frontend

dev/.env.docker-compose, dev/.env.docker-compose-native
Following from #2205, it seems the values supplied in the dev `.env` files contain quotes around them, which could cause errors when running the app locally, depending on the local environment. This is the only place this quoting occurs, which is why CI doesn't catch it.
=> Remove quotes on DANDI_ADMIN_EMAIL env var

web/eslint.config.js, web/src/components/DLP/AccessInformationTab.vue, web/src/components/DLP/AssetSummaryTab.vue, web/src/components/DLP/ContributorsTab.vue, web/src/components/DLP/DandisetOwnersDialog.vue, web/src/components/DLP/MetadataCard.vue, web/src/components/DLP/RelatedResourcesTab.vue, web/src/components/DLP/SubjectMatterTab.vue, web/src/components/DandiFooter.vue, web/src/components/DandisetList.vue, web/src/components/DandisetSearchField.vue, web/src/components/DandisetsPage.vue, web/src/views/DandisetLandingView/DandisetMain.vue, web/src/views/DandisetLandingView/DandisetSidebar.vue
All of our Vue components have been converted to TS/Composition API, but not all of them use `script setup`. 
This PR updates all those outstanding components, and also cleans up some unused variables that got detected by the better static analysis tooling that comes along with using `script setup`.
=> Convert remaining Vue components to `<script setup>` syntax

web/netlify.toml
This adds a configuration block for use with [branch deploys](https://docs.netlify.com/site-deploys/overview/#branch-deploys-versus-deploy-previews). We don't have any branch deploys set up now, but they have been useful in the past (e.g., during development of #2212).
The configuration is identical to that of deploy previews.
=> Add Netlify configuration for branch deploys

dandiapi/api/services/audit/__init__.py
This enables us to omit the user parameter for audit actions when they occur as part of some administrative action (e.g., a bulk updating of incorrect metadata). A null `user` is only allowed with `admin` set to True, in which case blank values are used for the `username`, `email`, and `fullname` parameters of the `AuditRecord` that is created.
This is needed for the changes in #2225 to function properly.
=> Allow null `user` when `admin` is True

web/src/App.vue
Currently, we explicitly catch any javascript exceptions that occur during (1) fetching of the schema and (2) refreshing the user's oauth login. We do this so that we can set a boolean that causes the "Connection to server failed" string to get rendered in case the API request fails (or, github.com in the case of the schema fetching). However, we never re-raise the exception after catching it, so it is effectively suppressed and does not propagate to Sentry.
=> Don't suppress exceptions when fetching schema/logging in

web/src/views/FileBrowserView/FileBrowser.vue
Fixes #2256
The issue was that the click event on the `v-btn` (line 191) was propagating up to the parent `v-list-item` (line 117), and causing `openItem` to get called which resulted in the page transition instead of opening a new tab.
=> Fix "View asset metadata" link

web/src/components/CookieBanner.vue
Fixes #2247
Using `position: fixed;` without explicitly setting a `z-index` greater than zero results in some elements appearing on top of the `v-card` (see #2247).
=> Fix z-index of cookie banner

web/src/components/DLP/DandisetOwnersDialog.vue
Fixes #2255
Switches the button to use flexbox + `align-items: center` to ensure the child text is vertically centered within the button.
=> Fix alignment issue with Manage Owners button

web/src/components/StarButton.vue
Fixes #2245 
The `readonly` prop to `v-btn` also disables the button like `disabled` does, but without changing the style.
=> Fix star button disabled halo issue

.gitignore
These files are autogenerated by `celery beat` and should not be tracked in version control.
=> Add `celerybeat-schedule*` files to .gitignore

web/src/components/DandisetSearchField.vue
Fixes #2248
The `label` prop incorrectly behaves as a `placeholder` in the Vuetify 2 `v-text-field` component. Vuetify 3 changes it and makes `label` behave correctly, so we need to use `placeholder` instead.
=> Use `placeholder` instead of `label` for dandiset search bar

web/src/components/DandisetsPage.vue
Fixes #2249
Fixes #2289
Before:
After:
=> Fix v-switch margins and color

dandiapi/api/services/publish/__init__.py, dandiapi/api/tests/test_version.py
There's an edge case where assets can be uploaded and the dandiset can transition into publishing before an appropriate asset summary for the draft version is computed. When generating the asset summary for the published version it can be copied to the draft to ensure the draft asset summary is always eventually correct.
=> Fix a case where draft asset summaries could become stale

web/src/components/StarButton.vue, web/src/views/DandisetLandingView/DandisetMain.vue
fix #2188 
Cline-assisted
[cline_task_apr-6-2025_11-54-10-am.md](https://github.com/user-attachments/files/19622941/cline_task_apr-6-2025_11-54-10-am.md)
=> Refactor StarButton layout and improve alignment in DandisetMain view

dandiapi/api/views/dandiset.py
Fixes #2000 
The `users` endpoint for the Dandiset View now uses [select_for_update](https://docs.djangoproject.com/en/5.1/ref/models/querysets/#select-for-update). This prevents accidentally saving stale data when calleding `dandiset.save()`.
=> Lock dandiset when changing owners

dandiapi/api/tests/test_garbage_collection.py
@mvandenburgh Just putting this out there as a proposal since I didn't dig into any of the underlying code. This test takes ~1 minute on my machine with the existing chunk size of 1000. This reduces it to under a second.
=> Mock GC event chunk size during testing

dandiapi/api/manifests.py, dandiapi/api/services/metadata/__init__.py
Determining whether a zarr is embargoed requires querying the dandiset which could result in n+1 queries.
=> Remove n+1 queries from Asset.full_metadata

e2e/tests/meditor.spec.ts, web/src/components/Meditor/Meditor.vue, web/src/components/Meditor/utils.ts
Fixes #2281 
We do not currently feed the entire complex model and schema into VJSF for validation. Instead, we only pass a single sub-model and schema into VJSF when it has been selected by the "Edit" button; this is done for UI/UX purposes to avoid rendering every single item in a list as a form at once, as we used to do before the Meditor redesign a few years ago. 
Take this screenshot of the contributors view in the meditor of https://gui-staging.dandiarchive.org/dandiset/200017/draft, for example -
The left hand side of the modal is the VJSF component, while the right hand side is a custom component that uses `vue-draggable` to enable the user to manipulate the ordering of the contributors. We do not pass the full `contributor` array to VJSF ( [this …
=> Fix validation issue with vue/vjsf 3

doc/design/deployment-1.md
Inspired by @mvandenburgh removing a label in  https://github.com/dandi/dandi-archive/pull/2241#issuecomment-2776759964 .
We do have
"onlyPublishWithReleaseLabel": true
in the https://github.com/dandi/dandi-archive/blob/HEAD/.autorc . So there would be no release unless "release" label is added. All PRs ideally should be annotated with the appropriate labels for the changelog sectioning. See e.g. https://github.com/dandi/dandi-cli/blob/master/CHANGELOG.md#0670-mon-mar-03-2025 and other changelog entries there for how sectioning would look, and compare to current https://github.com/dandi/dandi-archive/blob/master/CHANGELOG.md where all changes are "Bug Fix" and only rarely appropriately annotated like in https://github.com/dandi/dandi-archive/blob/master/CHANGELOG.md#v040-mon-dec-16-2024 …
=> DOC: fixup description of the interaction with auto for releases based on labels

setup.py
In #2320 we un-pinned `django-oauth-toolkit`, but in reality it's an backward incompatible change, because the `ClientSecretField` model was added in `v2.0`, which results in an error-ed migration if not on `2.0+`. This pins that package version to `>2`.
=> Require minimum version of 2.0 for django-oauth-toolkit

dandiapi/urls.py
Typically a Resonant app will serve the redoc and swagger UI at `/api/docs/{swagger|redoc}` (see [cookiecutter](https://github.com/kitware-resonant/cookiecutter-resonant/blob/master/%7B%7B%20cookiecutter.project_slug%20%7D%7D/%7B%7B%20cookiecutter.pkg_name%20%7D%7D/urls.py#L33-L34)), but for historical reasons dandi serves them at the root of the API. This updates the routes to match the Resonant convention. We may want to come back to this later and deprecate/remove the old routes after some time, but for now the old routes are still available and simpy redirect to the new ones.
=> Update swagger/redocs urls to align with Resonant

dandiapi/settings.py
Fixes #2319
This commit switches the staging environment back to using the builtin `Application` model for OAuth2 authentication, while enabling the `ALLOW_URI_WILDCARDS` setting to allow for wildcard URIs to support Netlify deploy previews.
To be extra cautious, I did not remove the custom `StagingApplication` model yet. I think we should merge this, verify it works properly, and only then remove the custom model.
=> Switch staging back to builtin oauth `Application`

dandiapi/settings.py
This setting needs to be specified using the `OAUTH2_PROVIDER` dict.
https://django-oauth-toolkit.readthedocs.io/en/latest/settings.html#settings
=> Fix oauth2 setting

dandiapi/settings.py
Fixes an issue introduced in #2335 that caused the upstream `OAUTH2_PROVIDER` dict in `django-composed-configuration` to get overwritten.
=> Don't override oauth2_provider settings dict

web/src/App.vue, web/src/components/InfoBanner.vue, web/src/views/HomeView/HomeView.vue
Fix #2302 
This moves the previously implemented `FooterBanner` component to the main `App.vue` component, making it visible on all pages.
=> Move banner with info blurb to top of all pages

dandiapi/api/management/commands/collect_garbage.py, dandiapi/api/services/garbage_collection/__init__.py, dandiapi/api/services/garbage_collection/asset_blob.py, dandiapi/api/services/garbage_collection/upload.py, dandiapi/api/tests/test_garbage_collection.py
This hooks up the asset blob and upload garbage collection implementations to the existing stubbed-out `collect_garbage` management command. I recommend reviewing in commit order, as there was some minor refactoring of the `garbage_collection` service layer in order to make it callable from a management command neatly.
Closes #2161
Closes #2160 
In addition to the two issues above, this also partially addresses #2166. Once this is merged I'll test the management command on staging to verify it behaves as expected, and then we can run it on production. I'll hold off on enabling the automatic GC cron job until full `Asset` garbage collection is implemented and ready to be automated as well.
=> Integrate `garbage_collection` service into `collect_garbage.py`

DEVELOPMENT.md
Fixes https://github.com/dandi/dandi-archive/issues/2296
Command itself was removed in https://github.com/dandi/dandi-archive/pull/1335
=> Remove import_dandisets command from docs

web/package.json
eslint will not fail on warnings by default, meaning that CI will pass even if there are frontend lint warnings. This commit makes `yarn run lint` fail with a nonzero exit code if there are any lint warnings.
=> Make eslint fail on warning

web/src/components/DandisetsPage.vue
Fix #1764 
Fix #2176 
Replaces the current sorting controls on the Dandisets page with a more compact, mobile-friendly widget. Based on the design by @jtomeck outlined in #1764.
https://github.com/user-attachments/assets/153f07c2-dc81-4f8c-a239-b882aa40e0e6
=> Update sorting controls for Dandisets page

web/src/components/DandisetsPage.vue
Fix #2365 
Previous margin (https://dandiarchive.org as of 4/30/2025):
New margin (local development environment):
=> Remove margin around DandisetList

e2e/utils.ts
=> Fix Frontend CI Failing: remove " " from the Sign In/Up button names

dandiapi/api/templates/api/mail/approved_user_message.txt
Since the current template results in the following message:
=> Fix formatting of approved user message template

web/src/components/DandiFooter.vue, web/src/components/FileBrowser/FileUploadInstructions.vue, web/src/views/CreateDandisetView/CreateDandisetView.vue, web/src/views/DandisetLandingView/DownloadDialog.vue
- Fixed a few links that were referencing the old "numbered" pages
- Also replaced a few hardcoded references to https://docs.dandiarchive.org with the variable `dandiDocumentationUrl`
=> Fix broken/out-of-date docs links

MANIFEST.in
In principle I think it is ok and might even be desired to be shipped since it provides a component potentially to use with "dandiapi", but indeed there is no usecase ATM which would deploy both components from the sdist shipped to PyPI or anywhere else.
Closes #1724
<details>
<summary>Listing now</summary> 
```shell
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- setuptools
- setuptools-scm
* Getting build dependencies for sdist...
running egg_info
creating dandiapi.egg-info
writing dandiapi.egg-info/PKG-INFO
writing dependency_links to dandiapi.egg-info/dependency_links.txt
writing requirements to dandiapi.egg-info/requires.txt
writing top-level names to dandiapi.egg-info/top_level.txt
writing manifest file 'dandiapi.egg-info/SOURCES.txt' …
```
=> Prune web/ from sdist of dandiarchive/ and thus when uploading to heroku

dandiapi/api/tests/test_robots.py, dandiapi/api/views/robots.py
Continuation to try to re-enable googlebot to index our archive but without introducing heavy load on the website.  The goal here is to allow all end point hitting DLPs
filtered listing of assets is ATM to sense if dandiset has a zarr archive in it, so we could potentially disable publishing. There is a generic https://github.com/dandi/dandi-archive/issues/2404 asking to avoid that. But for now for DLP to load fully we need to allow for that end point.
The URL looks like
https://api.dandiarchive.org/api/dandisets/000026/versions/draft/assets/?zarr=true&page_size=1 and while reading
https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt I got impression that query options (after ?) are also considered, so we can just overall just allow queries which are of …
=> ENH: allow googlebot also /search endpoint and for filtered listing of assets

web/src/components/Search/forms/SpeciesForm.vue
This got missed in CI in #2422. The `paths_ignore` directive combined with the force push seems to have resulted in that check not being run on https://github.com/dandi/dandi-archive/actions/runs/16029771666?pr=2422.
=> Fix type checking error

DEVELOPMENT.md
Depends on #2435 
Original comment by @danlamanna https://github.com/dandi/dandi-archive/pull/2435#discussion_r2198659552
Using `1.` for all items in ordered lists allows for the markdown renderer to automatically order the items, without needing to manually manage it.
=> Use 1. for all items in markdown ordered lists

dandiapi/api/tests/test_asset.py, dandiapi/api/views/asset.py
fix #2413
The implementation involved:
1. Adding filter backends and the filterset class to the `NestedAssetViewSet` class in `dandiapi/api/views/asset.py`:
```python
filter_backends = [filters.DjangoFilterBackend]
filterset_class = AssetFilter
```
This change enables the existing `AssetFilter` class's ordering capability, which already supported ordering by:
- `created` (creation date)
- `modified` (modification date)
- `path` (asset path)
2. I added comprehensive tests to verify the ordering functionality works correctly for different scenarios:
- Ordering by created, modified, and path fields in both ascending and descending order
- Testing with authenticated users
- Testing with embargoed assets
Users can now order assets by date modified (and other fields) in the REST API endpoint …
=> ENH: add filtering capabilities to NestedAssetViewSet

web/src/views/DandisetLandingView/ExternalDandisetServicesDialog.vue
I missed this in #2439. We should probably move this to a env var and set it via Terraform using a reference to the associated `aws_route53_record` resource, but this fixes it for the time being.
=> Update hardcoded staging URL

dev/export-env-fish.sh
Multiple developers on the project use fish shell, and have come up with hacky workarounds to source environment variables from `.env` files. This script is meant to standardize that experience.
=> Add source script for fish shell

pyproject.toml
Follow up to #2469. Heroku requires this file to be present in the sdist.
=> Ensure `requirements.txt` is included in sdist

pyproject.toml
Follow up to #2470. These files are required by Heroku and thus also need to be included in the sdist.
See logs on https://github.com/dandi/dandi-archive/actions/runs/16788169095/job/47543851715
=> Include other files needed by Heroku in sdist

pyproject.toml
ATM installation of development environment (on python 3.11.2 on my Debian bookworm server) results in a lot of backtracking, which starts with
INFO: pip is looking at multiple versions of dandi to determine which version is compatible with other requirements. This could take a while.
Collecting dandi
Downloading dandi-0.69.2-py3-none-any.whl (354 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.1/354.1 kB 66.3 MB/s eta 0:00:00
Downloading dandi-0.69.1-py3-none-any.whl (352 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.2/352.2 kB 45.1 MB/s eta 0:00:00
Downloading dandi-0.69.0-py3-none-any.whl (351 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 351.5/351.5 kB 59.9 MB/s eta 0:00:00
...
Since we declare currently minimal version to be
❯ curl --silent https://dandiarchive.org/server-info | …
=> Declare  the same minimal version of dandi-cli as we announce in /info (/server-info)

web/src/components/Meditor/Meditor.vue
Follow up to #2471. 
Closes #2464
If single quotes were included in the text field, the buggy behavior persisted.
=> Fix broken behavior when text includes single quotes

DEVELOPMENT.md
This PR updates the instructions in `DEVELOPMENT.md` pertaining to installing this project locally for development. Specifically, it updates the dependency requirement from `psycopg2` to `psycopg` and added an example to illustrate how to install the system requirement of `libpq` in MacOS.
**Note**
=> Improve and update doc regarding the `psycopg` dependency and its system dependencies

web/src/views/FileBrowserView/FileBrowser.vue
NIfTI-Zarr is a file format that builds on OME-Zarr - https://github.com/neuroscales/nifti-zarr.  This pull request permits NIfTI-Zarr assets to be directly opened with the OME-Zarr Validator and thereby Neuroglancer.
Here is an [example](https://ome.github.io/ome-ngff-validator/?source=https://dandiarchive.s3.amazonaws.com/zarr/4bdb98bb-bb2a-471f-983f-12e22fa4753a/) NIfTI-Zarr asset opened with the OME-Zarr Validator, which is from [Dandiset 724](https://dandiarchive.org/dandiset/000724/draft/files?location=derivatives/dwi/sub-I58&page=1).
cc @balbasty @calvinchai @satra @ayendiki
=> Add support to open NIfTI-Zarr assets with the OME-Zarr Validator external service

dandiapi/api/storage.py, dandiapi/zarr/models.py
This was missed in #2069, preventing uploaded zarrs from being tagged with `embargoed=true`.
=> Support embargo tags in generated zarr upload URLs

.github/workflows/release.yml
The `release` action started failing on `master` - https://github.com/dandi/dandi-archive/actions/runs/16977062954/job/48128647939
I'm not sure what's causing it yet, but the only recent change to that file was #2465, so this PR just reverts that change.
=> Revert change to github token

.github/workflows/cli-integration.yml
This reverts commit e56151570fbb0a80b9dcca3f6920d67ff8fece54.
This can be merged after the CLI repo is updated by https://github.com/dandi/dandi-cli/pull/1678.
=> Revert "Temporarily point CLI tests at PR branch"

dandiapi/api/logging.py, dandiapi/settings/base.py
Configures Django's logging to append usernames to HTTP request logs if the request is associated with an authenticated user.
There isn't a clean way to get access to the `request.user` object globally, so I've stored it in a `ContextVar` as the Python logging cookbook outlines here https://docs.python.org/3/howto/logging-cookbook.html#use-of-contextvars.
=> Add middleware/logger to log username on every request

dev/django.Dockerfile
https://github.com/dandi/dandi-archive/pull/2466 removed `setup.py` and `setup.cfg`, but `django.Dockerfile` was never updated with the corresponding changes, so that image currently fails to build.
=> Fix Dockerfile for dev django

dandiapi/api/management/commands/collect_garbage.py
In the `echo_report()` script, there was a bug occuring when no asset blobs were found for garbage collection.
**Bug:**
Given the following,
```
asset_blobs_size_in_bytes = garbage_collectable_asset_blobs.aggregate(Sum('size'))['size__sum']
...
click.echo(
f'AssetBlobs: {asset_blobs_count} ({asset_blobs_size_in_bytes} bytes / '
f'{asset_blobs_size_in_bytes / (1024 ** 3):.2f} GB)'
)
```
If `len(garbage_collectable_asset_blobs) == 0`, then `asset_blobs_size_in_bytes` is `None`, resulting in an error trying to calculate `asset_blobs_size_in_bytes / (1024**3)`.
**Solution**
I've changed the assignemnt to the following, setting `asset_blobs_size_in_bytes` to `0` rather than `None` in the case of no asset blobs found.
```
asset_blobs_size_in_bytes = ( …
```
=> Fix Bug in collect_garbage.py with printing

dandiapi/api/services/audit/__init__.py
Fixes #2508
This updates the asset-related audit service functions to include the asset `size` in audit records. I'll follow this up with another PR that backfills the existing audit records.
=> Include asset size in audit record

e2e/tests/dandisetsPage.spec.ts, web/src/components/AppBar/AppBar.vue
I'm proposing a slight redesign of the navigation to close #2362.
In the screenshot you'll see that the nav items have been converted to `v-tabs` and the external links now live under a dropdown menu labeled "External Resources." I'm proposing this change because I do not believe decreasing paddings or font sizes in the menu is the right solution, nor do I like the idea of writing custom CSS to do so (Vuetify's methods, like `density="compact"` only change height and do not save horizontal space).
=> Fix avatar and new dandiset button line break issue in header

web/src/components/DandiFooter.vue
https://docs.dandiarchive.org/about/terms/ and https://docs.dandiarchive.org/about/policies/ lead to 404 page.
=> Fix broken links: Terms and Policies

dandiapi/settings/production.py, dandiapi/urls.py
`SOCIALACCOUNT_ONLY` allows only GitHub authentication, while not requiring any differences in `urls.py` between production and dev. https://docs.allauth.org/en/dev/socialaccount/configuration.html
Fixes #2515
=> Use allauth setting to restrict prod to github auth

dandiapi/api/management/commands/rectify_manifest_tags.py, dandiapi/api/manifests.py, dandiapi/api/services/embargo/utils.py, dandiapi/api/tests/test_manifests.py, dandiapi/api/tests/test_unembargo.py
It appears embargo tags were never applied to manifest files. This PR ensures going forward, the proper embargo tags are applied to the manifest files of embargoed dandisets, when generated. It also includes the corresponding unembargo functionality, as well as a management command to apply the tags to embargoed dandisets.
=> Apply embargo functionality to dandiset manifest files

dandiapi/api/management/commands/create_dev_dandiset.py, dandiapi/api/services/audit/__init__.py, dandiapi/api/services/dandiset/__init__.py, dandiapi/api/services/version/metadata.py, dandiapi/api/views/dandiset.py, dandiapi/api/views/serializers.py
This PR is based on top of #2462, making some refactors that I think are improvements.
The core change is splitting out the `create_dandiset()` service layer function into two separate functions - `create_open_dandiset()` and `create_embargoed_dandiset()`. I think the `create_dandiset` function has gotten too bloated, especially with all the new logic and function arguments that only apply to embargoed dandisets.
=> Fix embargoed dandiset creation form (Suggested Changes)

dandiapi/settings/production.py
`django-resonant-settings` currently specifies this setting incorrectly as a `float`, when it should be an `int`. See https://github.com/kitware-resonant/cookiecutter-resonant/pull/369
=> Temporarily override broken upstream setting

web/package.json, web/yarn.lock
There has been an issue lately that would cause a GUI error when a user attempted to load the GUI with expired credentials. The ad-hoc solution was to reset the browser cache, or initiate a login manually. This behavior is fixed by https://github.com/kitware-resonant/resonant-oauth-client/releases/tag/v1.0.3.
=> Fix intermittent login error

dandiapi/api/tests/test_schema.py, dandiapi/urls.py, doc/design/vendored-schema-1-implementation.md, doc/design/vendored-schema-1.md
~~This PR changes the endpoint for severing the list of available schemas from `api/schema/available` to `api/schemas`.~~
This PR changes the endpoints related to serving schemas of DANDI metadata models. From 
```
'api/schema/available'
'api/schema/'
```
to
```
'api/schemas/available/'
'api/schemas/'
Additionally, this PR also updates the documentation regarding these endpoints.
=> Change endpoints related to serving schemas of DANDI metadata models

dandiapi/api/tests/test_asset.py, dandiapi/api/tests/test_audit.py, dandiapi/api/tests/test_dandiset.py, dandiapi/api/tests/test_permission.py, dandiapi/api/tests/test_upload.py, dandiapi/api/tests/test_users.py, dandiapi/api/tests/test_version.py, dandiapi/zarr/tests/test_zarr.py, dandiapi/zarr/tests/test_zarr_upload.py
The setting `"TEST_REQUEST_DEFAULT_FORMAT": "json"` in: https://github.com/kitware-resonant/cookiecutter-resonant/blob/8546ec918977f7aaca42cc290fe97632fdd87eeb/django-resonant-settings/resonant_settings/rest_framework.py#L63-L64 ensures that `APIRequestFactory` will already format request bodies with JSON:
https://www.django-rest-framework.org/api-guide/testing/#setting-the-default-format
=> Remove unnecessary `format` argument from `APIRequestFactory` instances

dandiapi/api/tests/test_audit.py, dandiapi/zarr/tests/test_zarr_upload.py
* Improve coverage of `test_zarr_rest_upload_start`, by actually uploading a file
* Remove unnecessary code from `test_audit` tests, outside the scope of testing audit records
=> Improve Zarr upload tests

dandiapi/settings/base.py
This doesn't change any behavior, but it required by the upstream package to avoid warnings.
=> Fix a drf-yasg warning

web/src/utils/externalServices.ts
Supported formats include `.nii`, `.nii.gz`, `.ome.zarr`, and `.nii.zarr`.
Here is a [link](https://www.neuroglass.io/new?resource=https://api.dandiarchive.org/api/assets/012dd675-6bc9-429b-920d-5d8ac8afa681) to an example DANDI asset opened in NeuroGlass.
cc @satra @ayendiki @balbasty
=> Add support to open NIfTI and Zarr assets in NeuroGlass ephemeral mode

pyproject.toml
This ensures that all warnings (which were important enough for a library to emit) are affirmatively acted upon. False positive or WONTFIX warnings can always be ignored via `filterwarnings`.
=> Flag all warnings as test failures
